In [2]:
import pandas as pd
import numpy as np
import psutil
from unidecode import unidecode
from fuzzywuzzy import fuzz
from collections import defaultdict
import json

# Check memory usage
def memory_usage():
    process = psutil.Process()
    mem_info = process.memory_info()
    return mem_info.rss / (1024 * 1024)  # Convert bytes to MB

print(f"Memory usage: {memory_usage()} MB")

Memory usage: 98.00390625 MB

In [3]:
# Set pandas display options
pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.max_colwidth', None)  # Show full column width
pd.set_option('display.expand_frame_repr', False)  # Disable wrapping of rows

In [4]:
main = pd.read_csv('./e_patrul_users_and_units.csv')
main.head()

    id  account_non_expired  account_non_locked  active                    home_address  age  cadastre  citizenship                  created_at  created_by  credentials_non_expired               date_of_birth  email  enabled  first_name              full_name  ip_address  language   last_name   latitude living_address  living_place  longitude  middle_name passport_number                                                      password         phone_number                                                                                               photo            pnfl position    rank   sex  spam_time  telegram_id                  updated_at  updated_by    username  uuid  work_place  working_address  district_id  region_id  management_id  is_patrol  battery  speed is_guard                               session in_zone  zone_district_id  group  squad  black_list  region_id.1      region_name  district_id.1   district_name                                                                           activities
0    1                 True                True    True  Toshkent shahar Mirobod tumani   20       NaN          NaN  2023-04-15 23:36:35.786000         NaN                     True  2023-04-20 00:00:00.000000    NaN     True       Admin              Super SSD         NaN       NaN       Admin  41.262632            NaN           NaN  69.266267          NaN       AA6573787  $2a$10$K5NwS/Znffnzn4zKhgLqIO9gq2SuiYaBiXvvAg7./PcLLZaOVHPIO        +998901234567                              ?fileName=ePatrul/files/2023/12/1/6f0ed1cb-aac2-4428-b0d0-7131b1456eb0  12345678910111      NaN     NaN  MALE        NaN          NaN  2025-03-24 12:09:23.095000         NaN   shield655   NaN         NaN              NaN          NaN        NaN            NaN      False      NaN    NaN      NaN  0d39ccd6-75b2-4b92-9b02-90f2688fc77c     NaN               NaN    NaN    NaN       False          NaN              NaN            NaN             NaN                                                       [{"id" : null, "name" : null}]
1    2                 True                True    True     Toshkent shahar oybek metro   20       NaN          NaN  2023-04-15 23:36:35.881000         NaN                     True                         NaN    NaN     True  Shamsiddin  Anvardinov Shamsiddin         NaN       NaN  Anvardinov  41.262632            NaN           NaN  69.266267          NaN             NaN  $2a$10$OtluEMDnCnu.XSQulz/u3umJgVH8gte40ZNpsdW9EfvnOTSVjyA1m        +998903744007                                                                                                 NaN  78945612396325      NaN     NaN  MALE        NaN          NaN  2023-04-15 23:36:35.881000         NaN  shamsiddin   NaN         NaN              NaN          NaN        NaN            NaN      False      NaN    NaN      NaN                                   NaN     NaN               NaN    NaN    NaN       False          NaN              NaN            NaN             NaN                                                       [{"id" : null, "name" : null}]
2   52                 True               False   False                             NaN    0       NaN          NaN  2023-04-18 08:52:06.474000         NaN                     True  2023-04-17 19:00:00.000000    NaN     True         NaN           Test Patrol          NaN       NaN         NaN  41.302497            MVD           NaN  69.263965          NaN       ac1231231  $2a$10$v7PAQZAHeoptlKzrrRIy9uxg4I4/QWAu421mHBJMBM9DPpSDTTyJ6        +998777777333  http://10.254.7.1:10011/api/v1/attachment?fileName=ePatrul/files/2023/5/2/FOTO_20230502_122019.jpg  34563452351234     RANK  Safdor   NaN        NaN          NaN  2023-11-28 10:58:38.834000         NaN        1234   NaN         NaN  custom yonalush          NaN        9.0            NaN       True     56.0    0.0    False  61b1a901-2305-47e6-8845-23a8b45b48be     NaN               NaN    NaN    NaN       False          9.0  Toshkent shahar            NaN             NaN                                                         [{"id" : 3, "name" : "PPX"}]
3   53                 True                True   False                             NaN    1       NaN          NaN  2023-04-18 09:05:46.231000         NaN                     True  2023-04-18 19:00:00.000000    NaN     True         NaN             Test admin         NaN       NaN         NaN        NaN            MVD           NaN        NaN          NaN       ac1231251  $2a$10$AchA0vzekfeWm7BXZ0Pvqen0Sd1yn19tu7dJ0rvy3LHIZVllCczuK  +998 (22) 222-22-22                                                        ?fileName=ePatrul/files/2023/4/18/images.png  43643576323123    admin   Admin   NaN        NaN          NaN  2024-01-23 12:20:20.764000         NaN        4321   NaN         NaN              MVD          1.0        1.0            NaN      False      NaN    NaN    False                                   NaN     NaN               NaN    NaN    NaN       False          1.0          Andijon            1.0  Andijon tumani  [{"id" : 2, "name" : "PI"}, {"id" : 4, "name" : "JQB"}, {"id" : 4, "name" : "JQB"}]
4  102                 True               False   False                             NaN    1       NaN          NaN  2023-04-19 09:10:02.507000         NaN                     True  2023-04-09 19:00:00.000000    NaN     True         NaN    test statistics for         NaN       NaN         NaN        NaN         testde           NaN        NaN          NaN       AV1234564  $2a$10$3dqIqDlwy3GcNDJvAkrJYO7qP9UnoFTdS1Sc0kPyW4VpJYfOnSnWW  +998 (33) 333-33-33                                                   ?fileName=ePatrul/files/2023/4/19/Kim Chin In.jpg  12154674874123      DEV  Safdor   NaN        NaN          NaN  2024-06-19 13:50:08.067000         NaN   AV1234564   NaN         NaN      Turgan joyi         81.0        6.0            NaN       True      NaN    NaN    False                                   NaN     NaN               NaN    NaN    NaN       False          6.0           Jizzax           81.0          Jizzax                                                         [{"id" : 3, "name" : "PPX"}]

In [5]:
df = main.copy()
# df.columns = [f'col_{i}' for i in range(len(df.columns))]
df.activities = [json.loads(i)[0]['name'] if len(json.loads(i)) == 1 else json.loads(i) for i in df.activities]
# df.tail(50)
df.head(10)

    id  account_non_expired  account_non_locked  active                    home_address  age  cadastre  citizenship                  created_at  created_by  credentials_non_expired               date_of_birth  email  enabled  first_name                              full_name  ip_address  language   last_name   latitude                                         living_address  living_place  longitude  middle_name passport_number                                                      password         phone_number                                                                                               photo            pnfl       position       rank   sex  spam_time  telegram_id                  updated_at  updated_by    username  uuid  work_place  working_address  district_id  region_id  management_id  is_patrol  battery  speed is_guard                               session in_zone  zone_district_id  group  squad  black_list  region_id.1      region_name  district_id.1     district_name                                                                     activities
0    1                 True                True    True  Toshkent shahar Mirobod tumani   20       NaN          NaN  2023-04-15 23:36:35.786000         NaN                     True  2023-04-20 00:00:00.000000    NaN     True       Admin                              Super SSD         NaN       NaN       Admin  41.262632                                                    NaN           NaN  69.266267          NaN       AA6573787  $2a$10$K5NwS/Znffnzn4zKhgLqIO9gq2SuiYaBiXvvAg7./PcLLZaOVHPIO        +998901234567                              ?fileName=ePatrul/files/2023/12/1/6f0ed1cb-aac2-4428-b0d0-7131b1456eb0  12345678910111            NaN        NaN  MALE        NaN          NaN  2025-03-24 12:09:23.095000         NaN   shield655   NaN         NaN              NaN          NaN        NaN            NaN      False      NaN    NaN      NaN  0d39ccd6-75b2-4b92-9b02-90f2688fc77c     NaN               NaN    NaN    NaN       False          NaN              NaN            NaN               NaN                                                                           None
1    2                 True                True    True     Toshkent shahar oybek metro   20       NaN          NaN  2023-04-15 23:36:35.881000         NaN                     True                         NaN    NaN     True  Shamsiddin                  Anvardinov Shamsiddin         NaN       NaN  Anvardinov  41.262632                                                    NaN           NaN  69.266267          NaN             NaN  $2a$10$OtluEMDnCnu.XSQulz/u3umJgVH8gte40ZNpsdW9EfvnOTSVjyA1m        +998903744007                                                                                                 NaN  78945612396325            NaN        NaN  MALE        NaN          NaN  2023-04-15 23:36:35.881000         NaN  shamsiddin   NaN         NaN              NaN          NaN        NaN            NaN      False      NaN    NaN      NaN                                   NaN     NaN               NaN    NaN    NaN       False          NaN              NaN            NaN               NaN                                                                           None
2   52                 True               False   False                             NaN    0       NaN          NaN  2023-04-18 08:52:06.474000         NaN                     True  2023-04-17 19:00:00.000000    NaN     True         NaN                           Test Patrol          NaN       NaN         NaN  41.302497                                                    MVD           NaN  69.263965          NaN       ac1231231  $2a$10$v7PAQZAHeoptlKzrrRIy9uxg4I4/QWAu421mHBJMBM9DPpSDTTyJ6        +998777777333  http://10.254.7.1:10011/api/v1/attachment?fileName=ePatrul/files/2023/5/2/FOTO_20230502_122019.jpg  34563452351234           RANK     Safdor   NaN        NaN          NaN  2023-11-28 10:58:38.834000         NaN        1234   NaN         NaN  custom yonalush          NaN        9.0            NaN       True     56.0    0.0    False  61b1a901-2305-47e6-8845-23a8b45b48be     NaN               NaN    NaN    NaN       False          9.0  Toshkent shahar            NaN               NaN                                                                            PPX
3   53                 True                True   False                             NaN    1       NaN          NaN  2023-04-18 09:05:46.231000         NaN                     True  2023-04-18 19:00:00.000000    NaN     True         NaN                             Test admin         NaN       NaN         NaN        NaN                                                    MVD           NaN        NaN          NaN       ac1231251  $2a$10$AchA0vzekfeWm7BXZ0Pvqen0Sd1yn19tu7dJ0rvy3LHIZVllCczuK  +998 (22) 222-22-22                                                        ?fileName=ePatrul/files/2023/4/18/images.png  43643576323123          admin      Admin   NaN        NaN          NaN  2024-01-23 12:20:20.764000         NaN        4321   NaN         NaN              MVD          1.0        1.0            NaN      False      NaN    NaN    False                                   NaN     NaN               NaN    NaN    NaN       False          1.0          Andijon            1.0    Andijon tumani  [{'id': 2, 'name': 'PI'}, {'id': 4, 'name': 'JQB'}, {'id': 4, 'name': 'JQB'}]
4  102                 True               False   False                             NaN    1       NaN          NaN  2023-04-19 09:10:02.507000         NaN                     True  2023-04-09 19:00:00.000000    NaN     True         NaN                    test statistics for         NaN       NaN         NaN        NaN                                                 testde           NaN        NaN          NaN       AV1234564  $2a$10$3dqIqDlwy3GcNDJvAkrJYO7qP9UnoFTdS1Sc0kPyW4VpJYfOnSnWW  +998 (33) 333-33-33                                                   ?fileName=ePatrul/files/2023/4/19/Kim Chin In.jpg  12154674874123            DEV     Safdor   NaN        NaN          NaN  2024-06-19 13:50:08.067000         NaN   AV1234564   NaN         NaN      Turgan joyi         81.0        6.0            NaN       True      NaN    NaN    False                                   NaN     NaN               NaN    NaN    NaN       False          6.0           Jizzax           81.0            Jizzax                                                                            PPX
5  103                 True                True   False                             NaN   25       NaN          NaN  2023-04-19 09:34:29.791000         NaN                     True  1999-02-15 19:00:00.000000    NaN     True         NaN            ORIFOVA LOBAR RISQIBOY QIZI         NaN       NaN         NaN  41.302713  ПАРКЕНТ Ш., МОЗОРХОЖИ МФЙ, МИРСОДИКОВ КЎЧАСИ,  uy:116           NaN  69.263925          NaN       AB4669865  $2a$10$szOXH9ZLTRmrSUbxj1DyTeAIJbH2fNwWHKs1fqbFOrHOIoP2nsgS6  +998 (94) 423-47-74                             ?fileName=ePatrul/files/2024/12/23/859708fe-fe13-4e98-8eb5-ba6f1fc3d0bb  41602996770023           test      Mayor   NaN        NaN          NaN  2025-03-19 10:40:52.710000         NaN       lobar   NaN         NaN    mirzo ulugbek          NaN        9.0            NaN       True     62.0    0.0    False  7f18e701-15aa-47b7-8611-800e4ca0ccc1     NaN               NaN    NaN    NaN       False          9.0  Toshkent shahar            NaN               NaN                                                                            JQB
6  104                 True                True   False                             NaN    0       NaN          NaN  2023-04-19 09:48:01.003000         NaN                     True  2023-03-31 19:00:00.000000    NaN     True         NaN                                  Kerim         NaN       NaN         NaN        NaN                                              samarqand           NaN        NaN          NaN       AA1234567  $2a$10$ODS4Zm7Zfvd.foVUX4yrxONkeRCzpkWvigubIxg0qVsZocK9IHvle  +998 (65) 465-46-54                                                          ?fileName=ePatrul/files/2023/4/19/doni.jpg    413657852255         tester     Safdor   NaN        NaN          NaN  2024-10-19 03:49:48.144000         NaN         123   NaN         NaN           manzil         30.0        3.0            NaN       True      NaN    NaN    False  4eeda370-6153-44f5-bd4d-9757529d48a4     NaN               NaN    NaN    NaN       False          3.0        Samarqand           30.0  Bulung'ur tumani                                                                            PPX
7  302                 True                True   False                             NaN   25       NaN          NaN  2023-04-27 21:08:19.703000         NaN                     True  1998-05-24 19:00:00.000000    NaN     True         NaN  ANVARDINOV SHAMSIDDIN PANAYDIN O‘G‘LI         NaN       NaN         NaN  41.326400               НАВРЎЗ МФЙ, ТЕМИРЙУЛЧИЛАР КЎЧАСИ,  uy:71           NaN  69.320167          NaN       AD2072759  $2a$10$NtUaqLhg5nLTc4O2QOp9YuiQVP.LsMw8R7eiJkzFZe1sUQoQ9Mi5.  +998 (90) 374-40-07                              ?fileName=ePatrul/files/2023/8/10/f8de72ce-69a8-43cc-befd-cfc1684ab501  32505986530013      Developer  Leytenant   NaN        NaN          NaN  2025-03-13 12:05:37.336000         NaN        4007   NaN         NaN     Toshkent MVD          NaN        9.0            NaN       True     96.0    0.0    False  d4c30b44-fd86-4c4a-975e-d657068c88ae     NaN               NaN    NaN    NaN       False          9.0  Toshkent shahar            NaN               NaN                                                                            PPX
8  402                 True               False   False                             NaN   28       NaN          NaN  2023-05-18 10:56:46.829000         NaN                     True  1996-03-10 19:00:00.000000    NaN     True         NaN                        Rustam Qahhorov         NaN       NaN         NaN  41.326836                                       Andijon viloyati           NaN  69.317739          NaN       AA1234589  $2a$10$9Pg3J9s3a7c2PCmgvzS.JerAxRof7nHoaJeEOBnNjEU9WIsMIpo.u  +998 (99) 663-35-52                          ?fileName=ePatrul/files/2023/5/18/bc9a0f22-eeaa-44ef-bbc1-e24166813cd2.jpg  41254236589754  viloyat admin      Mayor   NaN        NaN          NaN  2024-06-27 13:13:25.855000         NaN   AA1234589   NaN         NaN   andijon shaxar          NaN        1.0            NaN       True     60.0    5.0    False  b9f56537-fdae-4041-9c56-06c7e4a8cfbf     NaN               NaN    NaN    NaN       False          1.0          Andijon            NaN               NaN                                                                            PPX
9  403                 True                True   False                             NaN   31       NaN          NaN  2023-05-18 10:58:59.609000         NaN                     True  1993-03-10 19:00:00.000000    NaN     True         NaN                        Doniyor Usmonov         NaN       NaN         NaN        NaN                                        Buxoro viloyati           NaN        NaN          NaN       AA8956233  $2a$10$Q35u99lgB5MzjB89JJFIau5H3E6tFJIxDvvjZsiHRJykhIg0hURkS  +998 (99) 687-54-32                                                       ?fileName=ePatrul/files/2023/5/18/andijon.jpg  45876953210369    tuman admin      Mayor   NaN        NaN          NaN  2024-01-23 12:14:37.082000         NaN   AA8956233   NaN         NaN   buxoro viloyat         17.0        2.0            NaN      False      NaN    NaN    False  ba5a8a7d-9d1d-4ac7-9fdf-712e5e757be6     NaN               NaN    NaN    NaN       False          2.0           Buxoro           17.0     Buxoro tumani                                                                             PI

In [6]:
# [{"id" : 2, "name" : "PI"}, {"id" : 4, "name" : "JQB"}, {"id" : 4, "name" : "JQB"}]
# df[df['activities'] == '[{"id" : 3, "name" : "PPX"}, {"id" : 2, "name" : "PI"}, {"id" : 4, "name" : "JQB"}]']
# df[df['activities'] == '[{"id" : 2, "name" : "PI"}, {"id" : 3, "name" : "PPX"}, {"id" : 4, "name" : "JQB"}]']
# df[df['activities'] == '[{"id" : 3, "name" : "PPX"}, {"id" : 4, "name" : "JQB"}, {"id" : 2, "name" : "PI"}]']
# df[df['activities'] == '[{"id" : null, "name" : null}]']
# df[df['full_name'] == 'ABDULAZIZOV SARDORBEK ALISHERJON O‘G‘LI']
df['squad'].value_counts()

1.0     2169
2.0      904
3.0      386
6.0      319
4.0      293
10.0     273
7.0      100
8.0       77
11.0      63
12.0      22
13.0      20
5.0        8
9.0        2
14.0       1
Name: squad, dtype: int64

In [7]:
main_df = df[['id','full_name','living_address','passport_number','phone_number','pnfl','position','rank','working_address','session','group','squad','region_name','district_name','activities']]
main_df.tail()

         id                           full_name                                                           living_address passport_number         phone_number            pnfl           position    rank                   working_address session  group  squad       region_name district_name activities
9514  19131   RAMAZONOV DOSTON BAXRIDDIN O‘G‘LI  Навоийская область, Навбахорский район, Карвон МСГ, ул. Шукрона, дом 50       AB5372725  +998 (95) 849-14-72  30712922350022         TXTB PPXB   Safdor  Navoiy shahar temir yo'l vogzali     NaN    1.0    NaN            Navoiy           NaN        PPX
9515  19132         ALIJONOVA OLIMA OTABEK QIZI                        НАВКЕНТ ҚФЙ, НАВКЕНТ МФЙ, НАВКЕНТ КЎЧАСИ,  uy:Р/С       AB2329716  +998 (77) 211-88-99  40704985950025  Mutaxassis o'qchi  Safdor                   MG Namangan VBB     NaN    NaN    NaN          Namangan           NaN         MG
9516  19133  MIRZABOYEVA MASTURA G‘OFURJON QIZI                          БАХТ ҚФЙ, КАТТАЧЕК МФЙ, ДЎСТЛИК КЎЧАСИ,  uy:Р/С       AD5931385  +998 (97) 682-33-77  40112975940026     Mutaxassis o'q  Safdor                   MG Namangan VBB     NaN    NaN    NaN          Namangan           NaN         MG
9517  19134  BAXTIYOROV XUMOYUN ULUG‘BEK O‘G‘LI                  Ташкентская область, г.Нурафшан, ул. Дегантепа, дом 329       AB1310593  +998 (99) 816-11-97  31611976800035     ППХ инспектори  Safdor                    тошкент тумани     NaN    1.0    4.0  Toshkent viloyat           NaN        PPX
9518  19135      NURMATOV SHAXZOD ALIJON O‘G‘LI  НАВБАХОР КФЙ, РЕГИСТОН МФЙ, НАВБАХОР КФЙ, РЕГИСТОН МФЙ, А.ТЕМУР,  uy:36       AB2941276  +998 (88) 875-45-45  32611996820029     ППХ инспектори  Safdor                     Янгийўл шаҳри     NaN    1.0    4.0  Toshkent viloyat           NaN        PPX

In [8]:
mg_df = main_df[main_df['activities'] == 'MG']
pi_df = main_df[main_df['activities'] == 'PI']
ppx_df = main_df[main_df['activities'] == 'PPX']
jqb_df = main_df[main_df['activities'] == 'JQB']
none_df = main_df[(main_df['activities'] != 'MG') & (main_df['activities'] != 'PI') & (main_df['activities'] != 'PPX') & (main_df['activities'] != 'JQB')]

In [ ]:
print(mg_df.info())
print(pi_df.info())
print(ppx_df.info())
print(jqb_df.info())
print(none_df.info())

In [9]:
pi_df[pi_df['working_address'] == 'Lutfiy MFY']

        id                         full_name                                living_address passport_number         phone_number            pnfl                  position       rank working_address                               session  group  squad      region_name     district_name activities
1863  9061      BABASHEV BABAMURAD TAIROVICH     Чорвадор МФЙ, Алишер Навоий кучаси, 31-уй       AD1918263  +998 (97) 410-52-25  30601800590099  Profilaktika  inspektori    Kapitan      Lutfiy MFY  c9ef0293-cde1-4876-b539-9f4db13a1a9f    NaN    NaN  Toshkent shahar  Chilonzor tumani         PI
1864  9062  NIYOZOV KOMILJON NOSIRJON O‘G‘LI  ХАЙРАБОД МФЙ, ХАКИМХОН, 4 ТОР КЎЧАСИ,  uy:3А       AB1004027  +998 (90) 924-32-33  33008996590026  Profilaktika  inspektori  Leytenant      Lutfiy MFY  1a9ac3fd-5a42-461e-8396-b48b07488060    NaN    NaN  Toshkent shahar               NaN         PI

In [10]:
none_df.head(3)

   id              full_name living_address passport_number         phone_number            pnfl position   rank working_address                               session  group  squad region_name   district_name                                                                     activities
0   1              Super SSD            NaN       AA6573787        +998901234567  12345678910111      NaN    NaN             NaN  0d39ccd6-75b2-4b92-9b02-90f2688fc77c    NaN    NaN         NaN             NaN                                                                           None
1   2  Anvardinov Shamsiddin            NaN             NaN        +998903744007  78945612396325      NaN    NaN             NaN                                   NaN    NaN    NaN         NaN             NaN                                                                           None
3  53             Test admin            MVD       ac1231251  +998 (22) 222-22-22  43643576323123    admin  Admin             MVD                                   NaN    NaN    NaN     Andijon  Andijon tumani  [{'id': 2, 'name': 'PI'}, {'id': 4, 'name': 'JQB'}, {'id': 4, 'name': 'JQB'}]

In [ ]:
# main_df.to_html('e_patrol_final.html')

In [11]:
# jqb_cnts = jqb_df['position'].value_counts()
mg_cnts = mg_df['position'].value_counts()

In [12]:
# Function to group similar names
def group_similar(series, threshold=80):
	inds = pd.Series(series.index)
	norm_inds = inds.str.lower()
	# Normalize names
	s_normalized = norm_inds.apply(unidecode)
		
	groups = defaultdict(list)
	used = set()

	for i, name in enumerate(norm_inds):
		if name in used:
			continue
		groups[name].append(name)
		for j, other in enumerate(norm_inds):
			if i != j and fuzz.ratio(name, other) >= threshold:
				groups[name].append(other)
				used.add(other)

	return {k: list(set(v)) for k, v in groups.items()}

# Group similar names
# similar_names = group_similar(jqb_cnts, threshold=80)
similar_names = group_similar(mg_cnts, threshold=80)

max_length = max(len(v) for v in similar_names.values())
data = {k: v + [None] * (max_length - len(v)) for k, v in similar_names.items()}
jqb_posi_dict_df = pd.DataFrame(data)
print(jqb_posi_dict_df)

        mutaxassis         guruh komandiri   inspektor        inspektor psixolog  seksiya komandiri   otryad komandiri    mutaxassis haydovchi  mutaxassis mergan  psixolog   guruh komandiri o‘rinbosari    mutaxassis portlatuvchi   katta ofitser    mutahassis o'qchi   mutaxassis kinolog  aloqa boshlig'i    бўлим бошлиғи  mutaxassis pulemyotchi  gurux mutaxassisi  kinolog  haydovchi        3-thmg komandiri  bo'lim boshlig'i   katta inspektor  mutaxassis kovaleriyachi  mutaxassis seksiya komandiri  patrullik guruhi komandiri  otyad kom yordam  инспектор  bbo‘  oʻttaa xasis ages  portlatuvchi  radiotelefonchi  aloqachi  boshqarma boshlig'i o'rinbosari  a.boronov  335960505  mutaxassis radiotelcfonist  otryad komandirining mtbyo  mutaxassis mo‘ljalga oluvchisi  komandir  kmtbyomt  gurux o‘rinbosari  boshliq o'rinbosari  ok mtbyo, mty   mutaxasis yo'naltiruvchi  mutaxassis motosikl   gdsg  uqchi  mutaxassis raqam xisobchi  mutaxasis sapyor;  tezkor navbatchi  98162 harbiy qism  mutaxassis opirotor  komandir seksiya  patrullik guruhi komandiri oʼrinbosari-haydovchi  mutaxassis hisob raqam  mutaxassis haydovchi (motosiklchi))  mutaxassis ags hisobi   gurh kamamdiri yordamchisi  feldsher    mttv komandiri  ofitser  ta’minot bo‘yicha yordamchi  admin  guruh ofitseri  kontrrazvedka boʻlim boshligʻi         komandir oʻrinbosari     ok  mutaxassis feldsher  pulemyotchi  surushtiruv boshlig‘i  surishtiruvchi  yurist  kichik serjant  komandir otryad
0     mutaxassis          guruh  komandiri   inspektor  katta inspektor-psixolog   seksiya komandir    otryd kamandiri       mutaxassis o’qchi  mutaxassis-mergan  psixolog    guruh kamandir urin bosari  mutaxassis portlatuvchisi  katta ofitseri   mutaxassis  o`qchi    mutaxasis kinolog  aloqa boshlig'i  бўлинма бошлиғи   mutaxassis pulemotchi  gurux mutaxassisi  kinolog  haydovchi        3-thmg komandiri  bo‘lim boshlig‘i   katta inspektor  mutaxassis kovaleriyachi  mutaxassis-seksiya komandiri  patrullik guruhi komandiri  otyad kom yordam  инспектор  bbo‘  oʻttaa xasis ages  portlatuvchi  radiotelefonchi  aloqachi  boshqarma boshlig'i o'rinbosari  a.boronov  335960505  mutaxassis radiotelcfonist  otryad komandirining mtbyo  mutaxassis mo‘ljalga oluvchisi  komandir  kmtbyomt  gurux o‘rinbosari  boshliq o'rinbosari  ok mtbyo, mty  mutaxassis yo‘naltiruvchi  mutaxassis motosikl   gdsg  uqchi  mutaxassis raqam xisobchi  mutaxasis sapyor;  tezkor navbatchi  98162 harbiy qism  mutaxassis opirotor  komandir seksiya  patrullik guruhi komandiri oʼrinbosari-haydovchi  mutaxassis hisob raqam  mutaxassis haydovchi (motosiklchi))  mutaxassis ags hisobi  guruh komandiri yordamchisi  feldsher    mttv komandiri  ofitser  ta’minot bo‘yicha yordamchi  admin  guruh ofitseri  kontrrazvedka boʻlim boshligʻi    guruh komandir o’rinbosari    ok  mutaxassis feldsher  pulemyotchi  surushtiruv boshlig‘i  surishtiruvchi  yurist  kichik serjant  komandir otryad
1      mutaxassis         guruh komandiri     ispektor        inspektor psixolog  seksiya komandiri   otryad kamandiri       mutaxassis o'qchi  mutaxassis mergan      None    guruh komandir o’rinbosari    mutaxassis portlatuvchi   katta ofitser    mutaxassis o’qchi   mutaxassis-kinolog   aloqa boshligi    бўлим бошлиғи  mutaxassis pulemyotchi  guruh mutaxassisi     None  xaydovchi  3-thm guruhi komandiri  bo'lim boshlig'i  katta inspektori  mutaxasiss kavaleryachi   mutaxassis seksiya komandiri                        None              None       None  None               None          None             None      None                             None       None       None                        None                        None                            None      None      None               None                 None           None   mutaxassis-yunaltiruvchi                  None  None   None                       None               None              None               None  mutaxassis-operator              None                                              None                    None                                 None                   None   gurh kamamdiri yordamchisi      None  otriat komandiri     None                         None   None            None                            None         komandiri o‘rinbosari  None                 None         None                   None            None    None            None             None
2    mutaxassisi           gurux komandiri    insepkor        inspektor psixolok               None   otryad komandiri    mutaxassis-haydovchi  mutahassis mergan      None   guruh komandiri o‘rinbosari                       None   katta ofitcer    mutahassis o'qchi   mutaxassis kinolik             None             None  mutaxassis pulomyotchi               None     None       None                    None              None              None                      None                          None                        None              None       None  None               None          None             None      None                             None       None       None                        None                        None                            None      None      None               None                 None           None   mutaxasis yo'naltiruvchi                  None  None   None                       None               None              None               None                 None              None                                              None                    None                                 None                   None  gurux komandiri yordamchisi      None              None     None                         None   None            None                            None  guruh komandiri o'rinbosari   None                 None         None                   None            None    None            None             None
3       mutaxassis   guruh komandiri (532)  inspektor                       None               None    otyad komandiri    mutaxassis xaydovchi               None      None         komandiri o‘rinbosari                       None            None    mutaxassis o'qchi    mutaxssis kinolog             None             None                    None               None     None       None                    None              None              None                      None                          None                        None              None       None  None               None          None             None      None                             None       None       None                        None                        None                            None      None      None               None                 None           None                       None                  None  None   None                       None               None              None               None                 None              None                                              None                    None                                 None                   None                         None      None              None     None                         None   None            None                            None         komandir oʻrinbosari   None                 None         None                   None            None    None            None             None
4       mutahassis         guruh komandiri        None                      None               None  otiryad komandiri    mutaxasiss haydovchi               None      None   guruh komandiri o'rinbosari                       None            None  mutaxassis o‘qchisi  mutaxassis kinoligi             None             None                    None               None     None       None                    None              None              None                      None                          None                        None              None       None  None               None          None             None      None                             None       None       None                        None                        None                            None      None      None               None                 None           None                       None                  None  None   None                       None               None              None               None                 None              None                                              None                    None                                 None                   None                         None      None              None     None                         None   None            None                            None   guruh komandiri oʻrinbosari  None                 None         None                   None            None    None            None             None
5        mutaxssis         guruh kamandiri        None                      None               None   otriat komandiri     mutahasis haydovchi               None      None  guruh komandiri o'rinbosari                        None            None    mutaxassis oqchi'   mutaxassis kinolog             None             None                    None               None     None       None                    None              None              None                      None                          None                        None              None       None  None               None          None             None      None                             None       None       None                        None                        None                            None      None      None               None                 None           None                       None                  None  None   None                       None               None              None               None                 None              None                                              None                    None                                 None                   None                         None      None              None     None                         None   None            None                            None          komandir o'rinbosari  None                 None         None                   None            None    None            None             None
6      mutaxassisi  3-thm guruhi komandiri        None                      None               None               None     mutaxasis haydovchi               None      None   guruh komandiri o’rinbosari                       None            None       mutaxassis o'q  mutaxassis kinologi             None             None                    None               None     None       None                    None              None              None                      None                          None                        None              None       None  None               None          None             None      None                             None       None       None                        None                        None                            None      None      None               None                 None           None                       None                  None  None   None                       None               None              None               None                 None              None                                              None                    None                                 None                   None                         None      None              None     None                         None   None            None                            None                          None  None                 None         None                   None            None    None            None             None
7         mutaxsis        guruh  kamandiri        None                      None               None               None     mutaxassis aloqachi               None      None   guruh komandiri oʻrinbosari                       None            None  mutaxassis aloqachi                 None             None             None                    None               None     None       None                    None              None              None                      None                          None                        None              None       None  None               None          None             None      None                             None       None       None                        None                        None                            None      None      None               None                 None           None                       None                  None  None   None                       None               None              None               None                 None              None                                              None                    None                                 None                   None                         None      None              None     None                         None   None            None                            None                          None  None                 None         None                   None            None    None            None             None
8     mutaxassisi           guruh komandir        None                      None               None               None       mutaxassis o‘qchi               None      None          komandir o'rinbosari                       None            None    mutaxassis o‘qchi                 None             None             None                    None               None     None       None                    None              None              None                      None                          None                        None              None       None  None               None          None             None      None                             None       None       None                        None                        None                            None      None      None               None                 None           None                       None                  None  None   None                       None               None              None               None                 None              None                                              None                    None                                 None                   None                         None      None              None     None                         None   None            None                            None                          None  None                 None         None                   None            None    None            None             None
9       mutaxasis                     None        None                      None               None               None       mutaxassis oqchi'               None      None                          None                       None            None                 None                 None             None             None                    None               None     None       None                    None              None              None                      None                          None                        None              None       None  None               None          None             None      None                             None       None       None                        None                        None                            None      None      None               None                 None           None                       None                  None  None   None                       None               None              None               None                 None              None                                              None                    None                                 None                   None                         None      None              None     None                         None   None            None                            None                          None  None                 None         None                   None            None    None            None             None
10     mutaxassist                    None        None                      None               None               None    mutaxassis haydovchi               None      None                          None                       None            None                 None                 None             None             None                    None               None     None       None                    None              None              None                      None                          None                        None              None       None  None               None          None             None      None                             None       None       None                        None                        None                            None      None      None               None                 None           None                       None                  None  None   None                       None               None              None               None                 None              None                                              None                    None                                 None                   None                         None      None              None     None                         None   None            None                            None                          None  None                 None         None                   None            None    None            None             None
11  mutaxassis o'q                    None        None                      None               None               None  mutaxassis haydovchisi               None      None                          None                       None            None                 None                 None             None             None                    None               None     None       None                    None              None              None                      None                          None                        None              None       None  None               None          None             None      None                             None       None       None                        None                        None                            None      None      None               None                 None           None                       None                  None  None   None                       None               None              None               None                 None              None                                              None                    None                                 None                   None                         None      None              None     None                         None   None            None                            None                          None  None                 None         None                   None            None    None            None             None

In [13]:
sorted_posi_data = pd.DataFrame(np.nan, index=jqb_posi_dict_df.index, columns=jqb_posi_dict_df.columns)

jqb_posi_data_dict = defaultdict(list)
jqb_posi_data_dict["bo'lim boshlig'i"] = ["bo'lim boshligi",'bo‘lim boshlig‘i','туман жамоат хавфсизлиги хизмати бошлиғи','aloqa boshligi','туман жамоат тартибини сақлаш бўлими бошлиғи',
       	'туман жамоат хавфсизлиги хизмати бошлиғи ','бўлим бошлиғи',"aloqa boshlig'i","viloyat iib jxx jtsb boshlig'i",'iib boshqarma boshliği', 
		"boshqarma boshlig'i",'иив жтсх ппх бўлим бошлиғи','ткд жкх булим бошлиги','jxx jtsb boshlig"i', 'jtsb boshlig‘i', 'tuman jtsb boshlig`i',
       	'jtsb boshlig`i','yashnobod tumani iio fmb jtsb boshlig’i','olmazor  tumani iio fmb jtsb boshlig’i  ','m.ulug`bek  tumani iio fmb jtsb boshlig’i  ',
		'bektemir tumani iio fmb jtsb boshlig’i  ','sergeli tumani iio fmb jtsb boshlig’i  ','yunusobod tumani iio fmb jtsb boshlig’i  ','хизмат бошлиғи',
		'mirzo ulug`bek tumani iio fmb boshlig`i','m.ulug`bek  tumani iio fmb jtsb boshlig’i  ','виибб жхх жтсб бошлиғи','tuman jamoat xavfsizligi xizmati boshlig`i',
		'туман жамоат тартибини сақлаш бошқармаси бошлиғи',"viloyat iib jxx jtsb boshlig'i", "iib jxx jtsb boshlig'i",'jxx jtsb boshlig"i',"bo'lim boshlqi", "bo'lim boshligi", 
		"bo'lim boshlig'i", 'bo‘lim boshlig‘i','batalyon shtab boshligʻi','surushtiruv boshlig‘i',"kontrrazvedka boʻlim boshligʻi","yakkasaroy tumani jtsb boshlig`i",
		'жамоат тартибини сақлаш бошқармаси ташкилий бўлим бошлиғи']
jqb_posi_data_dict["bo'linma boshlig'i"] = ['бўлинма бошлиғи',"bo'linma boshlig'i",'boʼlinma boshligʼi','жамоат тартибини сақлаш бошқармаси назорат-лицензиялаш фаолияти бўлинмаси бошлиғи']
jqb_posi_data_dict['bosh inspektor'] = ['davlatobod tumani tuquvchiguruh komandir o’rinbosari xtm bosh inspektori','davlatobod tumani orzu htm bosh inspektori','davlatobod tumani umid htm bosh inspektori',
       	'davlatobod tumani yuksalish htm bosh inspektori','yangi namangan tumani go`zal htm bosh inspektori','yangi namangan tumani ishonch xtm bosh inspektori',
       	'yangi namangan tumani bunyodkor htm bosh inspektori','yangi namangan tumani beruniy htm bosh inspektori','namangan shaxar lola xtm bosh inspektori',
       	'namangan shahar obihayot htm bosh inspektori', 'бош инспектори', 'бош инспектор', 'жхх бош инспектор','ахборот технологиялари бўйича бош инспкектори',
		'bosh inspektor','тошкент шахар иибб жтсб бош инспектори','жамоат тартибини сақлаш бошқармаси бош инспектори','davlatobod tumani tuquvchi xtm bosh inspektori']
jqb_posi_data_dict['katta inspektor'] = ['katta inspektori','jtsg katta inspektori',' inspektor','jtsb katta inspektori', 'katta inspektor', 'kadr inspektori','ppxb katta inspektori',
		'профилактика катта инспектори ', 'профилактика катта инспектори','катта инспектори','ppx bataloni shtab navbatchilik qismi katta inspеktor navbatchisi','pki',
		'старший инспектор','хттб ҳпг катта инспектори', 'ппхб кг катта инспектори','ппхб хтг катта инспектори','jtsb nq katta inspektor navbatchi ', 'катта инспектор',
		'ppx bataloni xizmatni tashkillashtirish guruhi katta inspеktori','kadrlar guruxi katta inspеktori','2-минтақа ппх катта инспектори','ppxb katta inspektori',
		'ppxb katta inspektori','katta inspektori','profilaktika katta ispektor','profilaktika  katta inspektori','profilaktika katta inspektori','profilaktika katta inspektori ',
		'profilaktika katta inspektor','жамоат тартибини сақлаш бошқармаси катта инспектори']
jqb_posi_data_dict['kichik inspektor'] = ['kichik inspektor']
jqb_posi_data_dict['inspektor'] = ['inspektori','nspektor','inspector','inspektori','ispektor','inspektor','inspektor','sinspektori','eko inspektor','inbspektor','inspektor','isnpektor',
		'inspektori','imspektor','inspektor.','inspektori','ppx inspektor','inispektor',' inspektori', 'ppx inaspektori', 'ppx ibspektori','profilaktika inspektor',
       	'ppxb inspektori', 'ppx inspektori', 'ppx insptktori','mppxo inspektori', 'inspektori', 'ppx onspektori','ppx inspektpri', 'ppx< inspektori', 'ppx inspetktori',
       	'ppx inspektrori ', 'inspektori ', 'ppx  inspektori ','mppx insoektori', ' ppx inspektori ', 'mppx inspektori ','ppx inpektro', 'ppx inspektrori', 'ppx inspektr',
       	' ppx inspektori', 'xob inpektori', 'ppx inspekt','ppx inispektori', 'ppx inspekrori', ' ppx inspektor','ppx inspek|tori', 'ppx insprktori', ' inspektori ',
		'ppx inspektor', 'ppx inpektor', 'ppx isnpektori','ppx insperktor', 'ppx inspektor ','sinspektori', 'ppx inspek', 'ppx inspektori ', 'ppx inspeltor',
       	'ppx inspektri', 'mppx inspektori', 'ppx  inspektori','p i inspektori', ' inspektor', 'ppx inspektro', 'ppxb inspektor','ppx iinspektori', 'ppx inpektori', 'mppxo inspektori ',
       	'ppx inspektort', 'ppx inspector','ппхб хтг инспектори', 'ппхб хтэг инспектори', 'ппх инспектори','жхд инспектори', 'ппх инсектори', 'ппх  инспектор',
       	'ппх  инспектори', 'ппх ипспектор', 'ппх инпектори ','ппх инспректор ', 'ппх инспектори ', 'ппх инспектор','инспектори','инспкетор', 'инспекитор', 'инспктор', 
		'мтб инспектор', 'инспекор','инспекиор', 'бош инспектор', 'инспектор ', '9инспектор','инпектор', 'инспетор', 'инсапектор', 'инспектор', 'ппх инспектор','инспектори',
		'patrul-post xizmati inspеktori', 'patrul post xizmati inspektori','davlatobot tumani ppx ispektori','davlatobod tumani  ppx inspektori','profilaktika inspector',' p.i',
		'davlatobod tumani iib jxx jtsb ppx inspektori','davlatobod tumani xtm inspektori','davlatobod tumani ppx inspektori ','davlatobot tumani iib ppx inspektori',
		'davlatobod tumani ppx inspektori','davlatobo tumani ppx inspektori','davlatobor tuman xtm inspektori','davlatobod tumani ppx ispektori','p.k.i',
		'1-otryad ppx inspektori', 'ppxb 2- otryad inspektori','ppxb isomtxt otryadi inspektori', '1-otryad inspektori ','ppx 1-otryad inspektori', 'ppxb 3-otryad inspektori',
		'ppxb 1-otryad inispektori', '2-otryad inspektori','ppxb 4-otryad inspektori', 'ppxb 1-otryad inspektori','ppx bataloni 1-otryad inspektori', 'ppxb 3-otryad  inspektori',
		'ppxb 2-otryad inspektori', 'ppxb 4- otryad inspektori safdor','ppxb 1-otryad inispektori ', 'ppxb 4- otryad inspektori','ppxb 3- otryad inspektori', 'ppxb 1-otryad inspektor',
		'3-otryad mppx inspektori ', '1-otryad ppx inspektori','2-otryad mppx inspektori ', '1-otryad ppx inspektori ','insepkor','profilaktika inspektor ','profilaktikainspektor','p.i',
		'1-otryad мppx inspektori ', '2-otryad mppx inspektori','2-otryad inspektori', '13-otryad mppx inspektori','2-otryad mppxo inspektori ', '1-otryad ppx inspektori  ',
		'2 otryad mppx inspektori', '1-otryad mppx inspektori     ','3-otryad мppx inspektori', '1-otryad inspektori ','3-otryad мppx inspektori ', '3-otryad mppx inspektori  ',
		'2 mintaqa ppx inspektori', '1-mintaqa ppx inspektori','3 mintaqa ppx inspektori', '2-mintaqa ppx inspektori','ppx ins', 'ppx ins ', 'ppx insp', 'ppx inspek', 'ppx inf',
		'yangi namangan tumani ppxb inspektori','yangi namangan tumani ppx inspektori  ','yangi namangan tumani ppx inspektori ','yangi namangan tumani ppx inspektori',
		'yangi namangan tumani ppxb inspektori ','yangi namangan tumani ishonch xtm bosh inspektori','profilaktika inspektori','profilaktika inspektori ',
		' yangi namangan tumani ppxb inspektor','yangi namangan tumani iib ppx inspetori','yangi namangan tumani iib jxx jtsb ppx inspektori','3-otryad mppx inspektori',
		'yangi namangan tumani iib ppx inspektori','yangi namangan tumani htm inspektori','yangi namangan tumani iib guzal mfy xtm ppx inspektori',
		'namangan viloyati ppxb tumanlararo otryadi inspektori','namangan viloyati iib ppxb maxsus otryadi inspektori','namangan viloyati ppxb maxsus otryad inspektori',
		'namangan viloyati ppxb tumalararo otryadi inspektori','namangan viloyati iib ppxb maxsus otryad inspektori','birinchi otryad inspektori', 'ikkinchi otryad inspektori',
		'ppxb 2-tumanlararo otryadi  inspektori','ppxb 3-tumanlararo otryadi inspektori','ppxb 4-tumanlararo otryadi inspektori','ppxb 3- tumanlararo otryad inspektori',
		'4-tumanlararo otryadi inspektori','ppxb 1-tumanlararo otryadi inspektori','ppxb 2-tumanlararo otryadi inspektori','ppxb 3-tumanlararo otryad inspektori',
		'ppxb 2-tumanlararo otryad inspektori','namangan viloyati iib jxx jtsb ppxb maxsus otryad inspektori','namangan viloyati iib ppxb maxsus otryadi inspektori',
		'namangan viloyati ppxb maxsus otryad inspektori','namangan viloyati iib jxx jtsb ppxb maxsus otryad inspektorii','namangan shaxar iib jxx jtsb ppx otryadi inspektori',
		'namangan viloyati iib ppxb maxsus otryad inspektori','profilaktika  inspektori ','ppxb  inspektori','ppxb-inspektori','сурхандарё вилоят ииб шмх саф бўлинмалари ппхо инспектори',
		'ppx isotoxto  inspektori','ppxb isomto’xt otryadi inspektori','ppxb isomtxt otryadi inspektori',"ppxb isomto'xt otryadi inspektori",'бўстонлиқ тииб 3-сон ииб ппхг инспектори',
		'2-tumanlararo inspektori', '1-tumanlararo inspektori','2-tumanlararo ppxg inspektori', 'tumanlar aro ppx inspektori','профилактика инспектори', 'профилактика инспектори ',
		'ismtoxto  inspektori', 'ppx isotoxto  inspektori',"isoto'xto inspektori", 'ismotxto ppx inspektori',' ismotxto  inspektori', ' ismtoxto inspektori',
		'ismotxto  inspektori', "isomto'xto inspektori",'1-отряд ппх инспектори ', '2-отряд мппхо инспектори','2-отряд мппхо инспектори  ', '2-отряд мппх инспектори ',
       	'2-отряд мппх инспектори', '2-отряд мппхо инспектори ','1-отряд мппх инспектори ','namangan shaxar iib jxx jtsb ppx otryadi inspektori',
		'yangi namangan tumani iib jxx jtsb ppx inspektori','namangan shaxar iib jxx jtsb ppx inspektori','namangan shaxar ppx inspektori','ppx tuman insp',
		'namangan shahar ppxb inspektori','namangan shahar ppx inspektori', 'namangan shaxar ppx inspektori','ппхб инспектор-навбатчиси ','1-туманлараро ppx inspektori',
		'inspektor safdor xodimi', 'inpektor xodim', 'inspektor xodimi','namangan shahar ppxb inspektori','namangan viloyati ppxb inspektori',
       	'namangan viloyati ppxb maxsus otryad inspektori','namanmgan viloyati ppxb inspektori','ikkinchi tumanlararo patrul-post xizmati guruhi inspektori',
       	'birinchi tumalararo patrul-post xizmati guruhi inspektori','tumanlararo patrul-post xizmati gurug‘i inspеktori','ппх исомтўхто инспектори',
		'namangan shaxar chorsu mfy xtm inspertori','qashqadaryo viloyati, iib ppxb inspektori',' inspektori', 'mppx inspektori','бустолик тииб 3 сон ииб ппхг инспектори',
		'inspektori ', 'ppxb inspektori', ' inspektor', 'mppx inspektori ','sinspektori', 'mppxo inspektori', 'xob inpektori', 'inspektori',
		'mtb inspektori', 'jtsg inspektori', ' inspektori ','jtsb inspektori','ikkinchi tumanlararo patrul-post xizmati guruhi inspektori','mppx inspektori tungi klub ',
       	'ikkinchi tumanlararo ppx guruhi inspektori',' ppx inspektori', '1-отряд ppx inspektori','davlatobod tumani iib jxx jtsb ppx inspektori',
       	'davlatobod tumani  iib jxx jtsb ppx otryad inspektori','yangi namangan tumani htm inspektori','namangan shahar iib ppx 4-sonli ozod mfy htm inspektori',
       	'yanginamangan tumani iib ppx 3-sonli gozal mfy htm inspektori','yangi namangan tumani iib jtsb ppx 4-sonli xtm inspektori','инспектор ходими',
		'yangi namangan tumani iib guzal mfy xtm ppx inspektori','мтб инспектори', 'мтб инспектор', 'инспектори','p/i', 'pi','транспорт жтсб инспектори','п.и',
		'shayxontohur tumani iio fmb 5-sonli iib hpb profilaktika inspektori',' inspektori', ' inspektor', 'sinspektori','prof ins','eko inspektor'
		'сурхандарё вилоят ииб шмх саф бўлинмалари ппхо инспектори','ppxb 3-tumanlararo otryadi inspektori','inspektor ', 'inspektor ходим',
		'maxsus otryad ppx inspektori', '1-otryad ppx inspektori','1-otryad ppx inspektori ', '2-otryad mppx inspektori','2 otryad mppx inspektori', '3-otryad мppx inspektori',
		"ta'minlash guruhi inspektori",'namangan viloyati ppxb tumanlararo','namangan shahar gishtkuprik 5-son mfy ppx inspektori','uchqurgon tumani  ppx inspektori  ',
		'yangi namangan tumani iib ppx inspektori','yangi namangan tumani iib guzal mfy xtm ppx inspektori','yangi namangan tumani biruniy 2-sonli mfy ppx inspektori ',
		'1-минтақа ппх инспектори ','1-минтака ппх инспектори','1-минтақа ппх инспентори','1-минтақа ппх инспектори','1-минтақа ппх инспектри ','samarqand viloyati txtb jtsg inspektori',
		'1-mintaqa ppx inspektori','2-минтақа ппх инспектори','2 mintaqa ppx inspektori','2-mintaqa ppx inspektori','profilaktika  inspektori',"farg'ona viloyati txtb jtsg inspektori",
		'3-минтақа ппх инсипектори','3-минтақа ппх инспектори','3-минтқа ппх инспектори','3-минтақа ппх иснпектори','3минтақа ппх инспектори',
		'3-минтақа ппх инспектои','3 mintaqa ppx inspektori','4-минтақа ппх инспектори ','4-минтақа ппх инспектори',' 4-минтақа ппх инспектори',
      	'жамоат тартибини сақлаш бошқармаси муҳим топшириқлар бўйича инспектори','qashqadaryo viloyati txtb jtsg inspektori','1-otryad inspektori',
      	'navoiy viloyati txtb jtsg inspektori','andijon viloyati txtb jtsg inspektori','1-tumanlararo ppxg inspektori','sirdaryo viloyati txtb jtsg inspektori']
jqb_posi_data_dict['guruh komandiri'] = ['3-guruh komandiri', 'guruh komandiri (532)', '1-gurux komandiri','gurux komandiri ', 'guruh komandiri ', '3-gurux komandiri',
       	'guruh komandir', 'guruh  kamandiri','4-guruh kamandiri','guruh komandiri', 'guruh kamandiri', 'ppx gurux komandiri','1-guruh komandiri', 'ppx guruh komandiri', 'guruh koma',
       	'2-gurux komandiri', 'gurux kamandiri','guruh  komandiri','2- gurux komandiri','gurux komandiri','2-гурух камандири','гуруҳ командири', 'гурух командири',
       	'гурух камандири', 'гурух командири ',' namangan viloyati iib jxx jtsb ppxb maxsus otryad guruh komandiri','namangan viloyati iib jxx jtsb ppxb maxsus otryad gurux komondiri',
		'ppx otuqto gurux kom','ppxb otliq guruhi komandiri','ppx guruh komandiri','текшириш, кузатиш ва тезкор ҳаракатланиш гуруҳи командири','otr/gur/ kom',
		'ўраб олиш ва кўздан кечиришни ташкиллаштириш гуруҳи командири','ппхб тппхо гурух командири','ppx bataloni isomtxt otryadi gurux  komandiri','1-минтақа ппх отряд командири ',
		'ppxb isomto’xt otryadi guruh komandiri','ppxb isomto’xt otryadi gurux komandiri','сув билан зарба бериш гуруҳи командири','1-mintaqa ppxo 1 gurux komandiri',
		'1-mintaqa ppxo 2 guruh komandiri','2 mintaqa ppxo 2 gurux komandiori','3-минтақа ппх 2-гурух командири','3-минтақа ппх 3-гуруҳ командири','1-ммм ппхо 2-гурух командири',
		'4-минтақа ппх гурух командири','3-минтақа ппх 1-гуруҳ командири','3-минтақа ппх 4-гурух командири','2-минтақа ппх  гурух командири', '2-минтақа ппх гурух командири',
		'ismotxto guruh komandiri','4-минтақа ппх 3-гурух командири','3-минтақа ппх 5-гурух командири','4-минтақа ппх 1-гурух командири','4-минтақа ппх 5-гурух командири',
		'2-минтақа ппх гуруҳ командири','ppxb 2-otryad gurux komandiri','mppx 2-otryad gurux komandiri','guruh koma','ppx gurux komandiri','ppx guruh koman','3-thm guruhi komandiri',
		'ppx bataloni isomtxt otryadi suv bilan zarba bеrish guruhi komandiri','ppx bataloni ta’minlash guruhi starshinasi','1-отряд гурух командири ','patrullik guruhi komandiri',
		'1-ммм ппхо 4-гурух командири ','1-ммм ппхо 1-гурух командири','1-ммм ппхо 3-гурух командири ','1-ммм ппхо 5-гурух командири ','gurux kom ','3-thmg komandiri',
    	'namangan viloyati txtb ppxb guruh komandiri']
jqb_posi_data_dict['otryad komandiri'] = ['2-otryad komandiri', 'ppxb 1-otryad komandiri','otryad komandiri ', 'otiryad komandiri',
		'1-otryad gurux komandiri', 'ppxb 2-otryad komandiri','otryad kamandiri', '1-otryad komandiri', 'otryd kamandiri','ppxb 4- otryad komandiri', '2-otryad komandiri ',
		'ppxb 3- otryad komandiri', 'ismotxt otryad komandiri','ppx otryad komandiri', 'otyad komandiri', 'otriat komandiri','otryad komandiri','отряд командири',
		'3-ппх отряд командири', 'отряд командири ў/и','ppxb 1-tumanlararo otryadi komandiri','ppxb 3-tumanlararo otryadi komandiri','ppxb 4-tumanlararo otryadi komandiri',
		'ppxb 3-tumanlararo otryad komandiri','ppx bataloni birinchi otryadi komandiri','ppx bataloni komandrining o‘rinbosari isomto‘xto komandiri',
		'namangan viloyati iib jxx jtsb ppxb tumanlararo otryad komandiri','ppxb ismotxt otryadi komandiri','2-минтақа ппх отряд командири','komandir otryad',
		'ппхб командирининг ўринбосари-исомтўхто командири','ппхб командири ўринбосари – исомтўхт отряди командири','davlatobod tumani iib jxx jtsb ppx otryad komandiri',
		'namangan shaxar ppx otryad komandiri','3 mintaxa ppx otryad komandiri','2 mintaqa ppxo komandiri','1 mintaxa ppx otryad komandiri',
       	'ppx otryad komandiri','4-ммм ппхо камандири','ppxb 4-tumanlararo otryadi komandiri','tumanlararo otryad komandiri', 'tumanlararo otryad komandiri ',
		'ppxb 2-tumanlararo otryad komandiri','tumanlararo otryadi komandiri','ппхб тппхо командири','2-tumanlaro otryadi komandiri']
jqb_posi_data_dict["bo'linma kamandiri"] = ['seksiya komandir', 'seksiya komandiri','bo’linma komandiri', 'bo‘linma komandiri', 'bolinma komandiri',"bo'linma komandiri", 
		"ppx bo'linma komandiri","bo'linma komandiri ", "bo'linma kamandiri", 'bo`linma komandiri','bulinma komandiri','бўлинма командири', 'бўлинма камандири', 'бўлинма камандири ',
		"ppx 2-otryad bo'linma komandiri",'ppxb 2-tumanlararo otryadi bo’linma komandiri',"ppxb 2-tumanlararo otryadi bo'linma komandiri","ppx 2-otryad bo'linma komadiri",
		"ppxb 1-otryad bo'linma komandiri",'ppxb 3-tumanlararo otryadi bo’linma komandiri','ppxb 4-otryadi bo’linma komandiri','mutaxassis-seksiya komandiri',
		"2-otryad bo'linma kamandiri",'ppxb 2-otryad  bo‘linma komandiri ','ppxb 4- otryad bo’linma komandiri','mppx 3-otryad bo‘linma komandiri',"birinchi otryad bo'linma komandiri",
		'ppxb 2-otryad bo’linma komandiri','ppxb 1-tumanlararo otryadi bo’linma komandiri',"ppx 1-otryad bo'linma komandiri",'mutaxassis seksiya komandiri',
		'ppxb 4-tumanlararo otryadi bo’linma komandiri','ppxb 1-otryad bo’linma komandiri','ppxb 3- otryad bo’linma komandiri','davlatobod tumani ppx bulimma komandiri',
		'davlatobod tumani ppx bulinma komandiri','ppx bataloni birinchi otryadi bo‘linma komandiri','safdor ppx bataloni birinchi otryadi bulinma komandiri',"ppx bo'linma komondri",
		'namangan shaxar iib jxx ppx otryad bulinma komandiri','komandir seksiya','ppxb 3-tumanlararo otryadi bo’linma komandiri ','yangi namangan tumani ppx bulinma komandiri']
jqb_posi_data_dict['batalyon komandir'] = ['батальон командири', 'батальон командири ','batalyon kamandirining', 'batalyon komandiri']
jqb_posi_data_dict['komandir'] = ['brigada komandiri','mttv komandiri','komandir']
jqb_posi_data_dict['katta tezkor vakil'] = ['катта тезкор вакил','katta tezkor vakil']
jqb_posi_data_dict['tezkor vakil'] = ['jqb','ўмиб','умиб тезкор вакил','tezkor vakil']
jqb_posi_data_dict['kichik tezkor vakil'] = ['kichik tezkor vakil']
jqb_posi_data_dict['bosh mutaxassis'] = ['bosh mutaxassis','катта мутахассис']
jqb_posi_data_dict['yetakchi mutaxassis'] = ['yekakchi mutaxassisi','етакчи мутахассиз', 'етакчи мутахассис','жкб ттиг этакч мутахссиси ']
jqb_posi_data_dict['mutaxassis'] = ['mutahassis ','mutahassis','mutahasis', 'mutaxassis', 'mutaxassisi','mutaxasis ', 'mutaxassis  ', 'mutaxasis', 'mutaxasiss','mutaxassis ', 'mutahassis',
		'namangan viloyati iib jxx jtsb maxsus otryad mutaxasis','namangan viloyati iib jxx jtsb ppxb maxsus otryad mutaxasisi','mutaxassis hisob raqam','mutaxasist',
		'мутахассис','ppxb isomto’xt otryadi mutaxassisi','текшириш, кузатиш ва тезкор ҳаракатланиш гуруҳи мутахассиси','ппх исомтўхто   мутахассис','mutaxssis','mutaxassisi ',
       	'текшириш, кузатиш ва тезкор ҳаракатланишгуруҳи мутахассиси','ўраб олиш ва кўздан кечиришни ташкиллаштириш гуруҳи мутахассиси','otryad mutahasisi','mutaxassisi  ',
		'ppx bataloni isomtxt otryadi mutaxasis xodimi','ppx bataloni isomtxt otryad mutaxasis xodimi','guruh mutaxassisi','mutaxassis ags hisobi',"mutaxasis yo'naltiruvchi",
		'бош мутахассиз','mutaxassis yo‘naltiruvchi','mutaxassis-yunaltiruvchi','mutaxassis hisob','mutaxassis raqam xisobchi','mutaxasiss kavaleryachi ','mutaxsis',
		'mutaxasiss kavaleryachi','mutaxassis kovaleriyachi',"isomto'xto mutaxasisi", 'isomtuht mutahasisi','gurux mutaxassisi','mutaxassist']
jqb_posi_data_dict['xaydovchi'] = ['хайдовчи', 'хайдwовчи','xaydovchi', 'haydovchi ', 'haydovchisi', 'haydovchi','хайдовчи ходим ', 'хайдовчи ходими', 'хайдовчи  ходим',
       	'хайдовчи ходим', 'ҳайдовчи ходим','xaydovchi hodim', 'xaydovchi hodimi ', 'xaydovchi xodim','haydovchi hodim ', 'xaydovchi hodimi', 'haydovchi hodimi',
		'haydovchi xodimi', 'haydovchi xodim', 'haydovchi hodim','xaydovchi  hodimi','ppx bataloni birinchi otryadi haydovchi-xodimi','mutaxassis motosikl ',
		'tumanlararo patrul-post xizmati otryadi birinchi tumanlararo patrul-post xizmati guruhi haydovchisi','mutaxassis-haydovchi', 'mutaxasis haydovchi','mutaxassis haydovchi',
		'mutahasis haydovchi', 'mutaxasiss haydovchi','mutaxassis xaydovchi','сафдор хайдовчм', 'сафдор хайдовчи','сув билан зарба бериш гуруҳи ҳайдовчиси',
		' сув билан зарба бериш гуруҳи ҳайдовчиси','amangan viloyati iib jxx jtsb ppxb maxsus otryad suv bilan zarba berish xaydovchisi','mutaxassis haydovchi (motosiklchi))',
		'4-минтақа ппх хайдовчи','ppx bataloni isomtxto haydovchi-xodimi','ppx bataloni ta’minlash guruhi haydovchi-xodimi','ppxb 4-tumanlararo otryadi xaydovchi xodimi',
       	'ppxb 2-otryad xaydovchi xodimi','ppxb 2-tumanlararo otryadi xaydovchi xodimi','ппхб ҳайдовчиси','mutaxassis haydovchisi',
		'namangan viloyati iib jxx jtsb ppxb maxsus otryad suv bilan zarba berish xaydovchisi']
jqb_posi_data_dict["guruh komandiri o'rinbosari"] = [' namangan viloyati iib jxx jtsb ppxb maxsus otryad inspektoriguruh komandiri urinbosari ',"guruh komandiri o'rinbosari ",
		'guruh komandiri oʻrinbosari', 'guruh kamandir urin bosari',"guruh komandiri o'rinbosari",'guruh komandir o’rinbosari',"guruh komandiri or'inbosari",'gurux o‘rinbosari',
		'guruh komandiri o‘rinbosari','текшириш, кузатиш ва тезкор ҳаракатланиш гуруҳ командирининг ўринбосари','ppx bataloni isomtxt otryadi gurux komandiri o‘rinbosari',
		'ўраб олиш ва кўздан кечиришни ташкиллаштириш гуруҳи командир ўринбосари',"ppxb isomto’xt otryadi guruh komandiri o'rinbosari",'гурух командири ўринбосари']
jqb_posi_data_dict["komandir o'rinbosari"] = ['батальон командирини хизмат бўйича ўринбосари','4-отряд командирининг хизмат бўйича  ўринбосари ','komandiri o‘rinbosari',
		'батальон командирининг хизмат бўйича ўринбосари','1-мппхо командири хизмат бўйича ўринбосари','ппхб командирининг хизмат бўйича ўринбосари',
		'отряд командирининг хизмат бўйича ўринбосари','батальон командирининг хизмат буйича уринбосари ',"komandir o'rinbosari",'batalyon komandirining o‘rinbosari',
		'otryad komandiri orinbosari','komandir o`rinbosari',"otryad komandiri o'rinbosari","ppxg komandir o'rinbosari","otryad komandir o'rinbosari",
		'guruh komandiri o’rinbosari','otryad komandiri o‘rinbosari','otryad komandiri o`rinbosari','ppx bataloni  isomtxt otryadi komandiri o‘rinbosari',
		'ppx bataloni birinchi otryadi komandiri o‘rinbosari',"ppxb ismotxt otryad komandiri o'rinbosari",'batalyon komandirining orinbosari','батальон командири ўринбосари',
		"batalyon komandirining o'rinbosari",'batalon komandirining o‘rinbosari',"ppxb 1-otryad komandiri o'rinbosari",'ппхб командирининг ўринбосари-исомтўхто командири',
		"ppxb 4- otryad komandirining o'rinbosari","otryad komandirining o'rinbosari","1-otryad komandirining o'rinbosari",'batalyon komandiri orinbosari',
		'ppxb otryad komandiri orinbosari',"otryad komandiriningo'rinbosari", "ppxb komandiri o'runbosari","ppxb komandirining o'rinbosari",'отряд командири ўринбосари',
		'batalyon komandirining orinbosari','batalyon komandirining o‘rinbosari',"batalyon komandirining o'rinbosari",'batalon komandirining o‘rinbosari', 
		'batalyon komandiri o`rinbosari','ppx otr kom urin','ппхб командири ўринбосари – исомтўхт отряди командири',' командири ўринбосари','отряд командир ўринбосари',
		"batalon komandirir o'rinbosari","batalon komandiri o'rinbosari",'otryad komandiri o`rinbosari',"tumanlararo otryad komandiri o'rinbosari",
		'ppxb 2-otryad komandiri o’rinbosari','1 otryad komandiri orinbosari',"ismotxt otryad komandiri o'rinbosari","ppx otryad  komandiri o'rinbosari",
		" 4-otryad komandiri o'rinbosari","ppxb 1-otryad komandiri o'rinbosari","2-otryad komandir o'rinbosari","ppxb 4- otryad komandirining o'rinbosari",
		"iotxt otryad komandiri o'rinbosari",'otryad komandiri o`rinbosari','ppxb 3- otryad komandiri o’rinbosari',"farg'ona viloyati iib imh ppx otryadi xizmat buyicha o'rinbosari",
		'batalon komandirining xizmat bo‘yicha o‘rinbosari',"batalion komandirining xizmat bo'yicha o'rinbosari","batalion kom o'rin bosar","otr kom o'rinbosari",
		'komandir otryad o`rinbosari','1 mintaxa ppx otryad kom orinbosari','podpolkovnik ppx bataloni komandiri o‘rinbosari','patrullik guruhi komandiri oʼrinbosari-haydovchi',
		'ppx bataloni komandrining o‘rinbosari isomto‘xto komandiri','komandir oʻrinbosari ','komandiri o‘rinbosari','батальон командири ўринбосари ','батальон ткомандири ўринбосари',
		"баталони командири o'rinbosari","farg'ona viloyati iib jxx jtsb ppx komandiri mmib o'rinbosari",]
jqb_posi_data_dict['safdor'] = ['сафдор-ходим', 'сафдор ходими', 'садор ходим', 'сафдор ходим ','сафдор ходим', 'сафдор-ходим  ', 'сафдор-ходим ','safdor','сафдор', 'сафдор ',
		'ppx xodimi', 'ppx xodimi ', 'ppx xodmi', ' ppx xodimi','safdor hodim', 'safdor hodim ', 'safdor xodim', 'safdor hodimi','safdor xodimi ', 'safdor-xodim', 'safdor xodimi',
		'ppxb 2-otryad safdor xodimi', 'ppxb 1-otryad xaydovchi xodimi','ppxb 3- otryad safdor xodimi', 'ppxb 2-otryad safdor xodimi ','ppx bataloni isomtxt otryadi ',
		'ppxb 2-otryad xaydovchi xodimi', 'ppxb 1-otryad safdor xodimi','ппхб тппхо сафдор ходим', 'ппхб тппхо хайдовчи  ходим','ппхб тппхо хайдовчи ходим',
		'tumanlararo patrul-post xizmati otryadi birinchi tumanlararo patrul-post xizmati guruhi safdor xodimi','ppx bataloni birinchi otryadi safdor-xodimi',
		'ppx bataloni 1-otryad otryadi safdor-xodimi','ppx bataloni birinchi otryadi safdor xodimi','ppx bataloni 1-otryad otryadi safdor xodimi',
		'ppx bataloni isomtxt otryadi safdor xodimi','сафдор хайдовчм', 'сафдор хайдовчи','катта тезкор вакил','ппхб коменданти','namangan viloyati txtb ppxb',
		'katta serjant',' текшириш, кузатиш ва тезкор ҳаракатланиш гуруҳи ходими','екшириш, кузатиш ва тезкор ҳаракатланиш гуруҳи ходими','tezkor vakil',
       	'текшириш, кузатиш ва тезкор ҳаракатланиш гуруҳи ходими','isomtuht safdor hodimi', 'isomtuht  safdor xodimi','isomtuht safdor xodimi',
		' ўраб олиш ва кўздан кечиришни ташкиллаштириш гуруҳи сафдор ходими','ўраб олиш ва кўздан кечиришни ташкиллаштириш гуруҳи',"pp{b ta'minot gurihi",
		' ўраб олиш ва кўздан кечиришни ташкиллаштириш гуруҳи ','ўраб олиш ва кўздан кечиришни ташкиллаштириш гуруҳи сафдор ходми','namangan vloyati txtb ppxb',
		' ўраб олиш ва кўздан кечиришни ташкиллаштириш гуруҳи сафдор','ўраб олиш ва кўздан кечиришни ташкиллаштириш гуруҳи ','patrul','txtb ppxb ',
		'ppx bataloni shtab navbatchilik qismi navbatchi-yordamchisi','ppxb navbatchilik qismi', 'ppxb navbatchisi','ппхб навбатчи ёрдамчиси',
		'ppx bataloni isomtxt otryadi safdor xodimi','ppx bataloni isomtxt otryad muxandis xodimi','tezkor navbatchi','isomtuxt otryadi','isomtuhta otryadi','isomtuhta',
       	'ppx bataloni isomtxt otryadi ','ppx bataloni isomtxt otryadi safdor xodimi','serjant','feldsher','ppxb otliq guruhi safdor xodimi',
		'bosh prokuraturasi huquqni muhofaza qilish akademiyasi','jxx atb','2-отряд мппхо','otliq xodim',"mmio'",'умиб тезкор вакил','trx jqb ', 'tqx jqb',
		'ppx brigadasi ', 'ppx brigadasi','namangan viloyati ppxb otliq guruxi','namangan viloyati ppxb otliq guruhi','ppxb', 'ppx','namangan viloyati iib jxx jtsb ppxb  ',
		'жтсг','3-guruh savdor hodimi','сержант','kichik serjant','ppx bataloni isomtxt otryadi safdor-xodimi','ppxb 3- otryad safdor xodimi',
       	'ppxb 1- otryad inspektori safdor xodimi','ppxb 1-otryad safdor xodimi', 'ppxb 4- otryad inspektori safdor','tumanlararo safdor xodim',
		'2-отряд сафдор-ходим ', '3-отряд софдор-ходими  ','3-отряд сафдор-ходим ','namangan viloyati ppxb navbatchisi','safdor hodimi','safdor hodim','ppxb safdor hodimi']
jqb_posi_data_dict["moddiy tehnika ta'minoti bo'yicha o'rinbosari"] = ["ppx komandirining mtt bo'yicha o'rinbosari",'ppxb komandiri  mtt orinbosari',
		'ппхб командирининг мттб ўринбосари','ppx bataloni komandiri mtt bo‘yicha urinbosari','ппхб командирининг моддий техника таъминоти бўйича ўринбосари']
jqb_posi_data_dict["tarbiyaviy ishlar bo'yicha o'rinbosari"] = ['отряд командирининг тарбиявий ишлар бўйича ўринбосари',"1-mmm ппхo tib o'rinbosari ",
		"farg'ona viloyati iib imh ppx otryadi komandirining tib o'rinbosari ",'batalon komandirining tb o‘rinbosari']
jqb_posi_data_dict["ma'naviy va ma'rifiy ishlar bo'yicha o'rinbosari"] = ['отряд командирининг маънавий ва маърифий ишлар бўйича ўринбосари','ppxb mmib orinbosari',
		'ппхб  командирининг маънавий-маърифий ишлар бўйича ўринбосари','ппхб командирининг ммиб ўринбосари','4-минтақа ппхо командирининг ммиб ўринбосари',
		'1-минтақа ппх отряд командарининг ммиб ўринбосари','ppx bataloni komandiri mmi bo‘yicha urinbosari',
		"batalion komandirining ma'naviy va ma'rifiy ishlar bo'yicha o'rinbosari"]
jqb_posi_data_dict["boshliq o'rinbosari"] = ['jtsb boshlig‘i o‘rinbosari ','jtsb boshlig`ining o`rinbosari',"viloyat iib jxx jtsb boshlig'i o'rinbosari",
		"iib jxx jtsb boshlig'ining o'rinbosari",'бошқарма бошлиғи ўринбосари ','бошқарма бошлиғи ўринбосари  ',"boshqarma boshlig'i o'rinbosari",
		"boshqarma boshligi' o'rinbosari",'жамоат тартибини сақлаш бошқармаси бошлиғи ўринбосарлари',"boshliq o'rinbosari","xorazm viloyati txtb boshlig'i o'rinbosari",
		'тошкент шаҳар ички ишлар бош бошқармаси бошлиғининг жамоат тартибини сақлаш бўйича ўринбосари']
jqb_posi_data_dict["o'rinbosar"] = ["markaz o'rinbosari","oltiariq t 1-o'rinbosari", "beshariq t 1-o'rinbosar",'ppxb xizmat buyicha orinbosari',"quva t 1-o'rinbosar",
		"buvayda t 1-o'rinbosari","quvasoy sh 1-o'rinbosari", "bag'dod t 1-o'rinbosar","uchko'prik t 1-o'rinbosari","dang'ara t 1-o'rinbosari",
		"farg'ona t 1-o'rinbosari","farg'ona t 1-o'rinbosari", "farg'ona sh 1-o'rinbosari","marg'ilon sh 1-o'rinbosar","qo'qon sh 1-o'rinbosari", "farg'ona sh 1-o'rinbosari",
       	"quvasoy sh 1-o'rinbosari",'иив ўринбосари',"qo'shtepa t 1-o'rinbosar","iib jxx jtsb o'rinbosar","iib jxx jtsb 1-o'rinbosari","yozyovon t 1-o'rinbosar",
		"farg'ona t 1-o'rinbosari", "quva t 1-o'rinbosar","furqat t 1-o'rinbosar","so'x t 1-o'rinbosari", "rishton t 1-o'rinbosari","o'zbekiston t 1-o'rinbosari",
		"batalion komandirining ma'naviy va ma'rifiy ishlar bo'yicha o'rinbosari  "]
jqb_posi_data_dict['yordamchi'] = ['gurux komandiri yordamchisi', 'guruh komandiri yordamchisi',"ta’minot bo‘yicha yordamchi",'gurh kamamdiri yordamchisi','otyad kom yordam',
		'otryad komandirining mtbyo','ok mtbyo, mty','kmtbyomt']
jqb_posi_data_dict['muxandis'] = ['ppxb isomto’xt otryadi muxandisi','ismoxto muxandisi', "isomto'xto mutaxasisi", 'ismtoxto muxandisi','ppxb isomto’xt otryadi muxandisi',
       	' текшириш, кузатиш ва тезкор ҳаракатланиш гуруҳи муҳандиси','ppxb isomto’xt otryadi muxandisi','muhandis','ppx bataloni isomtxt otryad muxandis xodimi',
       	'ppx bataloni isomtxt otryadi muxandis xodimi','ppx  katta muxandisi','aloqa guruhi katta muhandisi','ppx,atalioni atg katta muxandisi','atg muhandisi','ппхб катта мухандиси',
		' ппхб катта мухандиси']
jqb_posi_data_dict['operator'] = ['ppxb isomto’xt otryadi operatori','сув билан зарба бериш гуруҳи оператори',' сув билан зарба бериш гуруҳи оператори ',
		'operator ','ppx operator','operator','оператор','mutaxassis-operator','mutaxassis opirotor','suv bilan zarba berish operatori']
jqb_posi_data_dict['aloqachi'] = ['mutaxassis aloqachi','aloqa guruhi katta muhandisi','aloqa','radiotelefonchi','axborot tehnalogiyalari guruhi ','aloqachi',
		'mutaxassis radiotelcfonist']
jqb_posi_data_dict["o'qchi"] = ['mutaxassis o‘qchi',"mutahassis o'qchi","mutaxassis o'qchi",'mutaxassis  o`qchi','mutaxassis-mergan','mutaxassis mergan','mutahassis mergan',
		"mutaxassis oqchi'",'uqchi',"mutaxassis o'q",'mutaxassis o’qchi','mutaxassis o‘qchisi','mutaxassis mo‘ljalga oluvchisi']
jqb_posi_data_dict['pulemyotchi'] = ['pulemyotchi','mutaxassis pulemotchi','mutaxassis pulemyotchi','mutaxassis pulomyotchi']
jqb_posi_data_dict['psixolog'] = ['psixologik', 'psixolog','inspektor psixolog','katta inspektor-psixolog','inspektor psixolok']
jqb_posi_data_dict['ofitser'] = ['katta ofitseri', 'katta ofitcer', 'katta ofitser','ofitser','guruh ofitseri']
jqb_posi_data_dict['kinolog'] = ['kinolog','mutaxasis kinolog', 'mutaxssis kinolog', 'mutaxassis kinolog','mutaxassis kinoligi', 'mutaxassis kinolik','mutaxassis-kinolog',
		'mutaxassis kinologi','mutaxassis kinologi']
jqb_posi_data_dict['portlatuvchi'] = ['portlatuvchi','mutaxasis sapyor;','mutaxassis portlatuvchi','mutaxassis portlatuvchisi']
jqb_posi_data_dict['dev'] = ['dev',"prod test",'developer']
jqb_posi_data_dict['admin'] = ['admin','viloyat admin','tuman admin']
jqb_posi_data_dict['feldsher'] = ['feldsher','mutaxassis feldsher']
jqb_posi_data_dict['yurist'] = ['yurist']
# jqb_posi_data_dict['null'] = ['iiv','9999999999999999','test jxd','disigner','штқзулеўк','rank','oʻttaa xasis ages','kkkkl','32509893500073','32904966800012','94-058-98-00',
# 		'kj.jk.jk.','raqam','siktirganski','98162 harbiy qism','gdsg','  ok','super','uchtepa tumani','pd','phvpx ее']

In [14]:
# [next((print(k, ',', x) for k, v in jqb_posi_data_dict.items() if x in v), None) for x in jqb_df.position]
# print([next((k for k, v in jqb_posi_data_dict.items() if x.lower() in v), None) for x in jqb_df.position])
# [x for x in jqb_df.position]
jqb_df['std_position'] = [next((k for k, v in jqb_posi_data_dict.items() if x.lower() in v), None) for x in jqb_df.position]

/var/folders/ww/67t1k6ss6bqfd8tw6ntmpfgm0000gn/T/ipykernel_44201/2731910446.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  jqb_df['std_position'] = [next((k for k, v in jqb_posi_data_dict.items() if x.lower() in v), None) for x in jqb_df.position]

In [15]:
jqb_df.head()

        id                          full_name                                                                               living_address passport_number         phone_number            pnfl        position           rank  working_address                               session  group  squad      region_name district_name activities    std_position
5      103        ORIFOVA LOBAR RISQIBOY QIZI                                        ПАРКЕНТ Ш., МОЗОРХОЖИ МФЙ, МИРСОДИКОВ КЎЧАСИ,  uy:116       AB4669865  +998 (94) 423-47-74  41602996770023            test          Mayor    mirzo ulugbek  7f18e701-15aa-47b7-8611-800e4ca0ccc1    NaN    NaN  Toshkent shahar           NaN        JQB            None
1855  9052       SHUKUROV OTABEK BAXODIROVICH  г. Ташкент, Яшнабадский район, ул. Ховос, пр. 2, Ахмад Яссавий МСГ, 1/17- Дом, 19- Квартира       AD7877777  +998 (21) 321-32-13  32503861080024      mutaxassis  Katta serjant  Toshkent shahar  21728b5f-2be7-47da-a28d-92b752162c90    NaN    NaN  Toshkent shahar           NaN        JQB      mutaxassis
1857  9054    ALIKULOV ALINAZAR ERGASH O‘G‘LI                                             ОХАНГАРОН Ш., НАВБАХОР Ш., ФУРҚАТ КЎЧАСИ,  uy:44       AA4303941  +998 (65) 131-33-33  33012930440029      mutaxassis  Katta serjant         namangan                                   NaN    NaN    NaN         Namangan           NaN        JQB      mutaxassis
1859  9056  NIYAZMATOV KATTABEK OTABEK O‘G‘LI                                                         МИНГЧИНОР КФЙ; ЖУЛАНГАР МФЙ,  uy:Р/С       AA3990963  +998 (77) 000-11-97  31104976390016  бош инспектори      Leytenant        Сирдарё в  37fd1105-1916-4bab-97a5-8da282359c20    NaN    NaN         Sirdaryo           NaN        JQB  bosh inspektor
2058  9311  XOJIYEV G‘AYBULLO XABIBULLAYEVICH                                             НАВКЕНТ ҚФЙ, НАВКЕНТ МФЙ, ШЎРҚУЛ КЎЧАСИ,  uy:Р/С       AC1814971  +998 (98) 121-07-79  31604835920016       kj.jk.jk.      Leytenant   dfbfdbfdbdfbdf                                   NaN    NaN    NaN          Andijon           NaN        JQB            None

In [16]:
# [next((print(k, ',', x) for k, v in jqb_posi_data_dict.items() if x in v), None) for x in mg_df.position]
# fltrd = [next((k for k, v in jqb_posi_data_dict.items() if str(x).lower() in v), None) for x in mg_df.position]
# unfltrd = [x for x in mg_df.position]

# [print(fltrd[x],',',f"\'{unfltrd[x]}\'") if fltrd[x] == None else None for x in range(len(fltrd))]

mg_df['std_position'] = [next((k for k, v in jqb_posi_data_dict.items() if str(x).lower() in v), None) for x in mg_df.position]

/var/folders/ww/67t1k6ss6bqfd8tw6ntmpfgm0000gn/T/ipykernel_44201/2701170563.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mg_df['std_position'] = [next((k for k, v in jqb_posi_data_dict.items() if str(x).lower() in v), None) for x in mg_df.position]

In [17]:
mg_df.head()

        id                            full_name                                                                           living_address passport_number         phone_number            pnfl         position     rank                         working_address                               session  group  squad       region_name district_name activities     std_position
10     404                                asfas                                                                                    fasfa             dsf  +998 (65) 464-65-46            dgda             gdsg   Safdor                                    gsdg  58ac300e-e5d6-4f27-b73b-1d20c65ae916    NaN    NaN  Toshkent viloyat           NaN         MG             None
13     506     KUPRIYANOV ROSTISLAV MIXAYLOVICH  г. Ташкент, Мирзо Улугбекский район, ул. Мирзо Улугбек, Буз МСГ, 71- Дом, 158- Квартира       AD2728519   +998 (99)777-45-70  31306920270782    katta ofitcer  Kapitan                                Toshkent  fe4dcff4-7319-40f4-a55c-29f3cb145e59    NaN    NaN               NaN           NaN         MG          ofitser
22     702                             MG Admin                                                                                       MG       AA5555555  +998 (33) 888-77-66  30507239784517            ADMIN    Admin                               O'R MG MD  d5db43a7-e13e-4460-aea1-db869b0a7354    NaN    NaN               NaN           NaN         MG            admin
1181  3104     KUPRIYANOV ROSTISLAV MIXAYLOVICH  г. Ташкент, Мирзо Улугбекский район, ул. Мирзо Улугбек, Буз МСГ, 71- Дом, 158- Квартира       AD2728519  +998 (77) 077-45-70  31306920270782    katta ofitser    Mayor                               O'R MG MD  a41a00ff-d904-4407-a868-2bdd64c964be    NaN    NaN   Toshkent shahar           NaN         MG          ofitser
1184  3202  NORQOBILOV SHERDOR ABDIRAYIM O‘G‘LI                                                     ДАРХОН МФЙ, ДОДҚУШ  ҚИШЛОҒИ,  uy:Р/С       AD3802291  +998 (90) 768-86-36  31308932530010  Guruh komandiri  Kapitan  MG FVVB 82318 harbiy qism (Qo‘qon sh.)  b6923a91-bda0-4599-b1e6-82b9a62c4521    NaN    NaN          Farg'ona           NaN         MG  guruh komandiri

In [18]:
# [next((print(k, ',', x) for k, v in jqb_posi_data_dict.items() if x in v), None) for x in pi_df.position]
# fltrd = [next((k for k, v in jqb_posi_data_dict.items() if str(x).lower() in v), None) for x in pi_df.position]
# unfltrd = [x for x in pi_df.position]

# [print(fltrd[x],',',f"\'{unfltrd[x]}\'") if fltrd[x] == None else None for x in range(len(fltrd))]

pi_df['std_position'] = [next((k for k, v in jqb_posi_data_dict.items() if str(x).lower() in v), None) for x in pi_df.position]

/var/folders/ww/67t1k6ss6bqfd8tw6ntmpfgm0000gn/T/ipykernel_44201/3114325013.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pi_df['std_position'] = [next((k for k, v in jqb_posi_data_dict.items() if str(x).lower() in v), None) for x in pi_df.position]

In [19]:
pi_df.head()

      id                        full_name                               living_address passport_number         phone_number            pnfl            position             rank    working_address                               session  group  squad      region_name       district_name activities        std_position
9    403                  Doniyor Usmonov                              Buxoro viloyati       AA8956233  +998 (99) 687-54-32  45876953210369         tuman admin            Mayor     buxoro viloyat  ba5a8a7d-9d1d-4ac7-9fdf-712e5e757be6    NaN    NaN           Buxoro       Buxoro tumani         PI               admin
15   553  JAXONOV ABRORJON XOLMIRZAYEVICH  ЧУВАЛАЧИ ҚФЙ, ИСТИҚБОЛ МФЙ, УЙИНГОХ,  uy:16       AB6575424  +998 (99) 465-65-84  30409841570012       XOB inpektori     Podpolkovnik  Toshkent viloyati  e1501ddf-0180-4496-8f88-d074936672a8    NaN    NaN  Toshkent shahar                 NaN         PI           inspektor
30  1934    BOBOKULOV FERUZ XOMIDJONOVICH                                    Samarqand       AA7469019        +998979201001  24246629921293           Inspektor  Katta leytenant                NaN                                   NaN    NaN    NaN        Samarqand  Pastdarg'om tumani         PI           inspektor
31  1937         USMANOV IN’OM XUSANOVICH                                    Samarqand       AA8606489        +998944798502  71601135426310  Boʼlinma boshligʼi            Mayor                NaN                                   NaN    NaN    NaN        Samarqand   Qo'shrabot tumani         PI  bo'linma boshlig'i
32  1938       NOSIROV MASHRAB FARUXOVICH                                    Samarqand       AA3886793        +998996255947  50082576459978     Katta inspektor     Podpolkovnik                NaN                                   NaN    NaN    NaN        Samarqand        Urgut tumani         PI     katta inspektor

In [20]:
# # [next((print(k, ',', x) for k, v in jqb_posi_data_dict.items() if x in v), None) for x in ppx_df.position]
# fltrd = [next((k for k, v in jqb_posi_data_dict.items() if str(x).lower() in v), None) for x in ppx_df.position]
# unfltrd = [x for x in ppx_df.position]

# [print(fltrd[x],',',f"\'{unfltrd[x]}\'") if fltrd[x] == None else None for x in range(len(fltrd))]

ppx_df['std_position'] = [next((k for k, v in jqb_posi_data_dict.items() if str(x).lower() in v), None) for x in ppx_df.position]

/var/folders/ww/67t1k6ss6bqfd8tw6ntmpfgm0000gn/T/ipykernel_44201/2553474206.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ppx_df['std_position'] = [next((k for k, v in jqb_posi_data_dict.items() if str(x).lower() in v), None) for x in ppx_df.position]

In [21]:
ppx_df.head()

    id                              full_name                            living_address passport_number         phone_number            pnfl       position       rank  working_address                               session  group  squad      region_name     district_name activities std_position
2   52                           Test Patrol                                        MVD       ac1231231        +998777777333  34563452351234           RANK     Safdor  custom yonalush  61b1a901-2305-47e6-8845-23a8b45b48be    NaN    NaN  Toshkent shahar               NaN        PPX         None
4  102                    test statistics for                                    testde       AV1234564  +998 (33) 333-33-33  12154674874123            DEV     Safdor      Turgan joyi                                   NaN    NaN    NaN           Jizzax            Jizzax        PPX          dev
6  104                                  Kerim                                 samarqand       AA1234567  +998 (65) 465-46-54    413657852255         tester     Safdor           manzil  4eeda370-6153-44f5-bd4d-9757529d48a4    NaN    NaN        Samarqand  Bulung'ur tumani        PPX         None
7  302  ANVARDINOV SHAMSIDDIN PANAYDIN O‘G‘LI  НАВРЎЗ МФЙ, ТЕМИРЙУЛЧИЛАР КЎЧАСИ,  uy:71       AD2072759  +998 (90) 374-40-07  32505986530013      Developer  Leytenant     Toshkent MVD  d4c30b44-fd86-4c4a-975e-d657068c88ae    NaN    NaN  Toshkent shahar               NaN        PPX          dev
8  402                        Rustam Qahhorov                          Andijon viloyati       AA1234589  +998 (99) 663-35-52  41254236589754  viloyat admin      Mayor   andijon shaxar  b9f56537-fdae-4041-9c56-06c7e4a8cfbf    NaN    NaN          Andijon               NaN        PPX        admin

In [22]:
final_df = pd.concat([pi_df, ppx_df, mg_df, jqb_df])
final_df.head()

      id                        full_name                               living_address passport_number         phone_number            pnfl            position             rank    working_address                               session  group  squad      region_name       district_name activities        std_position
9    403                  Doniyor Usmonov                              Buxoro viloyati       AA8956233  +998 (99) 687-54-32  45876953210369         tuman admin            Mayor     buxoro viloyat  ba5a8a7d-9d1d-4ac7-9fdf-712e5e757be6    NaN    NaN           Buxoro       Buxoro tumani         PI               admin
15   553  JAXONOV ABRORJON XOLMIRZAYEVICH  ЧУВАЛАЧИ ҚФЙ, ИСТИҚБОЛ МФЙ, УЙИНГОХ,  uy:16       AB6575424  +998 (99) 465-65-84  30409841570012       XOB inpektori     Podpolkovnik  Toshkent viloyati  e1501ddf-0180-4496-8f88-d074936672a8    NaN    NaN  Toshkent shahar                 NaN         PI           inspektor
30  1934    BOBOKULOV FERUZ XOMIDJONOVICH                                    Samarqand       AA7469019        +998979201001  24246629921293           Inspektor  Katta leytenant                NaN                                   NaN    NaN    NaN        Samarqand  Pastdarg'om tumani         PI           inspektor
31  1937         USMANOV IN’OM XUSANOVICH                                    Samarqand       AA8606489        +998944798502  71601135426310  Boʼlinma boshligʼi            Mayor                NaN                                   NaN    NaN    NaN        Samarqand   Qo'shrabot tumani         PI  bo'linma boshlig'i
32  1938       NOSIROV MASHRAB FARUXOVICH                                    Samarqand       AA3886793        +998996255947  50082576459978     Katta inspektor     Podpolkovnik                NaN                                   NaN    NaN    NaN        Samarqand        Urgut tumani         PI     katta inspektor

In [ ]:
# DO NOT DELETE

# mg_df.to_excel("MG_users.xlsx")
# ppx_df.to_excel("PPX_users.xlsx")
# jqb_df.to_excel("JQB_users.xlsx")
# pi_df.to_excel("PI_users.xlsx")
# final_df.to_excel("All_users.xlsx")

In [348]:
col29_cnts = main_df['position'].value_counts()
col29_cnts

Inspektor                                                                                                1271
inspektor                                                                                                 516
p.i                                                                                                       385
Mutaxassis                                                                                                368
PPX INSPEKTORI                                                                                            331
mutaxassis                                                                                                323
PPX inspektori                                                                                            278
Katta inspektor                                                                                           268
PPX Inspektori                                                                                            200
PPX INSPEKTOR                                                                                             167
4-минтақа ППХ инспектори                                                                                  148
2-минтақа ППХ инспектори                                                                                  121
3-минтақа ППХ инспектори                                                                                  121
ППХ инспектори                                                                                            112
mutaxasis                                                                                                 104
Guruh komandiri                                                                                           101
guruh komandiri                                                                                            96
inspektori                                                                                                 92
ppx inspektori                                                                                             90
инспектор                                                                                                  86
гуруҳ командири                                                                                            75
сафдор ходим                                                                                               69
1-минтақа ППХ инспектори                                                                                   63
Profilaktika inspektori                                                                                    63
хайдовчи                                                                                                   46
Safdor                                                                                                     43
inspektor psixolog                                                                                         40
Сафдор ходим                                                                                               40
Otryad komandiri                                                                                           39
PPX xodimi                                                                                                 38
mutaxassisi                                                                                                37
PPX INSPEKTORI                                                                                             37
profilaktika inspektori                                                                                    36
profilaktika Inspektor                                                                                     33
Patrul-post xizmati inspеktori                                                                             33
1-Минтақа ППХ инспектори                                                                                   32
1-Минтақа ППХ инспектори                                                                                   32
Mutaxassis                                                                                                 30
Davlatobod tumani PPX inspektori                                                                           29
Profilaktika  inspektori                                                                                   28
safdor xodimi                                                                                              28
safdor                                                                                                     28
Seksiya komandiri                                                                                          28
Profilaktika katta inspektori                                                                              27
Bo'linma komandiri                                                                                         27
PPXB 2-OTRYAD INSPEKTORI                                                                                   27
PPXB 1-OTRYAD INSPEKTORI                                                                                   27
xaydovchi                                                                                                  27
Namangan viloyati TXTB PPXB                                                                                26
2-otryad MPPX inspektori                                                                                   26
сафдор                                                                                                     25
safdor hodimi                                                                                              25
PPXB 3- OTRYAD INSPEKTORI                                                                                  23
otryad komandiri                                                                                           22
3 Mintaqa PPX inspektori                                                                                   22
Mutaxassist                                                                                                22
PPXB 2-otryad safdor xodimi                                                                                21
PPXB 4- OTRYAD INSPEKTORI                                                                                  20
PPX INS                                                                                                    20
2 Mintaqa PPX inspektori                                                                                   19
Yangi Namangan tumani PPX inspektori                                                                       19
ППХБ ТППХО сафдор ходим                                                                                    19
ppx ins                                                                                                    19
Birinchi otryad inspektori                                                                                 18
safdor xodim                                                                                               18
Namangan viloyati PPXB Tumanlararo otryadi inspektori                                                      18
1-Mintaqa PPX inspektori                                                                                   18
INSPEKTOR                                                                                                  17
ҳайдовчи ходим                                                                                             17
Haydovchi                                                                                                  17
Namangan viloyati IIB JXX JTSB PPXB Maxsus otryad inspektori                                               17
Ҳайдовчи ходим                                                                                             17
Safdor xodim                                                                                               17
отряд командири                                                                                            17
1-otryad PPX inspektori                                                                                    17
xaydovchi hodimi                                                                                           17
1-otryad МPPX inspektori                                                                                   17
PPXB 1-TUMANLARARO OTRYADI INSPEKTORI                                                                      17
Бўлинма командири                                                                                          16
Mutahassis                                                                                                 16
PPXB 4-TUMANLARARO OTRYADI INSPEKTORI                                                                      16
хайдовчи ходим                                                                                             15
Boʼlinma boshligʼi                                                                                         15
PPXB 3-TUMANLARARO OTRYADI INSPEKTORI                                                                      15
3-otryad MPPX inspektori                                                                                   15
ППХБ ТППХО хайдовчи ходим                                                                                  15
 inspektori                                                                                                14
Бўлинма камандири                                                                                          14
Guruh komandir                                                                                             14
сафдор ходими                                                                                              13
PPXB inspektori                                                                                            13
отряд командирининг хизмат бўйича ўринбосари                                                               13
PPXB 2-TUMANLARARO OTRYADI INSPEKTORI                                                                      13
MPPX INSPEKTORI                                                                                            12
Батальон командири                                                                                         12
mutaxassis                                                                                                 12
PPXB ISOMTO’XT OTRYADI INSPEKTORI                                                                          12
Guruh komandiri o'rinbosari                                                                                12
Mutaxassis haydovchi                                                                                       12
bo'linma komandiri                                                                                         12
инспектори                                                                                                 11
Guruh komandiri o‘rinbosari                                                                                11
tumanlararo patrul-post xizmati otryadi birinchi tumanlararo patrul-post xizmati guruhi safdor xodimi      11
Bo’linma komandiri                                                                                         11
PPX bataloni birinchi otryadi safdor-xodimi                                                                11
Mutaxassis mergan                                                                                          11
Туман Жамоат хавфсизлиги хизмати бошлиғи                                                                   11
Profilaktika katta inspektori                                                                              11
PPX inspektori                                                                                             10
Бўстонлиқ ТИИБ 3-сон ИИБ ППХГ инспектори                                                                   10
Mutaxasis                                                                                                  10
Psixolog                                                                                                   10
отряд командирининг маънавий ва маърифий ишлар бўйича ўринбосари                                           10
PPX inspektor                                                                                              10
PPX Inspektor                                                                                               9
Yangi Namangan tumani PPXB inspektori                                                                       9
PPXB ISOMTO'XT OTRYADI INSPEKTORI                                                                           9
Inspektor psixolog                                                                                          9
ППХ инспектори                                                                                              9
guruh komandiri o'rinbosari                                                                                 9
Tumanlar aro PPX Inspektori                                                                                 9
inspektori                                                                                                  9
1-otryad PPX inspektori                                                                                     8
1-tumanlararo inspektori                                                                                    8
 PPX inspektori                                                                                             8
profilaktika Katta inspektor                                                                                8
PPXB 3-OTRYAD INSPEKTORI                                                                                    8
ISMTOXTO muxandisi                                                                                          8
HAYDOVCHI HODIM                                                                                             7
Mutaxassis portlatuvchi                                                                                     7
Mutaxassis o‘qchi                                                                                           7
mutaxassisi                                                                                                 7
Inspektor psixolok                                                                                          7
mutaxassisi                                                                                                 7
nspektor                                                                                                    7
katta ofitser                                                                                               7
Mutahassis o'qchi                                                                                           6
PPX bataloni birinchi otryadi haydovchi-xodimi                                                              6
inspektor                                                                                                   6
katta ofitseri                                                                                              6
ППХ инспектор                                                                                               6
профилактика инспектори                                                                                     6
PPXB 2- OTRYAD INSPEKTORI                                                                                   6
PPX INSPEKTRI                                                                                               6
2-otryad MPPX inspektori                                                                                    6
bo`linma komandiri                                                                                          6
PPXB 2-OTRYAD BO’LINMA KOMANDIRI                                                                            5
 inspektor                                                                                                  5
bo‘linma komandiri                                                                                          5
сафдор ходим                                                                                                5
сафдор хайдовчи                                                                                             5
ISMOTXTO  inspektori                                                                                        5
Lavozim                                                                                                     5
Mutaxassis kinolog                                                                                          5
Текшириш, кузатиш ва тезкор ҳаракатланиш гуруҳи ходими                                                      5
мутахассис                                                                                                  5
туман жамоат тартибини сақлаш бўлими бошлиғи                                                                5
Mutaxassis o'qchi                                                                                           5
3-минтқа ППХ инспектори                                                                                     5
PPX INSPEK                                                                                                  5
Gurux komandiri                                                                                             5
ISOMTO'XTO inspektori                                                                                       5
2-отряд МППХО инспектори                                                                                    5
PPX bataloni 1-otryad otryadi safdor xodimi                                                                 4
PPXB 4-OTRYAD INSPEKTORI                                                                                    4
profilaktika katta inspektor                                                                                4
mutaxassis kinolog                                                                                          4
2-отряд МППХ инспектори                                                                                     4
PPX bataloni ISOMTXT otryadi safdor xodimi                                                                  4
Namangan shaxar IIB JXX JTSB PPX inspektori                                                                 4
Inspektori                                                                                                  4
2-отряд МППХО инспектори                                                                                    4
Katta serjant                                                                                               4
Aloqa boshlig'i                                                                                             4
Inispektor                                                                                                  4
Katta ofitser                                                                                               4
PPXB 3- OTRYAD BO’LINMA KOMANDIRI                                                                           4
Mutaxasis                                                                                                   4
4-TUMANLARARO OTRYADI INSPEKTORI                                                                            4
Mutaxassis pulemyotchi                                                                                      4
Profilaktika inspektori                                                                                     4

In [349]:
col30_cnts = main_df['rank'].value_counts()
col30_cnts

Safdor                4267
Leytenant             1143
Serjant                829
Katta leytenant        682
Kapitan                524
Katta serjant          478
Mayor                  388
Podpolkovnik           207
Kichik serjant         159
3-darajali serjant     126
Inspektor               17
Polkovnik               13
1-darajali serjant       8
Admin                    5
Kichik leytenant         4
kichik serjant           3
Mayor serjant            2
2-darajali serjant       2
katta.Serjant            1
kapitan                  1
SAFDOR                   1
General Mayor            1
General Polkovnik        1
katta serjant            1
Name: rank, dtype: int64

In [350]:
# Function to group similar names
def group_similar(series, threshold=80):
    groups = defaultdict(list)
    used = set()
    
    for i, name in enumerate(series):
        if name in used:
            continue
        groups[name].append(name)
        for j, other in enumerate(series):
            if i != j and fuzz.ratio(name, other) >= threshold:
                groups[name].append(other)
                used.add(other)

    return {k: list(set(v)) for k, v in groups.items()}

inds = pd.Series(col30_cnts.index)
norm_inds = inds.str.lower()
# Normalize names
s_normalized = norm_inds.apply(unidecode)

# Group similar names
similar_names = group_similar(norm_inds, threshold=80)

print(similar_names)

{'safdor': ['safdor'], 'leytenant': ['leytenant'], 'serjant': ['serjant'], 'katta leytenant': ['katta leytenant'], 'kapitan': ['kapitan'], 'katta serjant': ['katta.serjant', 'katta serjant'], 'mayor': ['mayor'], 'podpolkovnik': ['polkovnik', 'podpolkovnik'], 'kichik serjant': ['kichik serjant'], '3-darajali serjant': ['1-darajali serjant', '2-darajali serjant', '3-darajali serjant'], 'inspektor': ['inspektor'], 'admin': ['admin'], 'kichik leytenant': ['kichik leytenant'], 'mayor serjant': ['mayor serjant'], 'general mayor': ['general mayor'], 'general polkovnik': ['general polkovnik']}

In [351]:
max_length = max(len(v) for v in similar_names.values())
data = {k: v + [None] * (max_length - len(v)) for k, v in similar_names.items()}
dict_df = pd.DataFrame(data)
dict_df.columns

Index(['safdor', 'leytenant', 'serjant', 'katta leytenant', 'kapitan',
       'katta serjant', 'mayor', 'podpolkovnik', 'kichik serjant',
       '3-darajali serjant', 'inspektor', 'admin', 'kichik leytenant',
       'mayor serjant', 'general mayor', 'general polkovnik'],
      dtype='object')

In [352]:
max_prof_length = max(len(v) for v in similar_names.values())
prof_data = {k: v + [None] * (max_prof_length - len(v)) for k, v in similar_names.items()}
prof_dict_df = pd.DataFrame(prof_data)
print(prof_dict_df)

   safdor  leytenant  serjant  katta leytenant  kapitan  katta serjant  mayor  podpolkovnik  kichik serjant  3-darajali serjant  inspektor  admin  kichik leytenant  mayor serjant  general mayor  general polkovnik
0  safdor  leytenant  serjant  katta leytenant  kapitan  katta.serjant  mayor     polkovnik  kichik serjant  1-darajali serjant  inspektor  admin  kichik leytenant  mayor serjant  general mayor  general polkovnik
1    None       None     None             None     None  katta serjant   None  podpolkovnik            None  2-darajali serjant       None   None              None           None           None               None
2    None       None     None             None     None           None   None          None            None  3-darajali serjant       None   None              None           None           None               None

In [354]:
sorted_prof_data = pd.DataFrame(np.nan, index=prof_dict_df.index, columns=prof_dict_df.columns)

prof_data_dict = defaultdict(list)
prof_data_dict['safdor'] = ['safdor','oddiy askar','patrul','safdor inspektor','safdor5t5atawatssaaetgcj? @*%14#4 wwww']
prof_data_dict['leytenant'] = ['leytentant','letinant','leytinant','leytenant ','leytenent','letenant','leytenant', ' leytenant']
prof_data_dict['katta serjant'] = ['katta serzhant ','katta serjant','katta serzhant','katta.serjant']
prof_data_dict['serjant'] = ['senjant','serzhant','serjant','serjat','serejant','snt']
prof_data_dict['katta leytenant'] = ['katta leytenant','kattal leytenant','katta leetinant','kt.leytenant','kt-lnt leytenant','kaata leytenant','katta letenant', 'katta leitenant','katta-leytenant','kattta leytenant','kattaleytenant','katta  leytenant']
prof_data_dict['mayor'] = ['maior','mayor ','mayor']
prof_data_dict['kapitan'] = ['kapitan ','kapitan','kanitan','adliya kapitani']
prof_data_dict['podpolkovnik'] = ['podpolkovnik']
prof_data_dict['kichik serjant'] = ['kichik serdant','kichik serjant','kichik serzhant','kichik. serjant','qichiq serjant','kichik sirjand']
prof_data_dict['3-darajali serjant'] = ['iii-darajali serjant','3 darajali serjant','lii-darajali serjant','||| darajali serjant','3-darajali serjant','iii- darajali  serjant','iii-darajali serjant', 'iii-darajali serjant ','iii darajali  serjant','|||-darajali serjant','lll-darajali serjant','lll- darajali serjant','iii-dar serjant','!!!-darajali  serjant','iii darajali serjant','lll darajali serjant','3-dar serjant','3-darajali serjant','iii-dar serjant']
prof_data_dict['inspektor'] = ['inspektor','insifektor','inispektor','starshii inspektor']
prof_data_dict['kichik leytenant'] = ['kichik leytenant']
prof_data_dict['kichik serjant'] = ['k-k serzhant','k-k-serzhant','kk.snt']
prof_data_dict['polkovnik'] = ['polkovnik','palkovnik']
prof_data_dict['general mayor'] = ['general mayor']
prof_data_dict['general polkovnik'] = ['general polkovnik']

max_length = max(len(v) for v in prof_data_dict.values())
data = {k: v + [None] * (max_length - len(v)) for k, v in prof_data_dict.items()}
prof_data_dict_df = pd.DataFrame(data)
print(prof_data_dict_df)

                                    safdor   leytenant    katta serjant   serjant   katta leytenant   mayor          kapitan  podpolkovnik kichik serjant      3-darajali serjant           inspektor  kichik leytenant  polkovnik  general mayor  general polkovnik
0                                   safdor  leytentant  katta serzhant    senjant   katta leytenant   maior         kapitan   podpolkovnik   k-k serzhant    iii-darajali serjant           inspektor  kichik leytenant  polkovnik  general mayor  general polkovnik
1                              oddiy askar    letinant    katta serjant  serzhant  kattal leytenant  mayor           kapitan          None   k-k-serzhant      3 darajali serjant          insifektor              None  palkovnik           None               None
2                                   patrul   leytinant   katta serzhant   serjant   katta leetinant   mayor          kanitan          None         kk.snt    lii-darajali serjant          inispektor              None       None           None               None
3                         safdor inspektor  leytenant     katta.serjant    serjat      kt.leytenant    None  adliya kapitani          None           None    ||| darajali serjant  starshii inspektor              None       None           None               None
4   safdor5t5atawatssaaetgcj? @*%14#4 wwww   leytenent             None  serejant  kt-lnt leytenant    None             None          None           None      3-darajali serjant                None              None       None           None               None
5                                     None    letenant             None       snt   kaata leytenant    None             None          None           None  iii- darajali  serjant                None              None       None           None               None
6                                     None   leytenant             None      None    katta letenant    None             None          None           None    iii-darajali serjant                None              None       None           None               None
7                                     None   leytenant             None      None   katta leitenant    None             None          None           None   iii-darajali serjant                 None              None       None           None               None
8                                     None        None             None      None   katta-leytenant    None             None          None           None   iii darajali  serjant                None              None       None           None               None
9                                     None        None             None      None  kattta leytenant    None             None          None           None    |||-darajali serjant                None              None       None           None               None
10                                    None        None             None      None    kattaleytenant    None             None          None           None    lll-darajali serjant                None              None       None           None               None
11                                    None        None             None      None  katta  leytenant    None             None          None           None   lll- darajali serjant                None              None       None           None               None
12                                    None        None             None      None              None    None             None          None           None         iii-dar serjant                None              None       None           None               None
13                                    None        None             None      None              None    None             None          None           None   !!!-darajali  serjant                None              None       None           None               None
14                                    None        None             None      None              None    None             None          None           None    iii darajali serjant                None              None       None           None               None
15                                    None        None             None      None              None    None             None          None           None    lll darajali serjant                None              None       None           None               None
16                                    None        None             None      None              None    None             None          None           None           3-dar serjant                None              None       None           None               None
17                                    None        None             None      None              None    None             None          None           None      3-darajali serjant                None              None       None           None               None
18                                    None        None             None      None              None    None             None          None           None         iii-dar serjant                None              None       None           None               None

In [ ]:
# prof_data_dict_df.to_excel('e_patrul_profs.xlsx')

In [356]:
inds = pd.Series(col29_cnts.index)
norm_inds = inds.str.lower()
# Normalize names
# s_normalized = norm_inds.apply(unidecode)

# Group similar names
similar_names = group_similar(norm_inds, threshold=80)

max_length = max(len(v) for v in similar_names.values())
data = {k: v + [None] * (max_length - len(v)) for k, v in similar_names.items()}
dict_df = pd.DataFrame(data)
dict_df.columns

Index(['inspektor', 'p.i', 'mutaxassis', 'ppx inspektori', 'katta inspektor',
       '4-минтақа ппх инспектори', 'ппх инспектори', 'guruh komandiri',
       'инспектор', 'гуруҳ командири',
       ...
       'otr/gur/ kom', 'ppxb 4-tumanlararo otryadi xaydovchi xodimi',
       'ppxb 1- otryad inspektori safdor xodimi', 'tumanlararo safdor xodim',
       'ппхб ҳайдовчиси', 'ppxb hizmatini tashkil etish',
       'axborot tehnalogiyalari guruhi ', 'kadirlar guruhi ',
       'ppxb xizmat kursatish komindanti', ' ппхб катта мухандиси'],
      dtype='object', length=355)

In [357]:
max_posi_length = max(len(v) for v in similar_names.values())
posi_data = {k: v + [None] * (max_posi_length - len(v)) for k, v in similar_names.items()}
posi_dict_df = pd.DataFrame(posi_data)
print(posi_dict_df)

        inspektor   p.i       mutaxassis         ppx inspektori        katta inspektor        4-минтақа ппх инспектори        ппх инспектори         guruh komandiri      инспектор    гуруҳ командири    сафдор ходим         profilaktika inspektori   хайдовчи  safdor        inspektor psixolog          otryad komandiri   ppx xodimi  patrul-post xizmati inspеktori               davlatobod tumani ppx inspektori   safdor xodimi  seksiya komandiri      bo'linma komandiri              ppxb 2-otryad inspektori    xaydovchi            namangan viloyati txtb ppxb      2-otryad mppx inspektori    сафдор  3 mintaqa ppx inspektori     ppxb 2-otryad safdor xodimi     ppx ins                    yangi namangan tumani ppx inspektori     ппхб тппхо сафдор ходим  birinchi otryad inspektori  namangan viloyati ppxb tumanlararo otryadi inspektori   ҳайдовчи ходим                              namangan viloyati iib jxx jtsb ppxb maxsus otryad inspektori        отряд командири   xaydovchi hodimi          ppxb 1-tumanlararo otryadi inspektori   бўлинма командири  boʼlinma boshligʼi           отряд командирининг хизмат бўйича ўринбосари   батальон командири  ppxb isomto’xt otryadi inspektori   guruh komandiri o'rinbosari    mutaxassis haydovchi  tumanlararo patrul-post xizmati otryadi birinchi tumanlararo patrul-post xizmati guruhi safdor xodimi     ppx bataloni birinchi otryadi safdor-xodimi  mutaxassis mergan   туман жамоат хавфсизлиги хизмати бошлиғи  бўстонлиқ тииб 3-сон ииб ппхг инспектори  psixolog  отряд командирининг маънавий ва маърифий ишлар бўйича ўринбосари    tumanlar aro ppx inspektori     ismtoxto muxandisi    mutaxassis portlatuvchi   katta ofitser    mutahassis o'qchi         профилактика инспектори               ppxb 2-otryad bo’linma komandiri  сафдор хайдовчи      ismotxto  inspektori  lavozim   mutaxassis kinolog                   текшириш, кузатиш ва тезкор ҳаракатланиш гуруҳи ходими  мутахассис      туман жамоат тартибини сақлаш бўлими бошлиғи   2-отряд мппхо инспектори           namangan shaxar iib jxx jtsb ppx inspektori  katta serjant  aloqa boshlig'i  mutaxassis pulemyotchi  катта тезкор вакил  ppxb isomto’xt otryadi mutaxassisi   isomtuht safdor hodimi    бўлим бошлиғи   jqb  tezkor vakil  ppx bataloni shtab navbatchilik qismi navbatchi-yordamchisi  ppx bataloni shtab navbatchilik qismi katta inspеktor navbatchisi  ппхб инспектор-навбатчиси               ppxb isomto’xt otryadi guruh komandiri  kinolog  gurux mutaxassisi   namangan shahar ppx inspektori  ппхб тппхо гурух командири  muhandis   lll  ppxb navbatchilik qismi  admin   катта инспектор              ppxb komandirining o'rinbosari          ўраб олиш ва кўздан кечиришни ташкиллаштириш гуруҳи мутахассиси  ппхб навбатчи ёрдамчиси   сув билан зарба бериш гуруҳи оператори   namangan viloyati txtb ppxb guruh komandiri  p.k.i  32509893500073  davlatobod tumani ppx bulinma komandiri  markaz o'rinbosari  kichik inspektor  front  viloyat iib jxx jtsb boshlig'i o'rinbosari     jtsb boshlig‘i o‘rinbosari   patrullik guruhi komandiri  patrul   жамоат тартибини сақлаш бошқармаси бошлиғи ўринбосарлари   birinchi tumalararo patrul-post xizmati guruhi inspektori  otryad mutahasisi  ppx otr kom urin  mutaxassis seksiya komandiri    test                namangan viloyati ppxb inspektori  bosh prokuraturasi huquqni muhofaza qilish akademiyasi         batalyon komandiri orinbosari  serjant      batalyon komandiri        3-thmg komandiri  mutaxassis kovaleriyachi  ппх исомтўхто инспектори         inspektor xodimi  o'zbekiston t 1-o'rinbosari      operator  оператор   ppx bataloni isomtxt otryad mutaxasis xodimi  ppx bataloni isomtxt otryadi gurux komandiri o‘rinbosari   иив                ppx bataloni isomtxt otryadi         ppx bataloni birinchi otryadi bo‘linma komandiri  namangan viloyati iib jxx jtsb ppxb maxsus otryad suv bilan zarba berish xaydovchisi  komandir otryad o`rinbosari  гурух командири ўринбосари              1 otryad komandiri orinbosari   ppx brigadasi    qo'qon sh 1-o'rinbosari  mppx 2-otryad gurux komandiri  2-отряд мппхо  ppx otuqto gurux kom  jxx atb  namangan shaxar chorsu mfy xtm inspertori    mtb inspektori  етакчи мутахассиз  yekakchi mutaxassisi  otliq xodim  aloqa      ppx guruh koman  ppxb xizmat buyicha orinbosari  ismotxto guruh komandiri  1-туманлараро ppx inspektori   1-mintaqa ppxo 1 gurux komandiri  iib boshqarma boshliği  хттб ҳпг катта инспектори  1-отряд ppx inspektori        namangan shahar iib ppx 4-sonli ozod mfy htm inspektori    2-минтақа ппх отряд командири   iiv  бош мутахассиз  4-ммм ппхо камандири  test jxd  disigner     so'x t 1-o'rinbosari     furqat t 1-o'rinbosar       1 mintaxa ppx otryad komandiri  жкб ттиг этакч мутахссиси   oltiariq t 1-o'rinbosari    bag'dod t 1-o'rinbosar  marg'ilon sh 1-o'rinbosar  yozyovon t 1-o'rinbosar  uchko'prik t 1-o'rinbosari  dang'ara t 1-o'rinbosari  qo'shtepa t 1-o'rinbosar  бошқарма бошлиғи ўринбосари    tuman jamoat xavfsizligi xizmati boshlig`i  виибб жхх жтсб бошлиғи        jtsb boshlig`i  yashnobod tumani iio fmb jtsb boshlig’i      mirzo ulug`bek tumani iio fmb boshlig`i      sergeli tumani iio fmb jtsb boshlig’i          batalion kom o'rin bosar  pp{b ta'minot gurihi  boshqarma boshlig'i o'rinbosari  bbo‘  aloqa guruhi katta muhandisi  davlatobod tumani yuksalish htm bosh inspektori  yangi namangan tumani bunyodkor htm bosh inspektori  namangan shahar obihayot htm bosh inspektori  iib jxx jtsb 1-o'rinbosari          iib jxx jtsb boshlig'i  тошкент шаҳар ички ишлар бош бошқармаси бошлиғининг жамоат тартибини сақлаш бўйича ўринбосари  otryad komandirining mtbyo  qashqadaryo viloyati txtb jtsg inspektori  баталони командири o'rinbosari  335960505  trx jqb   farg'ona viloyati iib jxx jtsb ppx komandiri mmib o'rinbosari  a.boronov  катта мутахассис         2-tumanlaro otryadi komandiri  txtb ppxb   mutaxassis radiotelcfonist  mutaxassis mo‘ljalga oluvchisi  otyad kom yordam  aloqachi  жамоат тартибини сақлаш бошқармаси назорат-лицензиялаш фаолияти бўлинмаси бошлиғи  жамоат тартибини сақлаш бошқармаси муҳим топшириқлар бўйича инспектори  жамоат тартибини сақлаш бошқармаси катта инспектори  mutaxassis motosikl    mutaxasis yo'naltiruvchi  ok mtbyo, mty  boshliq o'rinbosari  gurux o‘rinbosari  kmtbyomt  komandir  brigada komandiri  jtsb nq katta inspektor navbatchi     davlatobod tumani iib jxx jtsb ppx otryad komandiri           otr kom o'rinbosari  ўмиб  ppx texniki   ppx  batalion komandirining ma'naviy va ma'rifiy ishlar bo'yicha o'rinbosari    batalion komandirining xizmat bo'yicha o'rinbosari      yangi namangan tumani iib jtsb ppx 4-sonli xtm inspektori  штқзулеўк      farg'ona viloyati iib imh ppx otryadi xizmat buyicha o'rinbosari  ppxb mmib orinbosari  иив жтсх ппх бўлим бошлиғи           ппхб командирининг мттб ўринбосари      ппхб командирининг ўринбосари-исомтўхто командири       4-минтақа ппхо командирининг ммиб ўринбосари  mmio'  иив ўринбосари                  namangan shaxar ppx otryad komandiri  namangan viloyati ppxb otliq guruxi  хизмат бошлиғи  ткд жкх булим бошлиги  умиб тезкор вакил  ппх исомтўхто   мутахассис  rank  жтсг  транспорт жтсб инспектори  3-guruh savdor hodimi  oʻttaa xasis ages      bo'lim boshlqi  kkkkl   п.и   pki  батальон командири ўринбосари   bosh inspektor  ppx,atalioni atg katta muxandisi  инспектор ходими  portlatuvchi  radiotelefonchi  32904966800012  94-058-98-00  ахборот технологиялари бўйича бош инспкектори  kj.jk.jk.  сержант  shayxontohur tumani iio fmb 5-sonli iib hpb profilaktika inspektori    мтб инспектори   p/i  podpolkovnik ppx bataloni komandiri o‘rinbosari     ppx bataloni komandiri mmi bo‘yicha urinbosari  namangan shahar gishtkuprik 5-son mfy ppx inspektori  ppx bataloni komandrining o‘rinbosari isomto‘xto komandiri  ppx bataloni xizmatni tashkillashtirish guruhi katta inspеktori  ppx bataloni ta’minlash guruhi starshinasi  kadrlar guruxi katta inspеktori  ppx bataloni ta’minlash guruhi haydovchi-xodimi  ppx bataloni isomtxt otryadi suv bilan zarba bеrish guruhi komandiri      ppx bataloni isomtxto haydovchi-xodimi  mutaxassis raqam xisobchi  mutaxassis ags hisobi  mutaxassis haydovchi (motosiklchi))  mutaxassis hisob raqam  patrullik guruhi komandiri oʼrinbosari-haydovchi  uqchi  mutaxasis sapyor;  жхх бош инспектор  tezkor navbatchi  98162 harbiy qism  mutaxassis opirotor  komandir seksiya   gurh kamamdiri yordamchisi  feldsher   dev  developer  viloyat admin  tuman admin  gdsg  o'qituvchi  prod test  prof ins  дознаватель  9999999999999999  ta’minot bo‘yicha yordamchi  ofitser    mttv komandiri  kiber  kontrrazvedka boʻlim boshligʻi  guruh ofitseri  super  komandir otryad  kichik serjant  yurist  surishtiruvchi  surushtiruv boshlig‘i  pulemyotchi  mutaxassis feldsher    ok         komandir oʻrinbosari   3-отряд софдор-ходими    тошкент шахар иибб жтсб бош инспектори  uchtepa tumani  pd  phvpx ее  inspektor ходим  gurux kom   бустанлик тиман  толебй мфй     1-ммм ппхо 1-гурух командири  1-отряд гурух командири   ppxb otliq guruhi safdor xodimi  сурхандарё вилоят ииб шмх саф бўлинмалари ппхо инспектори  mppx inspektori tungi klub   ппхб коменданти  ппхб командирининг моддий техника таъминоти бўйича ўринбосари                  ikkinchi tumanlararo ppx guruhi inspektori  ppx  katta muxandisi  ppx tuman insp  старший инспектор  atg muhandisi  4-минтақа ппх хайдовчи  1-mmm ппхo tib o'rinbosari   ppxb otliq guruhi komandiri  ppxb 3-tumanlararo otryadi bo’linma komandiri   ta'minlash guruhi inspektori  suv bilan zarba berish operatori  uchqurgon tumani  ppx inspektori    yangi namangan tumani biruniy 2-sonli mfy ppx inspektori   namangan viloyati ppxb tumanlararo   isomtuxt otryadi  isomtuhta  namangan viloyati ppxb navbatchisi  maxsus otryad ppx inspektori    isomtuht mutahasisi  ppxb safdor hodimi  otr/gur/ kom  ppxb 4-tumanlararo otryadi xaydovchi xodimi  ppxb 1- otryad inspektori safdor xodimi  tumanlararo safdor xodim  ппхб ҳайдовчиси  ppxb hizmatini tashkil etish  axborot tehnalogiyalari guruhi   kadirlar guruhi   ppxb xizmat kursatish komindanti   ппхб катта мухандиси

In [197]:
posi_dict_df["yangi namangan tumani biruniy 2-sonli mfy ppx inspektori "].values

array(['yangi namangan tumani iib ppx inspektori',
       'yangi namangan tumani iib guzal mfy xtm ppx inspektori',
       'yangi namangan tumani biruniy 2-sonli mfy ppx inspektori ', None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None, None, None, None, None, None, None, None,
       None, None, None, None], dtype=object)

In [ ]:
sorted_posi_data = pd.DataFrame(np.nan, index=posi_dict_df.index, columns=posi_dict_df.columns)

posi_data_dict = defaultdict(list)
posi_data_dict['inspektor'] = ['inspektori','nspektor','inspector','inspektori','ispektor','inspektor','inspektor','sinspektori','eko inspektor','inbspektor','inspektor','isnpektor',
		'inspektori','imspektor','inspektor.','inspektori','ppx inspektor','inispektor',' inspektori', 'ppx inaspektori', 'ppx ibspektori',
       	'ppxb inspektori', 'ppx inspektori', 'ppx insptktori','mppxo inspektori', 'inspektori', 'ppx onspektori','ppx inspektpri', 'ppx< inspektori', 'ppx inspetktori',
       	'ppx inspektrori ', 'inspektori ', 'ppx  inspektori ','mppx insoektori', ' ppx inspektori ', 'mppx inspektori ','ppx inpektro', 'ppx inspektrori', 'ppx inspektr',
       	' ppx inspektori', 'xob inpektori', 'ppx inspekt','ppx inispektori', 'ppx inspekrori', ' ppx inspektor','ppx inspek|tori', 'ppx insprktori', ' inspektori ',
		'ppx inspektor', 'ppx inpektor', 'ppx isnpektori','ppx insperktor', 'ppx inspektor ', 'ppxb katta inspektori','sinspektori', 'ppx inspek', 'ppx inspektori ', 'ppx inspeltor',
       	'ppx inspektri', 'mppx inspektori', 'ppx  inspektori','p i inspektori', ' inspektor', 'ppx inspektro', 'ppxb inspektor','ppx iinspektori', 'ppx inpektori', 'mppxo inspektori ',
       	'ppx inspektort', 'ppx inspector','ппхб хтг инспектори', 'ппхб хтэг инспектори', 'ппх инспектори','жхд инспектори', 'ппх инсектори', 'ппх  инспектор',
       	'ппх  инспектори', 'ппх ипспектор', 'ппх инпектори ','ппх инспректор ', 'ппх инспектори ', 'ппх инспектор','инспектори','инспкетор', 'инспекитор', 'инспктор', 
		'мтб инспектор', 'инспекор','инспекиор', 'бош инспектор', 'инспектор ', '9инспектор','инпектор', 'инспетор', 'инсапектор', 'инспектор', 'ппх инспектор','инспектори',
		'patrul-post xizmati inspеktori', 'patrul post xizmati inspektori','davlatobot tumani ppx ispektori','davlatobod tumani  ppx inspektori',
		'davlatobod tumani iib jxx jtsb ppx inspektori','davlatobod tumani xtm inspektori','davlatobod tumani ppx inspektori ','davlatobot tumani iib ppx inspektori',
		'davlatobod tumani ppx inspektori','davlatobo tumani ppx inspektori','davlatobor tuman xtm inspektori','davlatobod tumani ppx ispektori',
		'1-otryad ppx inspektori', 'ppxb 2- otryad inspektori','ppxb isomtxt otryadi inspektori', '1-otryad inspektori ','ppx 1-otryad inspektori', 'ppxb 3-otryad inspektori',
		'ppxb 1-otryad inispektori', '2-otryad inspektori','ppxb 4-otryad inspektori', 'ppxb 1-otryad inspektori','ppx bataloni 1-otryad inspektori', 'ppxb 3-otryad  inspektori',
		'ppxb 2-otryad inspektori', 'ppxb 4- otryad inspektori safdor','ppxb 1-otryad inispektori ', 'ppxb 4- otryad inspektori','ppxb 3- otryad inspektori', 'ppxb 1-otryad inspektor',
		'ppxb katta inspektori','3-otryad mppx inspektori ', '1-otryad ppx inspektori','2-otryad mppx inspektori ', '1-otryad ppx inspektori ',
		'1-otryad мppx inspektori ', '2-otryad mppx inspektori','2-otryad inspektori', '13-otryad mppx inspektori','2-otryad mppxo inspektori ', '1-otryad ppx inspektori  ',
		'2 otryad mppx inspektori', '1-otryad mppx inspektori     ','3-otryad мppx inspektori', '1-otryad inspektori ','3-otryad мppx inspektori ', '3-otryad mppx inspektori  ',
		'2 mintaqa ppx inspektori', '1-mintaqa ppx inspektori','3 mintaqa ppx inspektori', '2-mintaqa ppx inspektori','ppx ins', 'ppx ins ', 'ppx insp', 'ppx inspek', 'ppx inf',
		'yangi namangan tumani ppxb inspektori','yangi namangan tumani ppx inspektori  ','yangi namangan tumani ppx inspektori ','yangi namangan tumani ppx inspektori',
		'yangi namangan tumani ppxb inspektori ','yangi namangan tumani ishonch xtm bosh inspektori','yangi namangan tumani ppx bulinma komandiri',
		' yangi namangan tumani ppxb inspektor','yangi namangan tumani iib ppx inspetori','yangi namangan tumani iib jxx jtsb ppx inspektori',
		'yangi namangan tumani iib ppx inspektori','yangi namangan tumani htm inspektori','yangi namangan tumani iib guzal mfy xtm ppx inspektori',
		'namangan viloyati ppxb tumanlararo otryadi inspektori','namangan viloyati iib ppxb maxsus otryadi inspektori','namangan viloyati ppxb maxsus otryad inspektori',
		'namangan viloyati ppxb tumalararo otryadi inspektori','namangan viloyati iib ppxb maxsus otryad inspektori','birinchi otryad inspektori', 'ikkinchi otryad inspektori',
		'ppxb 2-tumanlararo otryadi  inspektori','ppxb 3-tumanlararo otryadi inspektori','ppxb 4-tumanlararo otryadi inspektori','ppxb 3- tumanlararo otryad inspektori',
		'4-tumanlararo otryadi inspektori','ppxb 1-tumanlararo otryadi inspektori','ppxb 2-tumanlararo otryadi inspektori','ppxb 3-tumanlararo otryad inspektori',
		'ppxb 2-tumanlararo otryad inspektori','namangan viloyati iib jxx jtsb ppxb maxsus otryad inspektori','namangan viloyati iib ppxb maxsus otryadi inspektori',
		'namangan viloyati ppxb maxsus otryad inspektori','namangan viloyati iib jxx jtsb ppxb maxsus otryad inspektorii','namangan shaxar iib jxx jtsb ppx otryadi inspektori',
		'namangan viloyati iib ppxb maxsus otryad inspektori',
		'ppx isotoxto  inspektori','ppxb isomto’xt otryadi inspektori','ppxb isomtxt otryadi inspektori',"ppxb isomto'xt otryadi inspektori",'бўстонлиқ тииб 3-сон ииб ппхг инспектори',
		'2-tumanlararo inspektori', '1-tumanlararo inspektori','2-tumanlararo ppxg inspektori', 'tumanlar aro ppx inspektori','профилактика инспектори', 'профилактика инспектори ',
		'ismtoxto  inspektori', 'ppx isotoxto  inspektori',"isoto'xto inspektori", 'ismotxto ppx inspektori',' ismotxto  inspektori', ' ismtoxto inspektori',
		'ismotxto  inspektori', "isomto'xto inspektori",'1-отряд ппх инспектори ', '2-отряд мппхо инспектори','2-отряд мппхо инспектори  ', '2-отряд мппх инспектори ',
       	'2-отряд мппх инспектори', '2-отряд мппхо инспектори ','1-отряд мппх инспектори ','namangan shaxar iib jxx jtsb ppx otryadi inspektori',
		'yangi namangan tumani iib jxx jtsb ppx inspektori','namangan shaxar iib jxx jtsb ppx inspektori','namangan shaxar ppx inspektori','ppx tuman insp',
		'namangan shahar ppxb inspektori','namangan shahar ppx inspektori', 'namangan shaxar ppx inspektori','ппхб инспектор-навбатчиси ','1-туманлараро ppx inspektori',
		'inspektor safdor xodimi', 'inpektor xodim', 'inspektor xodimi','namangan shahar ppxb inspektori','namangan viloyati ppxb inspektori',
       	'namangan viloyati ppxb maxsus otryad inspektori','namanmgan viloyati ppxb inspektori','ikkinchi tumanlararo patrul-post xizmati guruhi inspektori',
       	'birinchi tumalararo patrul-post xizmati guruhi inspektori','tumanlararo patrul-post xizmati gurug‘i inspеktori','ппх исомтўхто инспектори',
		'namangan shaxar chorsu mfy xtm inspertori','qashqadaryo viloyati, iib ppxb inspektori',' inspektori', 'katta inspektori', 'mppx inspektori',
		'inspektori ', 'ppxb inspektori', ' inspektor', 'mppx inspektori ','sinspektori', 'mppxo inspektori', 'xob inpektori', 'inspektori',
		'mtb inspektori', 'jtsg inspektori', ' inspektori ','jtsb inspektori','ikkinchi tumanlararo patrul-post xizmati guruhi inspektori','mppx inspektori tungi klub ',
       	'ikkinchi tumanlararo ppx guruhi inspektori',' ppx inspektori', '1-отряд ppx inspektori','davlatobod tumani iib jxx jtsb ppx inspektori',
       	'davlatobod tumani  iib jxx jtsb ppx otryad inspektori','yangi namangan tumani htm inspektori','namangan shahar iib ppx 4-sonli ozod mfy htm inspektori',
       	'yanginamangan tumani iib ppx 3-sonli gozal mfy htm inspektori','yangi namangan tumani iib jtsb ppx 4-sonli xtm inspektori','инспектор ходими',
		'yangi namangan tumani iib guzal mfy xtm ppx inspektori','мтб инспектори', 'мтб инспектор', 'инспектори','p/i', 'pi','транспорт жтсб инспектори','п.и',
		'shayxontohur tumani iio fmb 5-sonli iib hpb profilaktika inspektori',' inspektori', ' inspektor', 'sinspektori','prof ins','eko inspektor'
		'сурхандарё вилоят ииб шмх саф бўлинмалари ппхо инспектори','ppxb 3-tumanlararo otryadi inspektori','inspektor ', 'inspektor ходим',
		'maxsus otryad ppx inspektori', '1-otryad ppx inspektori','1-otryad ppx inspektori ', '2-otryad mppx inspektori','2 otryad mppx inspektori', '3-otryad мppx inspektori',
		"ta'minlash guruhi inspektori",'namangan viloyati ppxb tumanlararo','namangan shahar gishtkuprik 5-son mfy ppx inspektori','uchqurgon tumani  ppx inspektori  ',
		'yangi namangan tumani iib ppx inspektori','yangi namangan tumani iib guzal mfy xtm ppx inspektori','yangi namangan tumani biruniy 2-sonli mfy ppx inspektori ']
posi_data_dict['katta inspektor'] = ['katta inspektori','jtsg katta inspektori',' inspektor','jtsb katta inspektori', 'katta inspektor', 'kadr inspektori','ppxb katta inspektori',
		'профилактика катта инспектори ', 'профилактика катта инспектори','катта инспектори','ppx bataloni shtab navbatchilik qismi katta inspеktor navbatchisi','pki',
		'старший инспектор','хттб ҳпг катта инспектори', 'ппхб кг катта инспектори','ппхб хтг катта инспектори','jtsb nq katta inspektor navbatchi ', 'катта инспектор',
		'ppx bataloni xizmatni tashkillashtirish guruhi katta inspеktori','kadrlar guruxi katta inspеktori']
posi_data_dict['kichik inspektor'] = ['kichik inspektor']
posi_data_dict['bosh inspektor'] = ['davlatobod tumani tuquvchi xtm bosh inspektori','davlatobod tumani orzu htm bosh inspektori','davlatobod tumani umid htm bosh inspektori',
       	'davlatobod tumani yuksalish htm bosh inspektori','yangi namangan tumani go`zal htm bosh inspektori','yangi namangan tumani ishonch xtm bosh inspektori',
       	'yangi namangan tumani bunyodkor htm bosh inspektori','yangi namangan tumani beruniy htm bosh inspektori','namangan shaxar lola xtm bosh inspektori',
       	'namangan shahar obihayot htm bosh inspektori', 'бош инспектори', 'бош инспектор', 'жхх бош инспектор','ахборот технологиялари бўйича бош инспкектори',
		'bosh inspektor','тошкент шахар иибб жтсб бош инспектори']
posi_data_dict['1-mintaqa inspektori'] = ['1-минтақа ппх инспектори ','1-минтака ппх инспектори','1-минтақа ппх инспентори','1-минтақа ппх инспектори','1-минтақа ппх инспектри ',
		'1-mintaqa ppx inspektori']
posi_data_dict['2-mintaqa inspektori'] = ['2-минтақа ппх инспектори', '2-минтақа ппх катта инспектори','2 mintaqa ppx inspektori','2-mintaqa ppx inspektori']
posi_data_dict['3-mintaqa inspektori'] = ['3-минтақа ппх инсипектори','3-минтақа ппх инспектори','3-минтқа ппх инспектори', '3-минтақа ппх иснпектори','3минтақа ппх инспектори',
		'3-минтақа ппх инспектои','3 mintaqa ppx inspektori']
posi_data_dict['4-mintaqa inspektori'] = ['4-минтақа ппх инспектори ','4-минтақа ппх инспектори',' 4-минтақа ппх инспектори']
posi_data_dict['mutaxassis'] = ['mutahasis', 'mutaxassis', 'bosh mutaxassis', 'mutaxassisi','mutaxasis ', 'mutaxassis  ', 'mutaxasis', 'mutaxasiss','mutaxassis ', 'mutahassis',
		'namangan viloyati iib jxx jtsb maxsus otryad mutaxasis','namangan viloyati iib jxx jtsb ppxb maxsus otryad mutaxasisi',
		'mutaxassis o‘qchi', "mutaxassis o'qchi",'mutaxassis aloqachi',
		'мутахассис','ppxb isomto’xt otryadi mutaxassisi','текшириш, кузатиш ва тезкор ҳаракатланиш гуруҳи мутахассиси','mutaxassis portlatuvchi','ппх исомтўхто   мутахассис',
       	'текшириш, кузатиш ва тезкор ҳаракатланишгуруҳи мутахассиси','ўраб олиш ва кўздан кечиришни ташкиллаштириш гуруҳи мутахассиси','otryad mutahasisi',
		'mutaxassis pulemotchi', 'mutaxassis pulemyotchi','ppx bataloni isomtxt otryadi mutaxasis xodimi','ppx bataloni isomtxt otryad mutaxasis xodimi','guruh mutaxassisi',
		'жкб ттиг этакч мутахссиси ','yekakchi mutaxassisi','етакчи мутахассиз', 'етакчи мутахассис','бош мутахассиз','mutaxassis yo‘naltiruvchi','mutaxassis-yunaltiruvchi'
		'mutaxassis hisob','mutaxassis raqam xisobchi','mutaxasis sapyor;','mutaxassis-operator', 'mutaxassis opirotor',
		'mutaxassis feldsher','mutaxasiss kavaleryachi',"isomto'xto mutaxasisi", 'isomtuht mutahasisi']
posi_data_dict['komandir'] = ['3-guruh komandiri', 'guruh komandiri (532)', '1-gurux komandiri','gurux komandiri ', 'guruh komandiri ', '3-gurux komandiri',
       	'guruh komandir', 'guruh  kamandiri', '4-guruh kamandiri','guruh komandiri', 'guruh kamandiri', 'ppx gurux komandiri','1-guruh komandiri', 'ppx guruh komandiri', 'guruh koma',
       	'2-gurux komandiri', 'gurux kamandiri', 'guruh  komandiri','2- gurux komandiri', 'gurux komandiri','2-гурух камандири', 'гуруҳ командири', 'гурух командири',
       	'гурух камандири', 'гурух командири ','2-otryad komandiri', 'ppxb 1-otryad komandiri','otryad komandiri ', 'otiryad komandiri',
		'1-otryad gurux komandiri', 'ppxb 2-otryad komandiri','otryad kamandiri', '1-otryad komandiri', 'otryd kamandiri','ppxb 4- otryad komandiri', '2-otryad komandiri ',
		'ppxb 3- otryad komandiri', 'ismotxt otryad komandiri','ppx otryad komandiri', 'otyad komandiri', 'otriat komandiri','otryad komandiri',
		'seksiya komandir', 'seksiya komandiri','bo’linma komandiri', 'bo‘linma komandiri', 'bolinma komandiri',"bo'linma komandiri", "ppx bo'linma komandiri",
		"bo'linma komandiri ", "bo'linma kamandiri", 'bo`linma komandiri','bulinma komandiri','отряд командири', '3-ппх отряд командири', 'отряд командири ў/и',
		'ppxb 1-tumanlararo otryadi komandiri','ppxb 3-tumanlararo otryadi komandiri','ppxb 4-tumanlararo otryadi komandiri','ppxb 3-tumanlararo otryad komandiri',
		'ppxb 1-tumanlararo otryadi bo’linma komandiri','ppxb 2-tumanlararo otryad komandiri','namangan viloyati iib jxx jtsb ppxb tumanlararo otryad komandiri',
		' namangan viloyati iib jxx jtsb ppxb maxsus otryad guruh komandiri','namangan viloyati iib jxx jtsb ppxb maxsus otryad gurux komondiri','бўлинма командири', 
		'бўлинма камандири', 'бўлинма камандири ','батальон командири', 'батальон командири ',"ppx 2-otryad bo'linma komandiri",'ppx otuqto gurux kom',
		'ppxb 2-tumanlararo otryadi bo’linma komandiri','ppxb 2-otryad komandiri',"ppxb 2-tumanlararo otryadi bo'linma komandiri",'ppxb otliq guruhi komandiri', 'ppx guruh komandiri',
		"ppx 2-otryad bo'linma komadiri", 'ppxb 1-otryad komandiri',"ppxb 1-otryad bo'linma komandiri",'ppxb 3-tumanlararo otryadi bo’linma komandiri',
		'ppxb 4-otryadi bo’linma komandiri', "2-otryad bo'linma kamandiri",'ppxb 2-otryad  bo‘linma komandiri ','ppxb 4- otryad bo’linma komandiri',
		'mppx 3-otryad bo‘linma komandiri','ppxb 2-otryad bo’linma komandiri','ppxb 1-tumanlararo otryadi bo’linma komandiri',
		"ppx 1-otryad bo'linma komandiri",'ppxb 4-tumanlararo otryadi bo’linma komandiri','ppxb 1-otryad bo’linma komandiri','ppxb 3- otryad bo’linma komandiri',
       	'текшириш, кузатиш ва тезкор ҳаракатланиш гуруҳи командири','ўраб олиш ва кўздан кечиришни ташкиллаштириш гуруҳи командири',
		'ппхб тппхо гурух командири', 'ппхб тппхо командири','ppx bataloni isomtxt otryadi gurux  komandiri','ppxb isomto’xt otryadi guruh komandiri',
		'ppxb isomto’xt otryadi gurux komandiri','ppxb ismotxt otryadi komandiri','otr/gur/ kom','сув билан зарба бериш гуруҳи командири',
       	'ppx bataloni isomtxt otryadi gurux  komandiri','ppx bataloni isomtxt otryadi gurux  komandiri','mutaxassis-seksiya komandiri', 'mutaxassis seksiya komandiri',
		'davlatobod tumani ppx bulimma komandiri','davlatobod tumani ppx bulinma komandiri','batalyon kamandirining', 'batalyon komandiri',
		'ppx bataloni birinchi otryadi komandiri','ppx bataloni birinchi otryadi bo‘linma komandiri','safdor ppx bataloni birinchi otryadi bulinma komandiri',
       	"birinchi otryad bo'linma komandiri",'1-mintaqa ppxo 1 gurux komandiri','1-mintaqa ppxo 2 guruh komandiri','2 mintaqa ppxo 2 gurux komandiori', '2 mintaqa ppxo komandiri',
		'3-минтақа ппх 2-гурух командири', '2-минтақа ппх отряд командири','3-минтақа ппх 3-гуруҳ командири','1-минтақа ппх отряд командири ', '4-минтақа ппх гурух командири',
		'3-минтақа ппх 1-гуруҳ командири','3-минтақа ппх 4-гурух командири','2-минтақа ппх  гурух командири', '2-минтақа ппх гурух командири','ismotxto guruh komandiri',
		'4-минтақа ппх 3-гурух командири','3-минтақа ппх 5-гурух командири','4-минтақа ппх 1-гурух командири','4-минтақа ппх 5-гурух командири', '2-минтақа ппх гуруҳ командири',
		'ppxb 1-otryad komandiri', '1-otryad gurux komandiri','ppxb 2-otryad komandiri', 'ppxb 2-otryad gurux komandiri','ppx otryad komandiri', 'mppx 2-otryad gurux komandiri',
		'guruh koma', 'ppx gurux komandiri', 'ppx guruh koman','ppx guruh komandiri','ппхб командирининг ўринбосари-исомтўхто командири','brigada komandiri',
       	'ппхб командири ўринбосари – исомтўхт отряди командири','davlatobod tumani iib jxx jtsb ppx otryad komandiri','namangan shaxar iib jxx ppx otryad bulinma komandiri',
       	'namangan shaxar ppx otryad komandiri','3 mintaxa ppx otryad komandiri', '2 mintaqa ppxo komandiri','1 mintaxa ppx otryad komandiri',
       	'ppx otryad komandiri','4-ммм ппхо камандири','ppxb 1-tumanlararo otryadi komandiri','ppxb 3-tumanlararo otryadi komandiri','ppxb 4-tumanlararo otryadi komandiri',
		'ppxb 3-tumanlararo otryad komandiri','tumanlararo otryad komandiri', 'tumanlararo otryad komandiri ','ppxb 2-tumanlararo otryad komandiri',
		'tumanlararo otryadi komandiri','ppx bataloni isomtxt otryadi suv bilan zarba bеrish guruhi komandiri','ppx bataloni komandrining o‘rinbosari isomto‘xto komandiri',
		'ppx bataloni ta’minlash guruhi starshinasi','komandir seksiya','otriat komandiri', 'mttv komandiri','ppxb 2-tumanlararo otryadi bo’linma komandiri',
		'ppxb 1-tumanlararo otryadi komandiri','ppxb 4-tumanlararo otryadi bo’linma komandiri',"ppxb 2-tumanlararo otryadi bo'linma komandiri",
		'ppxb 3-tumanlararo otryadi komandiri','ppxb 3-tumanlararo otryadi bo’linma komandiri','ppxb 4-otryadi bo’linma komandiri','ppxb 4-tumanlararo otryadi komandiri',
		'ppxb 3-tumanlararo otryadi bo’linma komandiri ','ppxb 3-tumanlararo otryad komandiri','ppxb 1-tumanlararo otryadi bo’linma komandiri',
		'ppxb 4- otryad bo’linma komandiri','ppxb 3- otryad bo’linma komandiri','ppxb 2-tumanlararo otryad komandiri','1-отряд гурух командири ', 'гурух командири ',
		'3-минтақа ппх 2-гурух командири', '1-ммм ппхо 2-гурух командири','1-ммм ппхо 4-гурух командири ', '1-ммм ппхо 1-гурух командири',
       	'1-ммм ппхо 3-гурух командири ', '1-ммм ппхо 5-гурух командири ','gurux kom ','guruh koma']
posi_data_dict['profilaktika inspektori'] = ['profilaktika inspektori', 'profilaktika  inspektori','profilaktika inspektor ','profilaktika inspector',
		'profilaktika inspektori ','profilaktika inspektor', 'profilaktika  inspektori ','profilaktikainspektor']
posi_data_dict['profilaktika katta inspektori'] = ['profilaktika katta inspektori','profilaktika katta inspektor','profilaktika  katta inspektori', 'profilaktika katta inspektori ',
		'profilaktika katta ispektor']
posi_data_dict['xaydovchi'] = ['хайдовчи', 'хайдwовчи','xaydovchi', 'haydovchi ', 'haydovchisi', 'haydovchi','хайдовчи ходим ', 'хайдовчи ходими', 'хайдовчи  ходим',
       	'хайдовчи ходим', 'ҳайдовчи ходим','xaydovchi hodim', 'xaydovchi hodimi ', 'xaydovchi xodim','haydovchi hodim ', 'xaydovchi hodimi', 'haydovchi hodimi',
		'haydovchi xodimi', 'haydovchi xodim', 'haydovchi hodim','xaydovchi  hodimi','ppx bataloni birinchi otryadi haydovchi-xodimi',
		'tumanlararo patrul-post xizmati otryadi birinchi tumanlararo patrul-post xizmati guruhi haydovchisi','mutaxassis-haydovchi', 'mutaxasis haydovchi','mutaxassis haydovchi',
		'mutahasis haydovchi', 'mutaxasiss haydovchi','mutaxassis xaydovchi','сафдор хайдовчм', 'сафдор хайдовчи','сув билан зарба бериш гуруҳи ҳайдовчиси',
		' сув билан зарба бериш гуруҳи ҳайдовчиси','amangan viloyati iib jxx jtsb ppxb maxsus otryad suv bilan zarba berish xaydovchisi','mutaxassis haydovchi (motosiklchi))'
		'4-минтақа ппх хайдовчи','ppx bataloni isomtxto haydovchi-xodimi','ppx bataloni ta’minlash guruhi haydovchi-xodimi','ppxb 4-tumanlararo otryadi xaydovchi xodimi',
       	'ppxb 2-otryad xaydovchi xodimi','ppxb 2-tumanlararo otryadi xaydovchi xodimi','ппхб ҳайдовчиси']
posi_data_dict['safdor'] = ['сафдор-ходим', 'сафдор ходими', 'садор ходим', 'сафдор ходим ','сафдор ходим', 'сафдор-ходим  ', 'сафдор-ходим ','safdor','сафдор', 'сафдор ',
		'ppx xodimi', 'ppx xodimi ', 'ppx xodmi', ' ppx xodimi','safdor hodim', 'safdor hodim ', 'safdor xodim', 'safdor hodimi','safdor xodimi ', 'safdor-xodim', 'safdor xodimi',
		'ppxb 2-otryad safdor xodimi', 'ppxb 1-otryad xaydovchi xodimi','ppxb 3- otryad safdor xodimi', 'ppxb 2-otryad safdor xodimi ',
		'ppxb 2-otryad xaydovchi xodimi', 'ppxb 1-otryad safdor xodimi','ппхб тппхо сафдор ходим', 'ппхб тппхо хайдовчи  ходим','ппхб тппхо хайдовчи ходим',
		'tumanlararo patrul-post xizmati otryadi birinchi tumanlararo patrul-post xizmati guruhi safdor xodimi','ppx bataloni birinchi otryadi safdor-xodimi',
		'ppx bataloni 1-otryad otryadi safdor-xodimi','ppx bataloni birinchi otryadi safdor xodimi','ppx bataloni 1-otryad otryadi safdor xodimi',
		'ppx bataloni isomtxt otryadi safdor xodimi','сафдор хайдовчм', 'сафдор хайдовчи','катта тезкор вакил','ппхб коменданти',
		'katta serjant',' текшириш, кузатиш ва тезкор ҳаракатланиш гуруҳи ходими','екшириш, кузатиш ва тезкор ҳаракатланиш гуруҳи ходими','tezkor vakil',
       	'текшириш, кузатиш ва тезкор ҳаракатланиш гуруҳи ходими','isomtuht safdor hodimi', 'isomtuht  safdor xodimi','isomtuht safdor xodimi',
		' ўраб олиш ва кўздан кечиришни ташкиллаштириш гуруҳи сафдор ходими','ўраб олиш ва кўздан кечиришни ташкиллаштириш гуруҳи',"pp{b ta'minot gurihi",
		' ўраб олиш ва кўздан кечиришни ташкиллаштириш гуруҳи ','ўраб олиш ва кўздан кечиришни ташкиллаштириш гуруҳи сафдор ходми',
		' ўраб олиш ва кўздан кечиришни ташкиллаштириш гуруҳи сафдор','ўраб олиш ва кўздан кечиришни ташкиллаштириш гуруҳи ','patrul',
		'ppx bataloni shtab navbatchilik qismi navbatchi-yordamchisi','ppxb navbatchilik qismi', 'ppxb navbatchisi','ппхб навбатчи ёрдамчиси',
		'ppx bataloni isomtxt otryadi safdor xodimi','ppx bataloni isomtxt otryad muxandis xodimi','tezkor navbatchi',
       	'ppx bataloni isomtxt otryadi ','ppx bataloni isomtxt otryadi safdor xodimi','serjant','feldsher','ppxb otliq guruhi safdor xodimi',
		'bosh prokuraturasi huquqni muhofaza qilish akademiyasi','jxx atb','2-отряд мппхо','otliq xodim',"mmio'",'умиб тезкор вакил',
		'ppx brigadasi ', 'ppx brigadasi','namangan viloyati ppxb otliq guruxi','namangan viloyati ppxb otliq guruhi','ppxb', 'ppx','namangan viloyati iib jxx jtsb ppxb  ',
		'жтсг','3-guruh savdor hodimi','сержант','kichik serjant','ppx bataloni isomtxt otryadi safdor-xodimi','ppxb 3- otryad safdor xodimi',
       	'ppxb 1- otryad inspektori safdor xodimi','ppxb 1-otryad safdor xodimi', 'ppxb 4- otryad inspektori safdor','tumanlararo safdor xodim',
		'2-отряд сафдор-ходим ', '3-отряд софдор-ходими  ','3-отряд сафдор-ходим ','namangan viloyati ppxb navbatchisi','safdor hodimi','safdor hodim','ppxb safdor hodimi']
posi_data_dict["oʼrinbosar"] = [' namangan viloyati iib jxx jtsb ppxb maxsus otryad inspektoriguruh komandiri urinbosari ',
		'батальон командирини хизмат бўйича ўринбосари','4-отряд командирининг хизмат бўйича  ўринбосари ','батальон командирининг хизмат бўйича ўринбосари',
		'1-мппхо командири хизмат бўйича ўринбосари','ппхб командирининг хизмат бўйича ўринбосари','отряд командирининг хизмат бўйича ўринбосари',
		'отряд командирининг тарбиявий ишлар бўйича ўринбосари','батальон командирининг хизмат буйича уринбосари ',"guruh komandiri o'rinbosari ", "komandir o'rinbosari",
		'guruh komandiri oʻrinbosari', 'guruh kamandir urin bosari','otryad komandiri orinbosari', 'komandir o`rinbosari',"otryad komandiri o'rinbosari", "guruh komandiri o'rinbosari",
		"ppxg komandir o'rinbosari", "otryad komandir o'rinbosari",'guruh komandiri o’rinbosari', 'otryad komandiri o‘rinbosari','guruh komandir o’rinbosari',
		"guruh komandiri or'inbosari",'guruh komandiri o‘rinbosari', 'otryad komandiri o`rinbosari','ppx bataloni birinchi otryadi komandiri',
		'отряд командирининг тарбиявий ишлар бўйича ўринбосари','отряд командирининг маънавий ва маърифий ишлар бўйича ўринбосари',
		'ппхб  командирининг маънавий-маърифий ишлар бўйича ўринбосари','текшириш, кузатиш ва тезкор ҳаракатланиш гуруҳ командирининг ўринбосари',
		'ўраб олиш ва кўздан кечиришни ташкиллаштириш гуруҳи командир ўринбосари',"ppxb isomto’xt otryadi guruh komandiri o'rinbosari",
      	'ppx bataloni  isomtxt otryadi komandiri o‘rinbosari','ppx bataloni birinchi otryadi komandiri o‘rinbosari','ppx bataloni isomtxt otryadi gurux komandiri o‘rinbosari',
		"ppxb isomto’xt otryadi guruh komandiri o'rinbosari","ppxb ismotxt otryad komandiri o'rinbosari",'jtsb boshlig‘i o‘rinbosari ', 'jtsb boshlig`ining o`rinbosari',
		"viloyat iib jxx jtsb boshlig'i o'rinbosari","iib jxx jtsb boshlig'ining o'rinbosari",'batalyon komandirining orinbosari',
		'batalyon komandirining o‘rinbosari', "komandir o'rinbosari","batalyon komandirining o'rinbosari",'batalon komandirining o‘rinbosari',
		"ppx komandirining mtt bo'yicha o'rinbosari","ppxg komandir o'rinbosari", "ppxb 1-otryad komandiri o'rinbosari",
		'ppxb komandiri  mtt orinbosari',"ppxb 4- otryad komandirining o'rinbosari","otryad komandirining o'rinbosari","1-otryad komandirining o'rinbosari",
		'ppxb otryad komandiri orinbosari',"otryad komandiriningo'rinbosari", "ppxb komandiri o'runbosari","ppxb komandirining o'rinbosari",
		'batalyon komandirining orinbosari','batalyon komandirining o‘rinbosari',"batalyon komandirining o'rinbosari",'batalon komandirining o‘rinbosari', 
		'otryad komandiri orinbosari',"otryad komandiri o'rinbosari", 'batalyon komandiri o`rinbosari','batalon komandirining tb o‘rinbosari','ppx otr kom urin',
		'otryad komandiri o‘rinbosari', "batalon komandirir o'rinbosari",'batalyon komandiri orinbosari', "batalon komandiri o'rinbosari",'otryad komandiri o`rinbosari',
		"markaz o'rinbosari","oltiariq t 1-o'rinbosari", "beshariq t 1-o'rinbosar",'ppxb xizmat buyicha orinbosari',"quva t 1-o'rinbosar", "buvayda t 1-o'rinbosari",
       	"quvasoy sh 1-o'rinbosari", "bag'dod t 1-o'rinbosar","uchko'prik t 1-o'rinbosari","dang'ara t 1-o'rinbosari","farg'ona t 1-o'rinbosari",
		"farg'ona t 1-o'rinbosari", "farg'ona sh 1-o'rinbosari","marg'ilon sh 1-o'rinbosar","qo'qon sh 1-o'rinbosari", "farg'ona sh 1-o'rinbosari",
       	"quvasoy sh 1-o'rinbosari",'ppxb mmib orinbosari','ппхб командирининг хизмат бўйича ўринбосари','ппхб командирининг мттб ўринбосари',
       	'ппхб командирининг ммиб ўринбосари','ппхб командирининг ўринбосари-исомтўхто командири','ппхб командири ўринбосари – исомтўхт отряди командири',
		'1-минтақа ппх отряд командарининг ммиб ўринбосари','4-минтақа ппхо командирининг ммиб ўринбосари','ппхб командирининг ммиб ўринбосари',
		'иив ўринбосари','otryad komandiri orinbosari', "otryad komandiri o'rinbosari",'otryad komandiri o‘rinbosari',"tumanlararo otryad komandiri o'rinbosari",
		'ppxb 2-otryad komandiri o’rinbosari','1 otryad komandiri orinbosari',"otryad komandirining o'rinbosari","ismotxt otryad komandiri o'rinbosari",
		"1-otryad komandirining o'rinbosari","otryad komandiriningo'rinbosari",'ppxb otryad komandiri orinbosari',"ppx otryad  komandiri o'rinbosari", "otryad komandir o'rinbosari",
		" 4-otryad komandiri o'rinbosari","ppxb 1-otryad komandiri o'rinbosari","2-otryad komandir o'rinbosari","ppxb 4- otryad komandirining o'rinbosari",
		"ppxb isomto’xt otryadi guruh komandiri o'rinbosari","iotxt otryad komandiri o'rinbosari",'otryad komandiri o`rinbosari','ppxb 3- otryad komandiri o’rinbosari',
		"ppxb ismotxt otryad komandiri o'rinbosari","farg'ona viloyati iib imh ppx otryadi xizmat buyicha o'rinbosari",
       	"farg'ona viloyati iib imh ppx otryadi komandirining tib o'rinbosari ",'batalyon komandirining o‘rinbosari','batalon komandirining o‘rinbosari',
		'batalon komandirining xizmat bo‘yicha o‘rinbosari','ppx bataloni komandiri mmi bo‘yicha urinbosari',"batalion komandirining xizmat bo'yicha o'rinbosari",
		'batalon komandirining tb o‘rinbosari','ppx bataloni komandiri mtt bo‘yicha urinbosari',"qo'shtepa t 1-o'rinbosar",'бошқарма бошлиғи ўринбосари ', 
		'бошқарма бошлиғи ўринбосари  ',"batalon komandiri o'rinbosari", "batalon komandirir o'rinbosari","batalion kom o'rin bosar",
		"boshqarma boshlig'i o'rinbosari","boshqarma boshligi' o'rinbosari",'жамоат тартибини сақлаш бошқармаси бошлиғи ўринбосарлари',
		"iib jxx jtsb o'rinbosar", "iib jxx jtsb 1-o'rinbosari",'гурух командири ўринбосари', ' командири ўринбосари','отряд командир ўринбосари',
		'komandir otryad o`rinbosari','1 mintaxa ppx otryad kom orinbosari', "komandir o'rinbosari",'komandir o`rinbosari',"yozyovon t 1-o'rinbosar",
		"farg'ona t 1-o'rinbosari", "quva t 1-o'rinbosar","furqat t 1-o'rinbosar","so'x t 1-o'rinbosari", "rishton t 1-o'rinbosari","1-mmm ппхo tib o'rinbosari ",
		"otryad komandiri o'rinbosari", "otryad komandir o'rinbosari","otr kom o'rinbosari","batalion komandirining ma'naviy va ma'rifiy ishlar bo'yicha o'rinbosari",
		"tumanlararo otryad komandiri o'rinbosari",'podpolkovnik ppx bataloni komandiri o‘rinbosari','ppx bataloni komandrining o‘rinbosari isomto‘xto komandiri',
		"guruh komandiri o'rinbosari ", "komandir o'rinbosari",'guruh komandiri oʻrinbosari', "ppxg komandir o'rinbosari",'komandir o`rinbosari', 'guruh komandir o’rinbosari',
       	'komandir oʻrinbosari ','ппхб командирининг моддий техника таъминоти бўйича ўринбосари']
posi_data_dict["bo'lim boshlig'i"] = ["bo'lim boshligi", 'boʼlinma boshligʼi', "bo'linma boshlig'i", 'bo‘lim boshlig‘i','туман жамоат хавфсизлиги хизмати бошлиғи',
       	'туман жамоат хавфсизлиги хизмати бошлиғи ','бўлинма бошлиғи','бўлим бошлиғи',"aloqa boshlig'i","viloyat iib jxx jtsb boshlig'i",'iib boshqarma boshliği', 
		"boshqarma boshlig'i",'иив жтсх ппх бўлим бошлиғи','ткд жкх булим бошлиги','jxx jtsb boshlig"i', 'jtsb boshlig‘i', 'tuman jtsb boshlig`i',
       	'jtsb boshlig`i','yashnobod tumani iio fmb jtsb boshlig’i','olmazor  tumani iio fmb jtsb boshlig’i  ','m.ulug`bek  tumani iio fmb jtsb boshlig’i  ',
		'bektemir tumani iio fmb jtsb boshlig’i  ','sergeli tumani iio fmb jtsb boshlig’i  ','yunusobod tumani iio fmb jtsb boshlig’i  ','хизмат бошлиғи',
		'mirzo ulug`bek tumani iio fmb boshlig`i','m.ulug`bek  tumani iio fmb jtsb boshlig’i  ','виибб жхх жтсб бошлиғи','tuman jamoat xavfsizligi xizmati boshlig`i',
		'туман жамоат тартибини сақлаш бошқармаси бошлиғи',"viloyat iib jxx jtsb boshlig'i", "iib jxx jtsb boshlig'i",'jxx jtsb boshlig"i',"bo'lim boshlqi", "bo'lim boshligi", 
		"bo'linma boshlig'i","bo'lim boshlig'i", 'bo‘lim boshlig‘i','batalyon shtab boshligʻi','surushtiruv boshlig‘i',"kontrrazvedka boʻlim boshligʻi",
		"yakkasaroy tumani jtsb boshlig`i"]
posi_data_dict['yordamchi'] = ['gurux komandiri yordamchisi', 'guruh komandiri yordamchisi',"ta’minot bo‘yicha yordamchi"]
posi_data_dict['muxandis'] = ['ppxb isomto’xt otryadi muxandisi','ismoxto muxandisi', "isomto'xto mutaxasisi", 'ismtoxto muxandisi','ppxb isomto’xt otryadi muxandisi',
       	' текшириш, кузатиш ва тезкор ҳаракатланиш гуруҳи муҳандиси','ppxb isomto’xt otryadi muxandisi','muhandis','ppx bataloni isomtxt otryad muxandis xodimi',
       	'ppx bataloni isomtxt otryadi muxandis xodimi','ppx  katta muxandisi','aloqa guruhi katta muhandisi','ppx,atalioni atg katta muxandisi','atg muhandisi','ппхб катта мухандиси']
posi_data_dict['operator'] = ['ppxb isomto’xt otryadi operatori','сув билан зарба бериш гуруҳи оператори',' сув билан зарба бериш гуруҳи оператори ',
		'operator ', 'ppx operator', 'operator','оператор','mutaxassis-operator', 'mutaxassis opirotor','suv bilan zarba berish operatori']
posi_data_dict['aloqachi'] = ['mutaxassis aloqachi','aloqa guruhi katta muhandisi','aloqa','radiotelefonchi','axborot tehnalogiyalari guruhi ']
posi_data_dict["o'qchi"] = ['mutaxassis o‘qchi', "mutaxassis o'qchi","mutahassis o'qchi", "mutaxassis o'qchi",'mutaxassis  o`qchi','mutaxassis-mergan',
		'mutaxassis mergan','pulemyotchi','mutahassis mergan']
posi_data_dict['psixolog'] = ['psixologik', 'psixolog','inspektor psixolog']
posi_data_dict['ofitser'] = ['katta ofitseri', 'katta ofitcer', 'katta ofitser','ofitser','guruh ofitseri']
posi_data_dict['kinolog'] = ['kinolog','mutaxasis kinolog', 'mutaxssis kinolog', 'mutaxassis kinolog','mutaxassis kinoligi', 'mutaxassis kinolik']
posi_data_dict['portlatuvchi'] = ['portlatuvchi']
posi_data_dict['dev'] = ['dev',"prod test",'developer']
posi_data_dict['admin'] = ['admin','viloyat admin','tuman admin']
posi_data_dict['null'] = ['iiv','9999999999999999','test jxd','disigner','штқзулеўк','rank','oʻttaa xasis ages','kkkkl','32509893500073','32904966800012','94-058-98-00',
		'kj.jk.jk.','raqam','siktirganski','98162 harbiy qism','gdsg','  ok','super','uchtepa tumani','pd','phvpx ее']
posi_data_dict['other'] = ["o'qituvchi",'surishtiruvchi','дознаватель','yurist','kiber','isomtuhta otryadi', 'isomtuxt otryadi','isomtuhta','kadirlar guruhi ',
		'ppxb xizmat kursatish komindanti','ppxb hizmatini tashkil etish']

       
       


max_length = max(len(v) for v in posi_data_dict.values())
data = {k: v + [None] * (max_length - len(v)) for k, v in posi_data_dict.items()}
posi_data_dict_df = pd.DataFrame(data)
print(posi_data_dict_df)

                                                                                    inspektor                                                    katta inspektor  kichik inspektor                                       bosh inspektor       1-mintaqa inspektori            2-mintaqa inspektori       3-mintaqa inspektori       4-mintaqa inspektori                                                       mutaxassis                                                              komandir    profilaktika inspektori   profilaktika katta inspektori                                                                                            xaydovchi                                                                                                 safdor                                                                                oʼrinbosar                                  bo'lim boshlig'i                    yordamchi                                                    muxandis                                  operator                         aloqachi              o'qchi            psixolog         ofitser              kinolog  portlatuvchi        dev          admin               null                             other
0                                                                                  inspektori                                                   katta inspektori  kichik inspektor       davlatobod tumani tuquvchi xtm bosh inspektori  1-минтақа ппх инспектори         2-минтақа ппх инспектори  3-минтақа ппх инсипектори  4-минтақа ппх инспектори                                                         mutahasis                                                     3-guruh komandiri    profilaktika inspektori   profilaktika katta inspektori                                                                                             хайдовчи                                                                                           сафдор-ходим   namangan viloyati iib jxx jtsb ppxb maxsus otryad inspektoriguruh komandiri urinbosari                                    bo'lim boshligi  gurux komandiri yordamchisi                            ppxb isomto’xt otryadi muxandisi          ppxb isomto’xt otryadi operatori              mutaxassis aloqachi   mutaxassis o‘qchi          psixologik  katta ofitseri              kinolog  portlatuvchi        dev          admin                iiv                        o'qituvchi
1                                                                                    nspektor                                              jtsg katta inspektori              None           davlatobod tumani orzu htm bosh inspektori   1-минтака ппх инспектори  2-минтақа ппх катта инспектори   3-минтақа ппх инспектори   4-минтақа ппх инспектори                                                       mutaxassis                                                 guruh komandiri (532)   profilaktika  inspektori    profilaktika katta inspektor                                                                                            хайдwовчи                                                                                          сафдор ходими                                             батальон командирини хизмат бўйича ўринбосари                                boʼlinma boshligʼi  guruh komandiri yordamchisi                                           ismoxto muxandisi    сув билан зарба бериш гуруҳи оператори     aloqa guruhi katta muhandisi   mutaxassis o'qchi            psixolog   katta ofitcer    mutaxasis kinolog          None  prod test  viloyat admin   9999999999999999                    surishtiruvchi
2                                                                                   inspector                                                          inspektor              None           davlatobod tumani umid htm bosh inspektori   1-минтақа ппх инспентори        2 mintaqa ppx inspektori    3-минтқа ппх инспектори   4-минтақа ппх инспектори                                                  bosh mutaxassis                                                     1-gurux komandiri    profilaktika inspektor   profilaktika  katta inspektori                                                                                            xaydovchi                                                                                            садор ходим                                          4-отряд командирининг хизмат бўйича  ўринбосари                                 bo'linma boshlig'i  ta’minot bo‘yicha yordamchi                                       isomto'xto mutaxasisi   сув билан зарба бериш гуруҳи оператори                             aloqa   mutahassis o'qchi  inspektor psixolog   katta ofitser    mutaxssis kinolog          None  developer    tuman admin           test jxd                       дознаватель
3                                                                                  inspektori                                              jtsb katta inspektori              None      davlatobod tumani yuksalish htm bosh inspektori   1-минтақа ппх инспектори        2-mintaqa ppx inspektori   3-минтақа ппх иснпектори                       None                                                      mutaxassisi                                                      gurux komandiri      profilaktika inspector  profilaktika katta inspektori                                                                                            haydovchi                                                                                           сафдор ходим                                            батальон командирининг хизмат бўйича ўринбосари                                  bo'lim boshlig'i                         None                                          ismtoxto muxandisi                                 operator                   radiotelefonchi   mutaxassis o'qchi                None         ofitser   mutaxassis kinolog          None       None           None           disigner                            yurist
4                                                                                    ispektor                                                    katta inspektor              None     yangi namangan tumani go`zal htm bosh inspektori   1-минтақа ппх инспектри                             None    3минтақа ппх инспектори                       None                                                       mutaxasis                                                       guruh komandiri    profilaktika inspektori      profilaktika katta ispektor                                                                                          haydovchisi                                                                                           сафдор ходим                                                1-мппхо командири хизмат бўйича ўринбосари                                  bo‘lim boshlig‘i                         None                            ppxb isomto’xt otryadi muxandisi                              ppx operator  axborot tehnalogiyalari guruhi   mutaxassis  o`qchi                None  guruh ofitseri  mutaxassis kinoligi          None       None           None          штқзулеўк                             kiber
5                                                                                   inspektor                                                    kadr inspektori              None    yangi namangan tumani ishonch xtm bosh inspektori   1-mintaqa ppx inspektori                            None    3-минтақа ппх инспектои                       None                                                     mutaxassis                                                       3-gurux komandiri     profilaktika inspektor                            None                                                                                            haydovchi                                                                                         сафдор-ходим                                                 ппхб командирининг хизмат бўйича ўринбосари          туман жамоат хавфсизлиги хизмати бошлиғи                         None   текшириш, кузатиш ва тезкор ҳаракатланиш гуруҳи муҳандиси                                  operator                             None   mutaxassis-mergan                None            None   mutaxassis kinolik          None       None           None               rank                 isomtuhta otryadi
6                                                                                   inspektor                                              ppxb katta inspektori              None  yangi namangan tumani bunyodkor htm bosh inspektori                       None                            None   3 mintaqa ppx inspektori                       None                                                        mutaxasis                                                        guruh komandir  profilaktika  inspektori                             None                                                                                      хайдовчи ходим                                                                                           сафдор-ходим                                               отряд командирининг хизмат бўйича ўринбосари         туман жамоат хавфсизлиги хизмати бошлиғи                          None                            ppxb isomto’xt otryadi muxandisi                                  оператор                             None   mutaxassis mergan                None            None                 None          None       None           None  oʻttaa xasis ages                  isomtuxt otryadi
7                                                                                 sinspektori                                     профилактика катта инспектори               None    yangi namangan tumani beruniy htm bosh inspektori                       None                            None                       None                       None                                                       mutaxasiss                                                      guruh  kamandiri      profilaktikainspektor                            None                                                                                      хайдовчи ходими                                                                                                 safdor                                     отряд командирининг тарбиявий ишлар бўйича ўринбосари                                   бўлинма бошлиғи                         None                                                    muhandis                       mutaxassis-operator                             None         pulemyotchi                None            None                 None          None       None           None              kkkkl                         isomtuhta
8                                                                               eko inspektor                                      профилактика катта инспектори              None             namangan shaxar lola xtm bosh inspektori                       None                            None                       None                       None                                                      mutaxassis                                                      4-guruh kamandiri                       None                            None                                                                                      хайдовчи  ходим                                                                                                 сафдор                                          батальон командирининг хизмат буйича уринбосари                                      бўлим бошлиғи                         None                 ppx bataloni isomtxt otryad muxandis xodimi                       mutaxassis opirotor                             None   mutahassis mergan                None            None                 None          None       None           None     32509893500073                  kadirlar guruhi
9                                                                                  inbspektor                                                   катта инспектори              None         namangan shahar obihayot htm bosh inspektori                       None                            None                       None                       None                                                       mutahassis                                                       guruh komandiri                       None                            None                                                                                       хайдовчи ходим                                                                                                сафдор                                                               guruh komandiri o'rinbosari                                    aloqa boshlig'i                         None                ppx bataloni isomtxt otryadi muxandis xodimi          suv bilan zarba berish operatori                             None                None                None            None                 None          None       None           None     32904966800012  ppxb xizmat kursatish komindanti
10                                                                                  inspektor  ppx bataloni shtab navbatchilik qismi katta inspеktor navbatchisi              None                                       бош инспектори                       None                            None                       None                       None           namangan viloyati iib jxx jtsb maxsus otryad mutaxasis                                                       guruh kamandiri                       None                            None                                                                                       ҳайдовчи ходим                                                                                             ppx xodimi                                                                      komandir o'rinbosari                    viloyat iib jxx jtsb boshlig'i                         None                                        ppx  katta muxandisi                                      None                             None                None                None            None                 None          None       None           None       94-058-98-00      ppxb hizmatini tashkil etish
11                                                                                  isnpektor                                                                pki              None                                        бош инспектор                       None                            None                       None                       None     namangan viloyati iib jxx jtsb ppxb maxsus otryad mutaxasisi                                                   ppx gurux komandiri                       None                            None                                                                                      xaydovchi hodim                                                                                            ppx xodimi                                                                guruh komandiri oʻrinbosari                            iib boshqarma boshliği                         None                                aloqa guruhi katta muhandisi                                      None                             None                None                None            None                 None          None       None           None          kj.jk.jk.                              None
12                                                                                 inspektori                                                  старший инспектор              None                                    жхх бош инспектор                       None                            None                       None                       None                                             mutaxassis-haydovchi                                                     1-guruh komandiri                       None                            None                                                                                    xaydovchi hodimi                                                                                               ppx xodmi                                                                guruh kamandir urin bosari                               boshqarma boshlig'i                         None                            ppx,atalioni atg katta muxandisi                                      None                             None                None                None            None                 None          None       None           None              raqam                              None
13                                                                                  imspektor                                          хттб ҳпг катта инспектори              None        ахборот технологиялари бўйича бош инспкектори                       None                            None                       None                       None                                              mutaxasis haydovchi                                                   ppx guruh komandiri                       None                            None                                                                                      xaydovchi xodim                                                                                             ppx xodimi                                                               otryad komandiri orinbosari                        иив жтсх ппх бўлим бошлиғи                         None                                               atg muhandisi                                      None                             None                None                None            None                 None          None       None           None       siktirganski                              None
14                                                                                 inspektor.                                           ппхб кг катта инспектори              None                                       bosh inspektor                       None                            None                       None                       None                                             mutaxassis haydovchi                                                            guruh koma                       None                            None                                                                                     haydovchi hodim                                                                                            safdor hodim                                                                      komandir o`rinbosari                             ткд жкх булим бошлиги                         None                                        ппхб катта мухандиси                                      None                             None                None                None            None                 None          None       None           None  98162 harbiy qism                              None

In [ ]:
"bo'linma boshlig'i" and "bo'lim boshlig'i"

In [359]:
posi_data_dict_df.to_excel('e_patrul_posi.xlsx')

In [55]:
posits = pd.read_csv('./ActivityPosition.csv')
posits.tail()

      JQB      9инспектор
1031  PPX             NaN
1032  NaN         Lavozim
1033  NaN           super
1034  NaN  Хизмат бошлиғи
1035  NaN             NaN

In [57]:
df_pos = posits.copy()
df_pos.columns = [f'col_{i}' for i in range(len(df_pos.columns))]
df_pos.head()

  col_0                                                   col_1
0   JQB                                                   ADMIN
1   JQB                                  Bag'dod t 1-o'rinbosar
2   JQB                                 Beshariq t 1-o'rinbosar
3   JQB                                          Bo'lim boshlqi
4   JQB  Bosh prokuraturasi Huquqni muhofaza qilish akademiyasi

In [58]:
most_frequent_column = df_pos.mode().iloc[0]
print(most_frequent_column)

col_0      PPX
col_1    ADMIN
Name: 0, dtype: object

In [63]:
strc_cnts = df_pos['col_0'].value_counts()
strc_cnts

PPX    810
MG     129
PI      51
JQB     42
Name: col_0, dtype: int64

In [64]:
serv_cnts = df_pos['col_1'].value_counts()
serv_cnts

ADMIN                                                                                                    4
Lavozim                                                                                                  4
Inspektor                                                                                                3
инспектор                                                                                                3
Markaz o'rinbosari                                                                                       3
front                                                                                                    3
Katta inspektor                                                                                          3
Haydovchi                                                                                                2
Gurux komandiri                                                                                          2
Guruh komandiri o‘rinbosari                                                                              2
profilaktika Inspektor                                                                                   2
admin                                                                                                    2
Mutahassis                                                                                               2
Guruh komandiri                                                                                          2
Guruh komandir                                                                                           2
Profilaktika katta inspektori                                                                            2
Mutaxassis                                                                                               2
Kichik inspektor                                                                                         2
Boʼlinma boshligʼi                                                                                       2
test                                                                                                     2
mutaxassis                                                                                               2
Guruh komandiri o'rinbosari                                                                              2
Otryad komandiri                                                                                         2
guruh komandiri                                                                                          2
guruh komandiri o'rinbosari                                                                              2
otryad komandiri                                                                                         2
inspektor                                                                                                2
PPXB 2-otryad safdor xodimi                                                                              1
PPXB INSPEKTOR                                                                                           1
PPXB 4-TUMANLARARO OTRYADI BO’LINMA KOMANDIRI                                                            1
PPXB 2-TUMANLARARO OTRYADI BO’LINMA KOMANDIRI                                                            1
PPXB 2-TUMANLARARO OTRYADI BO'LINMA KOMANDIRI                                                            1
PPXB 4-TUMANLARARO OTRYADI INSPEKTORI                                                                    1
PPXB 4-TUMANLARARO OTRYADI KOMANDIRI                                                                     1
PPXB 2-TUMANLARARO OTRYADI  INSPEKTORI                                                                   1
PPXB 4-TUMANLARARO OTRYADI XAYDOVCHI XODIMI                                                              1
PPXB 2-TUMANLARARO OTRYAD KOMANDIRI                                                                      1
PPXB 2-TUMANLARARO OTRYAD INSPEKTORI                                                                     1
PPXB 2-OTRYAD XAYDOVCHI XODIMI                                                                           1
PPXB 2-TUMANLARARO OTRYADI INSPEKTORI                                                                    1
PPXB ISMOTXT OTRYAD KOMANDIRI O'RINBOSARI                                                                1
PPXB ISMOTXT OTRYADI KOMANDIRI                                                                           1
PPXB ISOMTO'XT OTRYADI INSPEKTORI                                                                        1
PPXB ISOMTO'XT otryadi inspektori                                                                        1
PPXB ISOMTO’XT OTRYADI GURUH KOMANDIRI                                                                   1
PPXB ISOMTO’XT OTRYADI GURUH KOMANDIRI O'RINBOSARI                                                       1
PPXB ISOMTO’XT OTRYADI GURUX KOMANDIRI                                                                   1
PPXB 2-OTRYAD SAFDOR XODIMI                                                                              1
PPXB ISOMTO’XT OTRYADI INSPEKTORI                                                                        1
PPXB 2-OTRYAD KOMANDIRI O’RINBOSARI                                                                      1
PPXB ISOMTO’XT OTRYADI MUTAXASSISI                                                                       1
PPXB ISOMTO’XT OTRYADI MUXANDISI                                                                         1
PPXB 4-OTRYADI BO’LINMA KOMANDIRI                                                                        1
PPXB 4-OTRYAD INSPEKTORI                                                                                 1
PPXB 2-TUMANLARARO OTRYADI XAYDOVCHI XODIMI                                                              1
PPXB 4- OTRYAD KOMANDIRINING O'RINBOSARI                                                                 1
PPXB 3- OTRYAD BO’LINMA KOMANDIRI                                                                        1
PPXB 3- OTRYAD INSPEKTORI                                                                                1
PPXB 3- OTRYAD KOMANDIRI                                                                                 1
PPXB 2-otryad safdor xodimi                                                                              1
PPXB 3- OTRYAD KOMANDIRI O’RINBOSARI                                                                     1
PPXB 3- OTRYAD SAFDOR XODIMI                                                                             1
PPXB 3- TUMANLARARO OTRYAD INSPEKTORI                                                                    1
PPXB 2-otryad inspektori                                                                                 1
PPXB 3-OTRYAD  INSPEKTORI                                                                                1
PPXB 2-otryad gurux komandiri                                                                            1
PPXB 3-OTRYAD INSPEKTORI                                                                                 1
PPXB 2-otryad  bo‘linma komandiri                                                                        1
PPXB 3-TUMANLARARO OTRYAD INSPEKTORI                                                                     1
PPXB 3-TUMANLARARO OTRYAD KOMANDIRI                                                                      1
PPXB ISOMTXT otryadi inspektori                                                                          1
PPXB 3-TUMANLARARO OTRYADI BO’LINMA KOMANDIRI                                                            1
PPXB 3-TUMANLARARO OTRYADI BO’LINMA KOMANDIRI                                                            1
PPXB 3-TUMANLARARO OTRYADI INSPEKTORI                                                                    1
PPXB 3-TUMANLARARO OTRYADI KOMANDIRI                                                                     1
PPXB 4- OTRYAD BO’LINMA KOMANDIRI                                                                        1
PPXB 4- OTRYAD INSPEKTORI                                                                                1
PPXB 4- OTRYAD INSPEKTORI SAFDOR                                                                         1
PPXB 4- OTRYAD KOMANDIRI                                                                                 1
PPXB ISOMTO’XT OTRYADI OPERATORI                                                                         1
PPXB komandiri  MTT orinbosari                                                                           1
PPXB MMIB orinbosari                                                                                     1
Viloyat IIB JXX JTSB boshlig'i o'rinbosari                                                               1
Ta'minlash guruhi inspektori                                                                             1
Test JXD                                                                                                 1
Tezkor vakil                                                                                             1
Tuman Jamoat xavfsizligi xizmati boshlig`i                                                               1
Tumanlar aro PPX Inspektori                                                                              1
Tumanlar aro PPX inspektori                                                                              1
Tumanlararo otryad komandiri                                                                             1
Tumanlararo otryad komandiri o'rinbosari                                                                 1
Tumanlararo otryadi komandiri                                                                            1
Tumanlararo safdor xodim                                                                                 1
Uchqurgon tumani  PPX inspektori                                                                         1
Uchtepa tumani                                                                                           1
Viloyat IIB JXX JTSB boshlig'i                                                                           1
Xaydovchi                                                                                                1
Serjant                                                                                                  1
Yakkasaroy tumani JTSB boshlig`i                                                                         1
Yangi Namangan tumani Beruniy HTM bosh inspektori                                                        1
Yangi Namangan tumani Biruniy 2-sonli MFY PPX inspektori                                                 1
Yangi Namangan tumani Bunyodkor HTM bosh inspektori                                                      1
Yangi Namangan tumani Go`zal HTM bosh inspektori                                                         1
Yangi Namangan tumani IIB Guzal MFY XTM PPX inspektori                                                   1
Yangi Namangan tumani IIB JXX JTSB PPX inspektori                                                        1
Yangi Namangan tumani IIB PPX inspektori                                                                 1
Yangi Namangan tumani IIB PPX inspetori                                                                  1
Yangi Namangan tumani Ishonch XTM Bosh inspektori                                                        1
Yangi Namangan tumani PPX Inspektori                                                                     1
Yangi Namangan tumani PPX bulinma komandiri                                                              1
Yangi Namangan tumani PPX inspektori                                                                     1
Suv bilan zarba berish operatori                                                                         1
Sergeli tumani IIO FMB JTSB boshlig’i                                                                    1
PPXB OTLIQ GURUHI KOMANDIRI                                                                              1
PPXG KOMANDIR O'RINBOSARI                                                                                1
PPXB OTLIQ GURUHI SAFDOR XODIMI                                                                          1
PPXB hizmatini tashkil etish                                                                             1
PPXB inspektori                                                                                          1
PPXB katta inspektori                                                                                    1
PPXB 2-OTRYAD INSPEKTORI                                                                                 1
PPXB komandiri o'runbosari                                                                               1
PPXB komandirining o'rinbosari                                                                           1
PPXB navbatchilik qismi                                                                                  1
PPXB navbatchisi                                                                                         1
PPXB otryad komandiri orinbosari                                                                         1
PPXB safdor hodimi                                                                                       1
PPXB xizmat buyicha orinbosari                                                                           1
PPXB xizmat kursatish komindanti                                                                         1
PP{B Ta'minot gurihi                                                                                     1
Safdor xodimi                                                                                            1
Patrul Post Xizmati Inspektori                                                                           1
Patrul-post xizmati inspеktori                                                                           1
Pd  phvPX ее                                                                                             1
Podpolkovnik PPX bataloni komandiri o‘rinbosari                                                          1
Qashqadaryo viloyati, IIB PPXB inspektori                                                                1
RANK                                                                                                     1
SAFDOR                                                                                                   1
SAFDOR HODIM                                                                                             1
SAFDOR HODIM                                                                                             1
SAFDOR XODIM                                                                                             1
Safdor                                                                                                   1
Safdor PPX bataloni birinchi otryadi bulinma komandiri                                                   1
Safdor xodim                                                                                             1
PPXB 2-OTRYAD KOMANDIRI                                                                                  1
PPXB 1-OTRYAD INSPEKTORI                                                                                 1
PPXB 2-OTRYAD BO’LINMA KOMANDIRI                                                                         1
PPX INSPEKTOR                                                                                            1
PPX INSPEKTORI                                                                                           1
PPX INSPEKTORT                                                                                           1
PPX INSPEKTPRI                                                                                           1
PPX INSPEKTRI                                                                                            1
PPX INSPEKTRO                                                                                            1
PPX INSPEK|TORI                                                                                          1
PPX INSPELTOR                                                                                            1
PPX INspektori                                                                                           1
PPX ISOTOXTO  inspektori                                                                                 1
PPX Inaspektori                                                                                          1
PPX Inispektori                                                                                          1
PPX Inspector                                                                                            1
PPX Inspektor                                                                                            1
PPX Inspektori                                                                                           1
PPX Inspektr                                                                                             1
PPX OTUQTO gurux kom                                                                                     1
PPX bataloni  ISOMTXT otryadi komandiri o‘rinbosari                                                      1
PPX bataloni 1-otryad inspektori                                                                         1
PPX bataloni 1-otryad otryadi safdor xodimi                                                              1
PPX bataloni 1-otryad otryadi safdor-xodimi                                                              1
PPX bataloni ISOMTXT otryad Muxandis xodimi                                                              1
PPX bataloni ISOMTXT otryad mutaxasis xodimi                                                             1
PPX bataloni ISOMTXT otryadi                                                                             1
PPX bataloni ISOMTXT otryadi Muxandis xodimi                                                             1
PPX bataloni ISOMTXT otryadi gurux  komandiri                                                            1
PPX bataloni ISOMTXT otryadi gurux komandiri o‘rinbosari                                                 1
PPX bataloni ISOMTXT otryadi mutaxasis xodimi                                                            1
PPX INSPEKTORI                                                                                           1
PPX INSPEKTOR                                                                                            1
PPX bataloni ISOMTXT otryadi safdor xodimi                                                               1
PPX INSPEKT                                                                                              1
Otr kom o'rinbosari                                                                                      1
Otryad komandir o'rinbosari                                                                              1
Otryad komandiri o'rinbosari                                                                             1
Otryad komandiri o`rinbosari                                                                             1
Otryad komandiri orinbosari                                                                              1
Otryad komandirining o'rinbosari                                                                         1
P I inspektori                                                                                           1
PPX                                                                                                      1

In [75]:
pos_inds = pd.Series(serv_cnts.index)
norm_pos_inds = pos_inds.str.upper()
# Normalize names
s_pos_normalized = norm_pos_inds.apply(unidecode)

# Group similar names
similar_pos_names = group_similar(s_pos_normalized)

print(similar_pos_names)

{'ADMIN': ['ADMIN'], 'LAVOZIM': ['LAVOZIM'], 'INSPEKTOR': ['INSPKETOR', 'INSPEKTOR', 'PPX INSPEKTOR', 'INPEKTOR', 'SINSPEKTORI', 'INSPEKTORI', ' INSPEKTORI ', 'INSPKTOR', 'INISPEKTOR', 'IMSPEKTOR', 'INSPECTOR', 'NSPEKTOR', 'EKO INSPEKTOR', 'INSPEKITOR', 'ISNPEKTOR', 'ISPEKTOR', 'INSPEKOR', 'INSAPEKTOR', 'INSPEKIOR', 'INSPETOR', 'INSPEKTORI ', ' INSPEKTORI', 'INBSPEKTOR', ' INSPEKTOR', 'INSPEKTOR ', 'MTB INSPEKTOR', 'INSPEKTOR.'], "MARKAZ O'RINBOSARI": ["MARKAZ O'RINBOSARI"], 'FRONT': ['FRONT'], 'KATTA INSPEKTOR': ['KATTA INSPEKTOR', 'JTSB KATTA INSPEKTORI', ' INSPEKTOR', 'JTSG KATTA INSPEKTORI', 'KADR INSPEKTORI', 'KATTA INSPEKTORI', 'PPXB KATTA INSPEKTORI'], 'HAYDOVCHI': ['HAYDOVCHI ', 'HAYDOVCHI', 'HAYDOVCHISI', 'XAYDOVCHI'], 'GURUX KOMANDIRI': ['3-GURUX KOMANDIRI', 'GURUH  KOMANDIRI', 'GURUH KAMANDIRI', "GURUKh' KOMANDIRI", 'PPX GURUX KOMANDIRI', 'GURUH KOMANDIRI', 'GURUX KOMANDIRI ', 'GURUKh KOMANDIRI', 'PPX GURUH KOMANDIRI', 'GURUX KOMANDIRI', '4-GURUH KAMANDIRI', 'GURUKh KOMANDIRI ', 'GURUH KOMANDIR', 'GURUH KOMANDIRI ', 'GURUKh KAMANDIRI', '3-GURUH KOMANDIRI', '1-GURUX KOMANDIRI', 'GURUH  KAMANDIRI', 'GURUX KAMANDIRI', '2-GURUX KOMANDIRI', '2- GURUX KOMANDIRI', '1-GURUH KOMANDIRI'], "GURUH KOMANDIRI O'RINBOSARI": ['KOMANDIR O`RINBOSARI', "OTRYAD KOMANDIRI O'RINBOSARI", 'GURUKh KOMANDIRI URINBOSARI', "GURUH KOMANDIRI O'RINBOSARI", "OTRYAD KOMANDIR O'RINBOSARI", "GURUH KOMANDIRI O'RINBOSARI ", "GURUH KOMANDIR O'RINBOSARI", 'GURUH KAMANDIR URIN BOSARI', "PPXG KOMANDIR O'RINBOSARI", "KOMANDIR O'RINBOSARI", "GURUH KOMANDIRI OR'INBOSARI", 'OTRYAD KOMANDIRI ORINBOSARI', ' KOMANDIRI URINBOSARI', 'GURUH KOMANDIRI O`RINBOSARI', 'OTRYAD KOMANDIRI O`RINBOSARI'], 'PROFILAKTIKA INSPEKTOR': ['PROFILAKTIKA  INSPEKTORI', 'PROFILAKTIKA INSPECTOR', 'PROFILAKTIKA INSPEKTORI', 'PROFILAKTIKA  KATTA INSPEKTORI', 'PROFILAKTIKA INSPEKTOR', 'PROFILAKTIKA INSPEKTOR ', 'PROFILAKTIKA  INSPEKTORI ', 'PROFILAKTIKA KATTA INSPEKTORI', 'PROFILAKTIKA KATTA ISPEKTOR', 'PROFILAKTIKA KATTA INSPEKTOR', 'PROFILAKTIKAINSPEKTOR', 'PROFILAKTIKA INSPEKTORI ', 'PROFILAKTIKA KATTA INSPEKTORI '], 'MUTAHASSIS': ['MUTAHASSIS ', 'MUTAXASIS', 'MUTAKhASSIS', 'MUTAHASSIS', 'MUTAHASIS', 'MUTAXASSISI', 'MUTAXASSIS ', 'MUTAXASIS ', 'MUTAXASISS', 'MUTAXASSIS  ', 'MUTAXASSIS'], 'KICHIK INSPEKTOR': ['KICHIK INSPEKTOR'], "BO'LINMA BOSHLIG'I": ["BULINMA BOShLIG'I", "BO'LIM BOSHLIG'I", "BO'LINMA BOSHLIG'I", "BO'LIM BOSHLIGI", "BO'LIM BOSHLQI"], 'TEST': ['TEST', 'TESTER'], 'OTRYAD KOMANDIRI': ['PPX OTRYAD KOMANDIRI', 'OTRIAT KOMANDIRI', 'PPXB 4- OTRYAD KOMANDIRI', 'OTRYAD KAMANDIRI', 'OTYAD KOMANDIRI', 'ISMOTXT OTRYAD KOMANDIRI', '1-OTRYAD KOMANDIRI', 'OTRYAD KOMANDIRI', '2-OTRYAD KOMANDIRI ', 'OTRIaD KOMANDIRI', '2-OTRYAD KOMANDIRI', 'OTRYAD KOMANDIRI ', 'OTRYD KAMANDIRI', '1-OTRYAD GURUX KOMANDIRI', 'PPXB 3- OTRYAD KOMANDIRI', 'PPXB 2-OTRYAD KOMANDIRI', 'OTIRYAD KOMANDIRI', 'PPXB 1-OTRYAD KOMANDIRI'], 'PPXB 2-OTRYAD SAFDOR XODIMI ': ['PPXB 2-OTRYAD XAYDOVCHI XODIMI', 'PPXB 3- OTRYAD SAFDOR XODIMI', 'PPXB 1-OTRYAD SAFDOR XODIMI', 'PPXB 2-OTRYAD SAFDOR XODIMI ', 'PPXB 2-OTRYAD SAFDOR XODIMI'], 'PPXB INSPEKTOR': ['PPKh INSPREKTOR ', 'PPX INSPEKTRO', 'PPX ONSPEKTORI', 'PPX INSPEKTOR', 'PPX INSPTKTORI', 'PPX INPEKTRO', 'PPX INASPEKTORI', 'PPKh INSPEKTOR', 'PPX IBSPEKTORI', 'MPPX INSPEKTORI', 'PPX INSPEKTORT', 'PPX  INSPEKTORI', 'MPPX INSPEKTORI ', 'PPX INSPEKRORI', 'PPXB INSPEKTORI', 'PPX INSPEKTORI', 'PPX INSPEKTRORI ', 'XOB INPEKTORI', 'PPKh  INSPEKTORI', 'MPPXO INSPEKTORI ', 'PPX INSPEKTRI', 'PPX INPEKTORI', 'PPX INSPEKTRORI', 'PPX INSPRKTORI', 'PPX INSPEK', 'PPX  INSPEKTORI ', 'PPX INSPEKT', 'PPX INISPEKTORI', 'PPX INSPEKTPRI', ' PPX INSPEKTORI ', 'PPKh INSPEKTORI', 'PPX INSPECTOR', 'PPXB INSPEKTOR', 'PPX INSPELTOR', 'PPKh  INSPEKTOR', 'PPX< INSPEKTORI', 'PPX INSPETKTORI', ' PPX INSPEKTORI', 'PPX INSPEKTOR ', 'PPX INSPEKTORI ', 'PPXB KATTA INSPEKTORI', 'PPX INPEKTOR', 'PPKh INSPEKTORI ', 'MPPXO INSPEKTORI', ' INSPEKTORI', 'PPX ISNPEKTORI', 'MPPX INSOEKTORI', ' INSPEKTOR', 'PPX INSPEK|TORI', 'PPX INSPERKTOR', 'PPX IINSPEKTORI', 'PPX INSPEKTR', ' PPX INSPEKTOR', 'MTB INSPEKTOR'], "PPXB 4-TUMANLARARO OTRYADI BO'LINMA KOMANDIRI": ["PPXB 3-TUMANLARARO OTRYADI BO'LINMA KOMANDIRI", 'PPXB 4-TUMANLARARO OTRYADI INSPEKTORI', "PPXB 4-OTRYADI BO'LINMA KOMANDIRI", 'PPXB 3-TUMANLARARO OTRYAD KOMANDIRI', "PPXB 1-TUMANLARARO OTRYADI BO'LINMA KOMANDIRI", "PPXB 4- OTRYAD BO'LINMA KOMANDIRI", 'PPXB 2-TUMANLARARO OTRYAD KOMANDIRI', "PPXB 1-OTRYAD BO'LINMA KOMANDIRI", 'PPXB 1-TUMANLARARO OTRYADI KOMANDIRI', "PPXB 2-OTRYAD BO'LINMA KOMANDIRI", "PPXB 3- OTRYAD BO'LINMA KOMANDIRI", "PPXB 3-TUMANLARARO OTRYADI BO'LINMA KOMANDIRI ", "PPXB 4-TUMANLARARO OTRYADI BO'LINMA KOMANDIRI", "PPXB 2-TUMANLARARO OTRYADI BO'LINMA KOMANDIRI", 'PPXB 4-TUMANLARARO OTRYADI KOMANDIRI', 'PPXB 3-TUMANLARARO OTRYADI KOMANDIRI'], 'PPXB 2-TUMANLARARO OTRYADI  INSPEKTORI': ['PPXB 3- TUMANLARARO OTRYAD INSPEKTORI', 'PPXB 2-TUMANLARARO OTRYADI INSPEKTORI', 'PPXB 4-TUMANLARARO OTRYADI INSPEKTORI', '4-TUMANLARARO OTRYADI INSPEKTORI', 'PPXB 3-TUMANLARARO OTRYAD INSPEKTORI', 'PPXB 1-TUMANLARARO OTRYADI INSPEKTORI', 'PPXB 2-TUMANLARARO OTRYADI  INSPEKTORI', 'PPXB 3-TUMANLARARO OTRYADI INSPEKTORI', "PPXB 2-TUMANLARARO OTRYADI BO'LINMA KOMANDIRI", 'PPXB 2-TUMANLARARO OTRYAD INSPEKTORI'], 'PPXB 4-TUMANLARARO OTRYADI XAYDOVCHI XODIMI': ['PPXB 4-TUMANLARARO OTRYADI XAYDOVCHI XODIMI', 'PPXB 2-TUMANLARARO OTRYADI XAYDOVCHI XODIMI'], "PPXB ISMOTXT OTRYAD KOMANDIRI O'RINBOSARI": [" 4-OTRYAD KOMANDIRI O'RINBOSARI", "PPXB ISMOTXT OTRYAD KOMANDIRI O'RINBOSARI", "OTRYAD KOMANDIRI O'RINBOSARI", "PPXB 1-OTRYAD KOMANDIRI O'RINBOSARI", "PPXB 4- OTRYAD KOMANDIRINING O'RINBOSARI", 'PPXB OTRYAD KOMANDIRI ORINBOSARI', "PPXB ISOMTO'XT OTRYADI GURUH KOMANDIRI O'RINBOSARI", "PPX OTRYAD  KOMANDIRI O'RINBOSARI", "PPXB 3- OTRYAD KOMANDIRI O'RINBOSARI", "IOTXT OTRYAD KOMANDIRI O'RINBOSARI", "PPXB 2-OTRYAD KOMANDIRI O'RINBOSARI", "PPX BATALONI ISOMTXT OTRYADI GURUX KOMANDIRI O'RINBOSARI", "PPX BATALONI  ISOMTXT OTRYADI KOMANDIRI O'RINBOSARI", 'PPXB ISMOTXT OTRYADI KOMANDIRI', "ISMOTXT OTRYAD KOMANDIRI O'RINBOSARI", '1 OTRYAD KOMANDIRI ORINBOSARI'], "PPXB ISOMTO'XT OTRYADI INSPEKTORI": ['PPX ISOTOXTO  INSPEKTORI', "PPXB ISOMTO'XT OTRYADI INSPEKTORI", "PPXB ISOMTO'XT OTRYADI MUXANDISI", "PPXB ISOMTO'XT OTRYADI OPERATORI", 'PPXB ISOMTXT OTRYADI INSPEKTORI'], "PPXB ISOMTO'XT OTRYADI GURUH KOMANDIRI": ["PPXB ISOMTO'XT OTRYADI MUXANDISI", "PPXB ISOMTO'XT OTRYADI GURUH KOMANDIRI O'RINBOSARI", 'PPX BATALONI ISOMTXT OTRYADI GURUX  KOMANDIRI', "PPXB ISOMTO'XT OTRYADI GURUX KOMANDIRI", "PPXB ISOMTO'XT OTRYADI GURUH KOMANDIRI", 'PPXB ISMOTXT OTRYADI KOMANDIRI'], "PPXB ISOMTO'XT OTRYADI MUTAXASSISI": ["PPXB ISOMTO'XT OTRYADI MUXANDISI", "PPXB ISOMTO'XT OTRYADI MUTAXASSISI"], 'PPXB 4-OTRYAD INSPEKTORI': ['PPXB 3-OTRYAD  INSPEKTORI', 'PPXB 1-OTRYAD INSPEKTOR', 'PPXB 2- OTRYAD INSPEKTORI', 'PPXB 1-OTRYAD INISPEKTORI', 'PPXB 1-OTRYAD INISPEKTORI ', 'PPXB 4- OTRYAD INSPEKTORI SAFDOR', 'PPXB 4- OTRYAD INSPEKTORI', 'PPXB 1-OTRYAD INSPEKTORI', 'PPX 1-OTRYAD INSPEKTORI', 'PPXB 4-OTRYAD INSPEKTORI', '1-OTRYAD INSPEKTORI ', 'PPXB 3- OTRYAD INSPEKTORI', 'PPXB 3-OTRYAD INSPEKTORI', 'PPX BATALONI 1-OTRYAD INSPEKTORI', 'PPXB ISOMTXT OTRYADI INSPEKTORI', '2-OTRYAD INSPEKTORI', 'PPXB 2-OTRYAD INSPEKTORI', 'PPXB KATTA INSPEKTORI'], 'PPXB 2-OTRYAD GURUX KOMANDIRI': ['PPX OTRYAD KOMANDIRI', 'PPXB 4- OTRYAD KOMANDIRI', '1-OTRYAD GURUX KOMANDIRI', 'PPXB 3- OTRYAD KOMANDIRI', 'PPXB 2-OTRYAD KOMANDIRI', "PPXB ISOMTO'XT OTRYADI GURUX KOMANDIRI", 'MPPX 2-OTRYAD GURUX KOMANDIRI', 'PPXB 1-OTRYAD KOMANDIRI', 'PPXB 2-OTRYAD GURUX KOMANDIRI'], "PPXB 2-OTRYAD  BO'LINMA KOMANDIRI ": ["PPXB 2-OTRYAD  BO'LINMA KOMANDIRI ", "PPXB 4-OTRYADI BO'LINMA KOMANDIRI", "PPXB 4- OTRYAD BO'LINMA KOMANDIRI", "PPXB 1-OTRYAD BO'LINMA KOMANDIRI", "PPXB 2-OTRYAD BO'LINMA KOMANDIRI", "PPX 2-OTRYAD BO'LINMA KOMADIRI", "PPXB 3- OTRYAD BO'LINMA KOMANDIRI", "PPXB 3-TUMANLARARO OTRYADI BO'LINMA KOMANDIRI ", "PPX 2-OTRYAD BO'LINMA KOMANDIRI", 'PPXB 2-OTRYAD KOMANDIRI', "MPPX 3-OTRYAD BO'LINMA KOMANDIRI", "PPXB 2-TUMANLARARO OTRYADI BO'LINMA KOMANDIRI", "PPX 1-OTRYAD BO'LINMA KOMANDIRI", "2-OTRYAD BO'LINMA KAMANDIRI"], 'PPXB KOMANDIRI  MTT ORINBOSARI': ['PPXB KOMANDIRI  MTT ORINBOSARI', 'PPKhB KOMANDIRINING MTTB URINBOSARI', 'PPXB OTRYAD KOMANDIRI ORINBOSARI', "PPXG KOMANDIR O'RINBOSARI", "PPXB KOMANDIRINING O'RINBOSARI", "PPXB KOMANDIRI O'RUNBOSARI"], 'PPXB MMIB ORINBOSARI': ['PPXB MMIB ORINBOSARI'], "VILOYAT IIB JXX JTSB BOSHLIG'I O'RINBOSARI": ["VILOYAT IIB JXX JTSB BOSHLIG'I O'RINBOSARI", "VILOYAT IIB JXX JTSB BOSHLIG'I", "IIB JXX JTSB BOSHLIG'INING O'RINBOSARI"], "TA'MINLASH GURUHI INSPEKTORI": ["TA'MINLASH GURUHI INSPEKTORI"], 'TEST JXD': ['TEST JXD'], 'TEZKOR VAKIL': ['UMIB TEZKOR VAKIL', 'TEZKOR VAKIL', 'KATTA TEZKOR VAKIL'], 'TUMAN JAMOAT XAVFSIZLIGI XIZMATI BOSHLIG`I': ["TUMAN ZhAMOAT KhAVFSIZLIGI KhIZMATI BOShLIG'I ", 'TUMAN JAMOAT XAVFSIZLIGI XIZMATI BOSHLIG`I', "TUMAN ZhAMOAT KhAVFSIZLIGI KhIZMATI BOShLIG'I"], 'TUMANLAR ARO PPX INSPEKTORI': ['2-TUMANLARARO INSPEKTORI', 'TUMANLAR ARO PPX INSPEKTORI', '1-TUMANLARARO INSPEKTORI', '1-TUMANLARARO PPX INSPEKTORI', '2-TUMANLARARO PPXG INSPEKTORI'], 'TUMANLARARO OTRYAD KOMANDIRI': ["TUMANLARARO OTRYAD KOMANDIRI O'RINBOSARI", 'PPXB 3-TUMANLARARO OTRYAD KOMANDIRI', 'TUMANLARARO OTRYAD KOMANDIRI ', 'PPXB 2-TUMANLARARO OTRYAD KOMANDIRI', 'PPXB 1-TUMANLARARO OTRYADI KOMANDIRI', 'TUMANLARARO OTRYADI KOMANDIRI', 'TUMANLARARO OTRYAD KOMANDIRI', 'PPXB 4-TUMANLARARO OTRYADI KOMANDIRI', 'PPXB 3-TUMANLARARO OTRYADI KOMANDIRI'], 'TUMANLARARO SAFDOR XODIM': ['TUMANLARARO SAFDOR XODIM'], 'UCHQURGON TUMANI  PPX INSPEKTORI  ': ['UCHQURGON TUMANI  PPX INSPEKTORI  '], 'UCHTEPA TUMANI': ['UCHTEPA TUMANI'], 'SERJANT': ['SERJANT', 'SERZhANT'], 'YAKKASAROY TUMANI JTSB BOSHLIG`I': ['YAKKASAROY TUMANI JTSB BOSHLIG`I'], 'YANGI NAMANGAN TUMANI BERUNIY HTM BOSH INSPEKTORI': ['YANGI NAMANGAN TUMANI BUNYODKOR HTM BOSH INSPEKTORI', 'YANGI NAMANGAN TUMANI GO`ZAL HTM BOSH INSPEKTORI', 'YANGI NAMANGAN TUMANI BERUNIY HTM BOSH INSPEKTORI', 'YANGI NAMANGAN TUMANI HTM INSPEKTORI', 'YANGI NAMANGAN TUMANI ISHONCH XTM BOSH INSPEKTORI'], 'YANGI NAMANGAN TUMANI BIRUNIY 2-SONLI MFY PPX INSPEKTORI ': ['YANGI NAMANGAN TUMANI BIRUNIY 2-SONLI MFY PPX INSPEKTORI '], 'YANGI NAMANGAN TUMANI IIB GUZAL MFY XTM PPX INSPEKTORI': ['YANGI NAMANGAN TUMANI GO`ZAL HTM BOSH INSPEKTORI', 'YANGINAMANGAN TUMANI IIB PPX 3-SONLI GOZAL MFY HTM INSPEKTORI', 'YANGI NAMANGAN TUMANI IIB GUZAL MFY XTM PPX INSPEKTORI', 'YANGI NAMANGAN TUMANI BIRUNIY 2-SONLI MFY PPX INSPEKTORI ', 'YANGI NAMANGAN TUMANI IIB JXX JTSB PPX INSPEKTORI', 'YANGI NAMANGAN TUMANI IIB PPX INSPETORI', 'YANGI NAMANGAN TUMANI PPX INSPEKTORI', 'YANGI NAMANGAN TUMANI IIB PPX INSPEKTORI'], 'YANGI NAMANGAN TUMANI PPX BULINMA KOMANDIRI': ['YANGI NAMANGAN TUMANI PPXB INSPEKTORI', 'YANGI NAMANGAN TUMANI PPX BULINMA KOMANDIRI', 'YANGI NAMANGAN TUMANI PPX INSPEKTORI ', 'YANGI NAMANGAN TUMANI PPX INSPEKTORI'], 'SUV BILAN ZARBA BERISH OPERATORI': ["SUV BILAN ZARBA BERISh GURUKh'I OPERATORI", 'SUV BILAN ZARBA BERISH OPERATORI', " SUV BILAN ZARBA BERISh GURUKh'I OPERATORI "], "SERGELI TUMANI IIO FMB JTSB BOSHLIG'I  ": ["YUNUSOBOD TUMANI IIO FMB JTSB BOSHLIG'I  ", "BEKTEMIR TUMANI IIO FMB JTSB BOSHLIG'I  ", "M.ULUG`BEK  TUMANI IIO FMB JTSB BOSHLIG'I  ", "OLMAZOR  TUMANI IIO FMB JTSB BOSHLIG'I  ", "SERGELI TUMANI IIO FMB JTSB BOSHLIG'I  "], 'PPXB OTLIQ GURUHI KOMANDIRI': ['PPXB OTLIQ GURUHI KOMANDIRI', 'PPX GURUH KOMANDIRI'], 'PPXB OTLIQ GURUHI SAFDOR XODIMI': ['PPXB OTLIQ GURUHI SAFDOR XODIMI'], 'PPXB HIZMATINI TASHKIL ETISH': ['PPXB HIZMATINI TASHKIL ETISH'], 'PPXB NAVBATCHILIK QISMI': ['PPXB NAVBATCHILIK QISMI'], 'PPXB NAVBATCHISI': ['PPXB NAVBATCHILIK QISMI', 'PPXB NAVBATCHISI'], 'PPXB SAFDOR HODIMI': ['SAFDOR HODIM', 'PPXB SAFDOR HODIMI', 'SAFDOR HODIMI'], 'PPXB XIZMAT BUYICHA ORINBOSARI': ['PPXB XIZMAT BUYICHA ORINBOSARI'], 'PPXB XIZMAT KURSATISH KOMINDANTI': ['PPXB XIZMAT KURSATISH KOMINDANTI'], "PP{B TA'MINOT GURIHI": ["PP{B TA'MINOT GURIHI"], 'SAFDOR XODIMI': ['SAFDOR XODIM', 'SAFDOR XODIMI ', 'SAFDOR HODIMI', 'SAFDOR-XODIM', 'SAFDOR KhODIM', 'SADOR KhODIM', 'SAFDOR XODIMI', 'SAFDOR KhODIMI', 'SAFDOR HODIM ', 'SAFDOR HODIM', 'SAFDOR KhODIM '], 'PATRUL POST XIZMATI INSPEKTORI': ['PATRUL-POST XIZMATI INSPEKTORI', 'PATRUL POST XIZMATI INSPEKTORI'], 'PD  PHVPX EE': ['PD  PHVPX EE'], "PODPOLKOVNIK PPX BATALONI KOMANDIRI O'RINBOSARI": ["PODPOLKOVNIK PPX BATALONI KOMANDIRI O'RINBOSARI"], 'QASHQADARYO VILOYATI, IIB PPXB INSPEKTORI': ['QASHQADARYO VILOYATI, IIB PPXB INSPEKTORI'], 'RANK': ['RANK'], 'SAFDOR': ['SAFDOR ', 'SAFDOR'], 'SAFDOR PPX BATALONI BIRINCHI OTRYADI BULINMA KOMANDIRI': ["PPX BATALONI BIRINCHI OTRYADI BO'LINMA KOMANDIRI", 'SAFDOR PPX BATALONI BIRINCHI OTRYADI BULINMA KOMANDIRI', 'PPX BATALONI BIRINCHI OTRYADI KOMANDIRI'], 'PPX OTUQTO GURUX KOM': ['PPX OTUQTO GURUX KOM'], 'PPX BATALONI 1-OTRYAD OTRYADI SAFDOR XODIMI': ['PPX BATALONI BIRINCHI OTRYADI SAFDOR-XODIMI', 'PPX BATALONI ISOMTXT OTRYADI SAFDOR-XODIMI', 'PPX BATALONI BIRINCHI OTRYADI SAFDOR XODIMI', 'PPX BATALONI 1-OTRYAD OTRYADI SAFDOR-XODIMI', 'PPX BATALONI ISOMTXT OTRYADI SAFDOR XODIMI', 'PPX BATALONI 1-OTRYAD OTRYADI SAFDOR XODIMI'], 'PPX BATALONI ISOMTXT OTRYAD MUXANDIS XODIMI': ['PPX BATALONI ISOMTXT OTRYAD MUTAXASIS XODIMI', 'PPX BATALONI ISOMTXT OTRYADI SAFDOR-XODIMI', 'PPX BATALONI ISOMTXT OTRYADI MUTAXASIS XODIMI', 'PPX BATALONI ISOMTXT OTRYADI MUXANDIS XODIMI', 'PPX BATALONI ISOMTXT OTRYAD MUXANDIS XODIMI', 'PPX BATALONI ISOMTXT OTRYADI GURUX  KOMANDIRI', 'PPX BATALONI ISOMTXT OTRYADI SAFDOR XODIMI'], 'PPX BATALONI ISOMTXT OTRYADI ': ['PPX BATALONI ISOMTXT OTRYADI ', 'PPX BATALONI ISOMTXT OTRYADI SAFDOR XODIMI', 'PPX BATALONI ISOMTXT OTRYAD MUXANDIS XODIMI', 'PPX BATALONI ISOMTXT OTRYADI SAFDOR-XODIMI'], "OTR KOM O'RINBOSARI": ["OTRYAD KOMANDIRI O'RINBOSARI", "OTR KOM O'RINBOSARI", "OTRYAD KOMANDIR O'RINBOSARI"], "OTRYAD KOMANDIRINING O'RINBOSARI": ["OTRYAD KOMANDIR O'RINBOSARI", "BATALON KOMANDIRINING O'RINBOSARI", "PPXB 2-OTRYAD KOMANDIRI O'RINBOSARI", "1-OTRYAD KOMANDIRINING O'RINBOSARI", "OTRYAD KOMANDIRINING O'RINBOSARI", "ISMOTXT OTRYAD KOMANDIRI O'RINBOSARI", "PPXB 4- OTRYAD KOMANDIRINING O'RINBOSARI", 'BATALYON KOMANDIRINING ORINBOSARI', 'PPXB OTRYAD KOMANDIRI ORINBOSARI', 'OTRYAD KOMANDIRI ORINBOSARI', "BATALYON KOMANDIRINING O'RINBOSARI", "PPX OTRYAD  KOMANDIRI O'RINBOSARI", "IOTXT OTRYAD KOMANDIRI O'RINBOSARI", 'OTRIaD KOMANDIRI URINBOSARI', "PPXB KOMANDIRINING O'RINBOSARI", '1 OTRYAD KOMANDIRI ORINBOSARI', "2-OTRYAD KOMANDIR O'RINBOSARI", " 4-OTRYAD KOMANDIRI O'RINBOSARI", "OTRYAD KOMANDIRI O'RINBOSARI", "PPXB 3- OTRYAD KOMANDIRI O'RINBOSARI", "OTRYAD KOMANDIRININGO'RINBOSARI", "PPXB 1-OTRYAD KOMANDIRI O'RINBOSARI", 'OTRYAD KOMANDIRI O`RINBOSARI'], 'P I INSPEKTORI': ['PPX INSPEKTOR', 'PPX INASPEKTORI', 'SINSPEKTORI', 'INSPEKTORI', ' INSPEKTORI ', 'MPPX INSPEKTORI', 'PPX  INSPEKTORI', 'MPPX INSPEKTORI ', 'PPXB INSPEKTORI', 'PPX INSPEKTORI', 'PPX INSPEKTRORI ', 'PPKh  INSPEKTORI', 'P I INSPEKTORI', 'PPX INSPEKTRI', 'PPX INPEKTORI', 'PPX INSPEKTRORI', 'PPX  INSPEKTORI ', 'PPX INISPEKTORI', ' PPX INSPEKTORI ', 'PPKh INSPEKTORI', 'PPKh  INSPEKTOR', 'PPX< INSPEKTORI', 'PPX INSPETKTORI', ' PPX INSPEKTORI', 'PPX INSPEKTORI ', 'PPKh INSPEKTORI ', 'MPPXO INSPEKTORI', 'INSPEKTORI ', ' INSPEKTORI', ' INSPEKTOR', 'PPX INSPEK|TORI', 'PPX IINSPEKTORI'], 'PPX': ['PPXB', 'PPX'], 'PPX  KATTA MUXANDISI': ['PPX  KATTA MUXANDISI'], 'PPX BRIGADASI': ['PPX BRIGADASI ', 'PPX BRIGADASI'], "PPX BO'LINMA KOMANDIRI": ["PPXB 4-OTRYADI BO'LINMA KOMANDIRI", 'BULINMA KOMANDIRI', "BO'LINMA KAMANDIRI", "PPXB 4- OTRYAD BO'LINMA KOMANDIRI", "PPXB 1-OTRYAD BO'LINMA KOMANDIRI", "BO'LINMA KOMANDIRI", 'BOLINMA KOMANDIRI', "PPXB 2-OTRYAD BO'LINMA KOMANDIRI", "PPX 2-OTRYAD BO'LINMA KOMADIRI", "PPXB 3- OTRYAD BO'LINMA KOMANDIRI", "PPX BO'LINMA KOMANDIRI", "PPX 2-OTRYAD BO'LINMA KOMANDIRI", "MPPX 3-OTRYAD BO'LINMA KOMANDIRI", "PPX 1-OTRYAD BO'LINMA KOMANDIRI", 'BO`LINMA KOMANDIRI', "BO'LINMA KOMANDIRI "], 'PPX INS': ['PPX INSPEK', 'PPX INSP', 'PPX INF', 'PPX INS', 'PPX INS '], "PPX KOMANDIRINING MTT BO'YICHA O'RINBOSARI": ["PPX KOMANDIRINING MTT BO'YICHA O'RINBOSARI", "PPXB KOMANDIRINING O'RINBOSARI", "BATALION KOMANDIRINING XIZMAT BO'YICHA O'RINBOSARI", "PPX BATALONI KOMANDIRI MTT BO'YICHA URINBOSARI", "BATALON KOMANDIRINING XIZMAT BO'YICHA O'RINBOSARI"], 'PPX OPERATOR': ['PPX OPERATOR', 'OPERATOR'], 'PPX OTR KOM URIN': ['PPX OTR KOM URIN'], 'PPX TUMAN INSP': ['PPX TUMAN INSP'], 'PPX XODIMI': ['PPX XODIMI', 'PPX XODIMI ', 'PPX XODMI', ' PPX XODIMI'], 'PPX,ATALIONI ATG KATTA MUXANDISI': ['PPX,ATALIONI ATG KATTA MUXANDISI'], 'PPXB 1- OTRYAD INSPEKTORI SAFDOR XODIMI': ['PPXB 3- OTRYAD SAFDOR XODIMI', 'PPXB 1-OTRYAD SAFDOR XODIMI', 'PPXB 4- OTRYAD INSPEKTORI SAFDOR', 'PPXB 1- OTRYAD INSPEKTORI SAFDOR XODIMI'], 'YANGI NAMANGAN TUMANI PPX INSPEKTORI  ': ['YANGI NAMANGAN TUMANI PPX INSPEKTORI  ', 'YANGI NAMANGAN TUMANI PPXB INSPEKTORI', 'YANGI NAMANGAN TUMANI PPX INSPEKTORI ', ' YANGI NAMANGAN TUMANI PPXB INSPEKTOR', 'YANGI NAMANGAN TUMANI PPXB INSPEKTORI ', 'YANGI NAMANGAN TUMANI IIB PPX INSPETORI', 'YANGI NAMANGAN TUMANI IIB JXX JTSB PPX INSPEKTORI', 'YANGI NAMANGAN TUMANI HTM INSPEKTORI', 'YANGI NAMANGAN TUMANI PPX INSPEKTORI', 'YANGI NAMANGAN TUMANI IIB PPX INSPEKTORI'], 'PPXB 1-OTRYAD XAYDOVCHI XODIMI': ['PPXB 1-OTRYAD XAYDOVCHI XODIMI', 'PPXB 2-OTRYAD XAYDOVCHI XODIMI', 'PPXB 2-OTRYAD SAFDOR XODIMI', 'PPXB 1-OTRYAD SAFDOR XODIMI'], 'PPX BATALONI ISOMTXT OTRYADI SUV BILAN ZARBA BERISH GURUHI KOMANDIRI': ['PPX BATALONI ISOMTXT OTRYADI SUV BILAN ZARBA BERISH GURUHI KOMANDIRI'], 'PPX BATALONI ISOMTXTO HAYDOVCHI-XODIMI': ['PPX BATALONI ISOMTXT OTRYADI SAFDOR-XODIMI', 'PPX BATALONI ISOMTXTO HAYDOVCHI-XODIMI'], 'PPX BATALONI SHTAB NAVBATCHILIK QISMI KATTA INSPEKTOR NAVBATCHISI': ['PPX BATALONI SHTAB NAVBATCHILIK QISMI KATTA INSPEKTOR NAVBATCHISI'], 'PPX BATALONI SHTAB NAVBATCHILIK QISMI NAVBATCHI-YORDAMCHISI': ['PPX BATALONI SHTAB NAVBATCHILIK QISMI NAVBATCHI-YORDAMCHISI'], 'PPX BATALONI BIRINCHI OTRYADI HAYDOVCHI-XODIMI': ['PPX BATALONI BIRINCHI OTRYADI SAFDOR-XODIMI', 'PPX BATALONI BIRINCHI OTRYADI HAYDOVCHI-XODIMI', 'PPX BATALONI BIRINCHI OTRYADI KOMANDIRI', 'PPX BATALONI BIRINCHI OTRYADI SAFDOR XODIMI'], "PPX BATALONI BIRINCHI OTRYADI KOMANDIRI O'RINBOSARI": ["PPX BATALONI BIRINCHI OTRYADI KOMANDIRI O'RINBOSARI", "PPX BATALONI ISOMTXT OTRYADI GURUX KOMANDIRI O'RINBOSARI", "PPX BATALONI  ISOMTXT OTRYADI KOMANDIRI O'RINBOSARI", 'PPX BATALONI BIRINCHI OTRYADI KOMANDIRI'], "PPX BATALONI KOMANDIRI MMI BO'YICHA URINBOSARI": ["BATALON KOMANDIRINING XIZMAT BO'YICHA O'RINBOSARI", "PPX BATALONI KOMANDIRI MTT BO'YICHA URINBOSARI", "PPX BATALONI KOMANDIRI MMI BO'YICHA URINBOSARI"], "PPX BATALONI KOMANDRINING O'RINBOSARI ISOMTO'XTO KOMANDIRI": ["PPX BATALONI KOMANDRINING O'RINBOSARI ISOMTO'XTO KOMANDIRI"], "PPX BATALONI TA'MINLASH GURUHI HAYDOVCHI-XODIMI": ["PPX BATALONI TA'MINLASH GURUHI HAYDOVCHI-XODIMI"], "PPX BATALONI TA'MINLASH GURUHI STARSHINASI": ["PPX BATALONI TA'MINLASH GURUHI STARSHINASI"], 'PPX BATALONI XIZMATNI TASHKILLASHTIRISH GURUHI KATTA INSPEKTORI': ['PPX BATALONI XIZMATNI TASHKILLASHTIRISH GURUHI KATTA INSPEKTORI'], 'PPX GURUH KOMAN': ['PPX GURUH KOMANDIRI', 'PPX GURUX KOMANDIRI', 'PPX GURUH KOMAN', 'GURUH KOMA'], 'PPKhB TPPKhO KhAIDOVChI KhODIM': ['PPKhB TPPKhO KhAIDOVChI  KhODIM', 'PPKhB TPPKhO SAFDOR KhODIM', 'PPKhB TPPKhO KhAIDOVChI KhODIM'], 'PPKhB KhTG INSPEKTORI': ['PPKh INSPEKTORI ', 'PPKh INSEKTORI', 'PPKhB KhTEG INSPEKTORI', 'PPKh INSPEKTORI', 'PPKhB KG KATTA INSPEKTORI', 'PPKhB KhTG INSPEKTORI', 'PPKh  INSPEKTORI', 'PPKh  INSPEKTOR', 'PPKh INSPEKTOR', 'PPKh ISOMTUKhTO INSPEKTORI', 'PPKhB KhTG KATTA INSPEKTORI', 'PPXB KATTA INSPEKTORI'], 'PPKhB INSPEKTOR-NAVBATChISI ': ['PPKhB INSPEKTOR-NAVBATChISI '], 'PPKhB KOMANDIRI URINBOSARI - ISOMTUKhT OTRIaDI KOMANDIRI': ['PPKhB KOMANDIRINING URINBOSARI-ISOMTUKhTO KOMANDIRI', 'PPKhB KOMANDIRI URINBOSARI - ISOMTUKhT OTRIaDI KOMANDIRI'], 'PPKhB KOMANDIRINING MMIB URINBOSARI': ['PPKh

In [76]:
max_pos_length = max(len(v) for v in similar_pos_names.values())
pos_data = {k: v + [None] * (max_pos_length - len(v)) for k, v in similar_pos_names.items()}
pos_dict_df = pd.DataFrame(pos_data)
print(pos_dict_df)

    ADMIN  LAVOZIM      INSPEKTOR  MARKAZ O'RINBOSARI  FRONT        KATTA INSPEKTOR    HAYDOVCHI      GURUX KOMANDIRI   GURUH KOMANDIRI O'RINBOSARI          PROFILAKTIKA INSPEKTOR    MUTAHASSIS  KICHIK INSPEKTOR  BO'LINMA BOSHLIG'I    TEST          OTRYAD KOMANDIRI    PPXB 2-OTRYAD SAFDOR XODIMI          PPXB INSPEKTOR   PPXB 4-TUMANLARARO OTRYADI BO'LINMA KOMANDIRI         PPXB 2-TUMANLARARO OTRYADI  INSPEKTORI  PPXB 4-TUMANLARARO OTRYADI XAYDOVCHI XODIMI                 PPXB ISMOTXT OTRYAD KOMANDIRI O'RINBOSARI  PPXB ISOMTO'XT OTRYADI INSPEKTORI              PPXB ISOMTO'XT OTRYADI GURUH KOMANDIRI  PPXB ISOMTO'XT OTRYADI MUTAXASSISI          PPXB 4-OTRYAD INSPEKTORI           PPXB 2-OTRYAD GURUX KOMANDIRI              PPXB 2-OTRYAD  BO'LINMA KOMANDIRI        PPXB KOMANDIRI  MTT ORINBOSARI  PPXB MMIB ORINBOSARI  VILOYAT IIB JXX JTSB BOSHLIG'I O'RINBOSARI  TA'MINLASH GURUHI INSPEKTORI  TEST JXD        TEZKOR VAKIL      TUMAN JAMOAT XAVFSIZLIGI XIZMATI BOSHLIG`I    TUMANLAR ARO PPX INSPEKTORI              TUMANLARARO OTRYAD KOMANDIRI  TUMANLARARO SAFDOR XODIM  UCHQURGON TUMANI  PPX INSPEKTORI    UCHTEPA TUMANI   SERJANT  YAKKASAROY TUMANI JTSB BOSHLIG`I    YANGI NAMANGAN TUMANI BERUNIY HTM BOSH INSPEKTORI  YANGI NAMANGAN TUMANI BIRUNIY 2-SONLI MFY PPX INSPEKTORI          YANGI NAMANGAN TUMANI IIB GUZAL MFY XTM PPX INSPEKTORI  YANGI NAMANGAN TUMANI PPX BULINMA KOMANDIRI             SUV BILAN ZARBA BERISH OPERATORI      SERGELI TUMANI IIO FMB JTSB BOSHLIG'I    PPXB OTLIQ GURUHI KOMANDIRI  PPXB OTLIQ GURUHI SAFDOR XODIMI  PPXB HIZMATINI TASHKIL ETISH  PPXB NAVBATCHILIK QISMI         PPXB NAVBATCHISI  PPXB SAFDOR HODIMI  PPXB XIZMAT BUYICHA ORINBOSARI  PPXB XIZMAT KURSATISH KOMINDANTI  PP{B TA'MINOT GURIHI   SAFDOR XODIMI  PATRUL POST XIZMATI INSPEKTORI  PD  PHVPX EE  PODPOLKOVNIK PPX BATALONI KOMANDIRI O'RINBOSARI  QASHQADARYO VILOYATI, IIB PPXB INSPEKTORI  RANK   SAFDOR  SAFDOR PPX BATALONI BIRINCHI OTRYADI BULINMA KOMANDIRI  PPX OTUQTO GURUX KOM  PPX BATALONI 1-OTRYAD OTRYADI SAFDOR XODIMI    PPX BATALONI ISOMTXT OTRYAD MUXANDIS XODIMI                PPX BATALONI ISOMTXT OTRYADI            OTR KOM O'RINBOSARI          OTRYAD KOMANDIRINING O'RINBOSARI    P I INSPEKTORI   PPX  PPX  KATTA MUXANDISI   PPX BRIGADASI             PPX BO'LINMA KOMANDIRI     PPX INS          PPX KOMANDIRINING MTT BO'YICHA O'RINBOSARI  PPX OPERATOR  PPX OTR KOM URIN  PPX TUMAN INSP   PPX XODIMI  PPX,ATALIONI ATG KATTA MUXANDISI  PPXB 1- OTRYAD INSPEKTORI SAFDOR XODIMI             YANGI NAMANGAN TUMANI PPX INSPEKTORI    PPXB 1-OTRYAD XAYDOVCHI XODIMI  PPX BATALONI ISOMTXT OTRYADI SUV BILAN ZARBA BERISH GURUHI KOMANDIRI      PPX BATALONI ISOMTXTO HAYDOVCHI-XODIMI  PPX BATALONI SHTAB NAVBATCHILIK QISMI KATTA INSPEKTOR NAVBATCHISI  PPX BATALONI SHTAB NAVBATCHILIK QISMI NAVBATCHI-YORDAMCHISI  PPX BATALONI BIRINCHI OTRYADI HAYDOVCHI-XODIMI       PPX BATALONI BIRINCHI OTRYADI KOMANDIRI O'RINBOSARI     PPX BATALONI KOMANDIRI MMI BO'YICHA URINBOSARI  PPX BATALONI KOMANDRINING O'RINBOSARI ISOMTO'XTO KOMANDIRI  PPX BATALONI TA'MINLASH GURUHI HAYDOVCHI-XODIMI  PPX BATALONI TA'MINLASH GURUHI STARSHINASI  PPX BATALONI XIZMATNI TASHKILLASHTIRISH GURUHI KATTA INSPEKTORI      PPX GURUH KOMAN   PPKhB TPPKhO KhAIDOVChI KhODIM        PPKhB KhTG INSPEKTORI  PPKhB INSPEKTOR-NAVBATChISI   PPKhB KOMANDIRI URINBOSARI - ISOMTUKhT OTRIaDI KOMANDIRI             PPKhB KOMANDIRINING MMIB URINBOSARI  PPKhB KOMANDIRINING MODDII TEKhNIKA TA'MINOTI BUIIChA URINBOSARI  PPKhB KOMENDANTI  PPKhB NAVBATChI IoRDAMChISI  PPKhB Kh'AIDOVChISI  STARShII INSPEKTOR       SUV BILAN ZARBA BERISh GURUKh'I KOMANDIRI  SURKhANDARIo VILOIaT IIB ShMKh SAF BULINMALARI PPKhO INSPEKTORI  TEKShIRISh, KUZATISh VA TEZKOR Kh'ARAKATLANISh GURUKh' KOMANDIRINING URINBOSARI         PPKhB TPPKhO KOMANDIRI  ZhTSG  ZhKhD INSPEKTORI  ZhAMOAT TARTIBINI SAK'LASh BOShK'ARMASI BOShLIG'I URINBOSARLARI   IIV  IIV ZhTSKh PPKh BULIM BOShLIG'I  IIV URINBOSARI  INSPEKTOR KhODIMI    MTB INSPEKTORI         OTRIaD KOMANDIRI U/I  PPKh ISOMTUKhTO   MUTAKhASSIS    PPKh INPEKTORI      PPKhB  KOMANDIRINING MA'NAVII-MA'RIFII IShLAR BUIIChA URINBOSARI   TEKShIRISh, KUZATISh VA TEZKOR Kh'ARAKATLANIShGURUKh'I MUTAKhASSISI  TOShKENT ShAKhAR IIBB ZhTSB BOSh INSPEKTORI    SAFDOR-KhODIM            OTRIaD KOMANDIRINING TARBIIaVII IShLAR BUIIChA URINBOSARI            OTRIaD KOMANDIRINING KhIZMAT BUIIChA URINBOSARI  SAFDOR KhAIDOVChI       OTRIaD KOMANDIR URINBOSARI  TRANSPORT ZhTSB INSPEKTORI  KhAIDWOVChI   KhAIDOVChI KhODIM  ShTK'ZULEUK  SUPER  TOShKENT ShAKh'AR IChKI IShLAR BOSh BOShK'ARMASI BOShLIG'INING ZhAMOAT TARTIBINI SAK'LASh BUIIChA URINBOSARI  KhTTB Kh'PG KATTA INSPEKTORI      BATAL'ON KOMANDIRI   BULINMA KAMANDIRI   DOZNAVATEL'  ETAKChI MUTAKhASSIS  VIIBB ZhKhKh ZhTSB BOShLIG'I  KADIRLAR GURUHI   KIBER  KKKKL  KOMANDIR OTRYAD O`RINBOSARI  O'QITUVCHI  OPERATOR   OTLIQ XODIM  OTR/GUR/ KOM  IKKINCHI TUMANLARARO PATRUL-POST XIZMATI GURUHI INSPEKTORI  IKKINCHI OTRYAD INSPEKTORI      YANGI NAMANGAN TUMANI IIB JTSB PPX 4-SONLI XTM INSPEKTORI    YASHNOBOD TUMANI IIO FMB JTSB BOSHLIG'I  ALOQA        BATALON KOMANDIRIR O'RINBOSARI   BOSH INSPEKTOR   HAYDOVCHI XODIMI  BOSH MUTAXASSIS     BOSHQARMA BOSHLIG'I    BOSHQARMA BOSHLIG'I O'RINBOSARI  DISIGNER  GURUX KOM   OTRYAD MUTAHASISI  PATRUL                      URAB OLISh VA KUZDAN KEChIRIShNI TAShKILLAShTIRISh GURUKh'I  AKhBOROT TEKhNOLOGIIaLARI BUIIChA BOSh INSPKEKTORI  BUSTANLIK TIMAN  TOLEBI MFI  BUSTONLIK' TIIB 3-SON IIB PPKhG INSPEKTORI  PROD TEST  PROF INS  VILOYAT ADMIN  TUMAN JTSB BOSHLIG`I    TUMANLARARO PATRUL-POST XIZMATI OTRYADI BIRINCHI TUMANLARARO PATRUL-POST XIZMATI GURUHI HAYDOVCHISI              NAMANGAN VILOYATI IIB JXX JTSB MAXSUS OTRYAD MUTAXASIS  SHAYXONTOHUR TUMANI IIO FMB 5-SONLI IIB HPB PROFILAKTIKA INSPEKTORI   P.I  P.K.I   P/I  TUMAN ADMIN  ZhKhKh BOSh INSPEKTOR  BOSh MUTAKhASSIZ  O`TTAA XASIS AGES    MUTAXASIS KINOLOG  MUTAXASIS SAPYOR;  MUTAXASSIS XAYDOVCHI  MUTAXASSIS-MERGAN  OFITSER  PSIXOLOGIK   PKI   SEKSIYA KOMANDIR  SIKTIRGANSKI  SURISHTIRUVCHI  SURUSHTIRUV BOSHLIG'I  YURIST    BULIM BOShLIG'I  32904966800012  94-058-98-00   1-MINTAQA PPXO 1 GURUX KOMANDIRI  1-OTRYAD MPPX INSPEKTORI           1-MINTAQA PPX INSPEKTORI       1-MMM PPKhO 1-GURUKh KOMANDIRI  1-MMM PPKhO TIB O'RINBOSARI       ISMOTXTO  INSPEKTORI   NAMANGAN VILOYATI IIB JXX JTSB PPXB MAXSUS OTRYAD INSPEKTORIGURUH KOMANDIRI URINBOSARI    PPKhB KATTA MUKhANDISI  1 MINTAXA PPX OTRYAD KOM ORINBOSARI  KOMANDIR SEKSIYA  1-MINTAK'A PPKh OTRIaD KOMANDARINING MMIB URINBOSARI  98162 HARBIY QISM  ALOQA BOSHLIG'I  BBO'  BATALYON SHTAB BOSHLIG`I  FELDSHER  GURUH KOMANDIRI (532)  GURUH KOMANDIRI YORDAMCHISI  GURUH MUTAXASSISI  INSPEKTOR PSIXOLOG   KATTA OFITSER  KINOLOG  KONTRRAZVEDKA BO`LIM BOSHLIG`I    MTTV KOMANDIRI  MUTAXASSIS PULEMYOTCHI  ZhKB TTIG ETAKCh MUTAKhSSISI   QO'SHTEPA T 1-O'RINBOSAR   BESHARIQ T 1-O'RINBOSAR  BOSH PROKURATURASI HUQUQNI MUHOFAZA QILISH AKADEMIYASI   BUVAYDA T 1-O'RINBOSARI  DANG'ARA T 1-O'RINBOSARI  FARG'ONA SH 1-O'RINBOSARI     FURQAT T 1-O'RINBOSAR  O'ZBEKISTON T 1-O'RINBOSARI     SO'X T 1-O'RINBOSARI  UCHKO'PRIK T 1-O'RINBOSARI  YOZYOVON T 1-O'RINBOSAR   JQB  KJ.JK.JK.  YEKAKCHI MUTAXASSISI  TKD ZhKKh BULIM BOShLIGI    MUTAHASSIS O'QCHI  PORTLATUVCHI  PULEMYOTCHI  RADIOTELEFONCHI  TA'MINOT BO'YICHA YORDAMCHI  TEZKOR NAVBATCHI  GDSG  GURUH OFITSERI  KICHIK SERJANT    OK   MUTAXASSIS-YUNALTIRUVCHI  MUTAXASSIS HISOB RAQAM  MUTAXASISS KAVALERYACHI   MUTAXASSIS FELDSHER  MUTAXASSIS HAYDOVCHI (MOTOSIKLCHI))  MUTAXASSIS-SEKSIYA KOMANDIRI  MUTAXASSIS OPIROTOR  MUTAXASSIS PORTLATUVCHI  MUTAXASSIS RAQAM XISOBCHI  1-MINTAK'A PPKh OTRIaD KOMANDIRI                NAMANMGAN VILOYATI PPXB INSPEKTORI  DAVLATOBOD TUMANI PPX BULIMMA KOMANDIRI  ISMOTXTO GURUH KOMANDIRI   ISMOXTO MUXANDISI  ISOMTO'XTO MUTAXASISI  ISOMTUHT  SAFDOR XODIMI  ISOMTUHTA  ISOMTUHTA OTRYADI  INSPEKTOR SAFDOR XODIMI               DAVLATOBOD TUMANI PPX INSPEKTORI       DAVLATOBOD TUMANI UMID HTM BOSH INSPEKTORI  DEVELOPER      FARG'ONA VILOYATI IIB IMH PPX OTRYADI XIZMAT BUYICHA O'RINBOSARI     IIB JXX JTSB O'RINBOSAR          IIB JXX JTSB BOSHLIG'I          JTSB BOSHLIG`INING O`RINBOSARI      JTSB BOSHLIG'I          NAMANGAN SHAXAR IIB JXX JTSB PPX INSPEKTORI  NAMANGAN SHAXAR IIB JXX PPX OTRYAD BULINMA KOMANDIRI      NAMANGAN SHAXAR LOLA XTM BOSH INSPEKTORI  NAMANGAN SHAXAR CHORSU MFY XTM INSPERTORI  NAMANGAN VILOYATI IIB JXX JTSB PPXB    NAMANGAN VILOYATI IIB JXX JTSB PPXB MAXSUS OTRYAD SUV BILAN ZARBA BERISH XAYDOVCHISI   NAMANGAN SHAHAR PPX INSPEKTORI    NAMANGAN VILOYATI IIB JXX JTSB PPXB TUMANLARARO OTRYAD KOMANDIRI           NAMANGAN VILOYATI IIB PPXB MAXSUS OTRYADI INSPEKTORI  NAMANGAN VILOYATI PPXB NAVBATCHISI  NAMANGAN VILOYATI PPXB OTLIQ GURUHI  NAMANGAN VILOYATI PPXB TUMANLARARO  MMIO'  JTSB NQ KATTA INSPEKTOR NAVBATCHI   JXX ATB  KADRLAR GURUXI KATTA INSPEKTORI  KATTA SERJANT   LLL  MPPX INSPEKTORI TUNGI KLUB   MAXSUS OTRYAD PPX INSPEKTORI      MIRZO ULUG`BEK TUMANI IIO FMB BOSHLIG`I  MUHANDIS  NAMANGAN SHAHAR GISHTKUPRIK 5-SON MFY PPX INSPEKTORI        NAMANGAN SHAHAR IIB PPX 4-SONLI OZOD MFY HTM INSPEKTORI    DAVLATOBOD TUMANI IIB JXX JTSB PPX OTRYAD KOMANDIRI    2-MINTAK'A PPKh GURUKh' KOMANDIRI  2-MINTAK'A PPKh KATTA INSPEKTORI     2-OTRIaD MPPKh INSPEKTORI  2-OTRIaD MPPKhO    2-OTRIaD SAFDOR-KhODIM   3 MINTAXA PPX OTRYAD KOMANDIRI  3-GURUH SAVDOR HODIMI           3-PPKh OTRIaD KOMANDIRI  2-GURUKh KAMANDIRI  1-OTRIaD GURUKh KOMANDIRI                 BIRINCHI OTRYAD BO'LINMA KOMANDIRI  BATALION KOMANDIRINING MA'NAVIY VA MA'RIFIY ISHLAR BO'YICHA O'RINBOSARI     DEV  BRIGADA KOMANDIRI  32509893500073  4-MMM PPKhO KAMANDIRI  4-MINTAK'A PPKh KhAIDOVChI  9999999999999999  ATG MUHANDISI  ALOQA GURUHI KATTA MUHANDISI  AXBOROT TEHNALOGIYALARI GURUHI   KhIZMAT BOShLIG'I
0   ADMIN  LAVOZIM      INSPKETOR  MARKAZ O'RINBOSARI  FRONT        KATTA INSPEKTOR   HAYDOVCHI     3-GURUX KOMANDIRI          KOMANDIR O`RINBOSARI        PROFILAKTIKA  INSPEKTORI   MUTAHASSIS   KICHIK INSPEKTOR   BULINMA BOShLIG'I    TEST      PPX OTRYAD KOMANDIRI  PPXB 2-OTRYAD XAYDOVCHI XODIMI       PPKh INSPREKTOR    PPXB 3-TUMANLARARO OTRYADI BO'LINMA KOMANDIRI          PPXB 3- TUMANLARARO OTRYAD INSPEKTORI  PPXB 4-TUMANLARARO OTRYADI XAYDOVCHI XODIMI                            4-OTRYAD KOMANDIRI O'RINBOSARI           PPX ISOTOXTO  INSPEKTORI                    PPXB ISOMTO'XT OTRYADI MUXANDISI    PPXB ISOMTO'XT OTRYADI MUXANDISI         PPXB 3-OTRYAD  INSPEKTORI                    PPX OTRYAD KOMANDIRI              PPXB 2-OTRYAD  BO'LINMA KOMANDIRI        PPXB KOMANDIRI  MTT ORINBOSARI  PPXB MMIB ORINBOSARI  VILOYAT IIB JXX JTSB BOSHLIG'I O'RINBOSARI  TA'MINLASH GURUHI INSPEKTORI  TEST JXD   UMIB TEZKOR VAKIL  TUMAN ZhAMOAT KhAVFSIZLIGI KhIZMATI BOShLIG'I        2-TUMANLARARO INSPEKTORI  TUMANLARARO OTRYAD KOMANDIRI O'RINBOSARI  TUMANLARARO SAFDOR XODIM  UCHQURGON TUMANI  PPX INSPEKTORI    UCHTEPA TUMANI   SERJANT  YAKKASAROY TUMANI JTSB BOSHLIG`I  YANGI NAMANGAN TUMANI BUNYODKOR HTM BOSH INSPEKTORI  YANGI NAMANGAN TUMANI BIRUNIY 2-SONLI MFY PPX INSPEKTORI                YANGI NAMANGAN TUMANI GO`ZAL HTM BOSH INSPEKTORI        YANGI NAMANGAN TUMANI PPXB INSPEKTORI    SUV BILAN ZARBA BERISh GURUKh'I OPERATORI    YUNUSOBOD TUMANI IIO FMB JTSB BOSHLIG'I    PPXB OTLIQ GURUHI KOMANDIRI  PPXB OTLIQ GURUHI SAFDOR XODIMI  PPXB HIZMATINI TASHKIL ETISH  PPXB NAVBATCHILIK QISMI  PPXB NAVBATCHILIK QISMI        SAFDOR HODIM  PPXB XIZMAT BUYICHA ORINBOSARI  PPXB XIZMAT KURSATISH KOMINDANTI  PP{B TA'MINOT GURIHI    SAFDOR XODIM  PATRUL-POST XIZMATI INSPEKTORI  PD  PHVPX EE  PODPOLKOVNIK PPX BATALONI KOMANDIRI O'RINBOSARI  QASHQADARYO VILOYATI, IIB PPXB INSPEKTORI  RANK  SAFDOR         PPX BATALONI BIRINCHI OTRYADI BO'LINMA KOMANDIRI  PPX OTUQTO GURUX KOM  PPX BATALONI BIRINCHI OTRYADI SAFDOR-XODIMI   PPX BATALONI ISOMTXT OTRYAD MUTAXASIS XODIMI                PPX BATALONI ISOMTXT OTRYADI   OTRYAD KOMANDIRI O'RINBOSARI               OTRYAD KOMANDIR O'RINBOSARI     PPX INSPEKTOR  PPXB  PPX  KATTA MUXANDISI  PPX BRIGADASI   PPXB 4-OTRYADI BO'LINMA KOMANDIRI  PPX INSPEK          PPX KOMANDIRINING MTT BO'YICHA O'RINBOSARI  PPX OPERATOR  PPX OTR KOM URIN  PPX TUMAN INSP   PPX XODIMI  PPX,ATALIONI ATG KATTA MUXANDISI             PPXB 3- OTRYAD SAFDOR XODIMI             YANGI NAMANGAN TUMANI PPX INSPEKTORI    PPXB 1-OTRYAD XAYDOVCHI XODIMI  PPX BATALONI ISOMTXT OTRYADI SUV BILAN ZARBA BERISH GURUHI KOMANDIRI  PPX BATALONI ISOMTXT OTRYADI SAFDOR-XODIMI  PPX BATALONI SHTAB NAVBATCHILIK QISMI KATTA INSPEKTOR NAVBATCHISI  PPX BATALONI SHTAB NAVBATCHILIK QISMI NAVBATCHI-YORDAMCHISI     PPX BATALONI BIRINCHI OTRYADI SAFDOR-XODIMI       PPX BATALONI BIRINCHI OTRYADI KOMANDIRI O'RINBOSARI  BATALON KOMANDIRINING XIZMAT BO'YICHA O'RINBOSARI  PPX BATALONI KOMANDRINING O'RINBOSARI ISOMTO'XTO KOMANDIRI  PPX BATALONI TA'MINLASH GURUHI HAYDOVCHI-XODIMI  PPX BATALONI TA'MINLASH GURUHI STARSHINASI  PPX BATALONI XIZMATNI TASHKILLASHTIRISH GURUHI KATTA INSPEKTORI  PPX GURUH KOMANDIRI  PPKhB TPPKhO KhAIDOVChI  KhODIM             PPKh INSPEKTORI   PPKhB INSPEKTOR-NAVBATChISI        PPKhB KOMANDIRINING URINBOSARI-ISOMTUKhTO KOMANDIRI  PPKhB KOMANDIRINING KhIZMAT BUIIChA URINBOSARI  PPKhB KOMANDIRINING MODDII TEKhNIKA TA'MINOTI BUIIChA URINBOSARI  PPKhB KOMENDANTI  PPKhB NAVBATChI IoRDAMChISI  PPKhB Kh'AIDOVChISI  STARShII INSPEKTOR       SUV BILAN ZARBA BERISh GURUKh'I OPERATORI  SURKhANDARIo VILOIaT IIB ShMKh SAF BULINMALARI PPKhO INSPEKTORI  TEKShIRISh, KUZATISh VA TEZKOR Kh'ARAKATLANISh GURUKh' KOMANDIRINING URINBOSARI         PPKhB TPPKhO KOMANDIRI  ZhTSG  PPKh INSPEKTORI   ZhAMOAT TARTIBINI SAK'LASh BOShK'ARMASI BOShLIG'I URINBOSARLARI   IIV  IIV ZhTSKh PPKh BULIM BOShLIG'I  IIV URINBOSARI   INSPEKTOR KhODIM   JTSB INSPEKTORI             OTRIaD KOMANDIRI  PPKh ISOMTUKhTO   MUTAKhASSIS   PPKh INSPREKTOR   OTRIaD KOMANDIRINING MA'NAVII VA MA'RIFII IShLAR BUIIChA URINBOSARI   TEKShIRISh, KUZATISh VA TEZKOR Kh'ARAKATLANISh GURUKh'I MUKh'ANDISI  TOShKENT ShAKhAR IIBB ZhTSB BOSh INSPEKTORI     SAFDOR XODIM            OTRIaD KOMANDIRINING TARBIIaVII IShLAR BUIIChA URINBOSARI             PPKhB KOMANDIRINING KhIZMAT BUIIChA URINBOSARI  SAFDOR KhAIDOVChI   4-OTRYAD KOMANDIRI O'RINBOSARI  TRANSPORT ZhTSB INSPEKTORI  KhAIDWOVChI   KhAIDOVChI KhODIM  ShTK'ZULEUK  SUPER  TOShKENT ShAKh'AR IChKI IShLAR BOSh BOShK'ARMASI BOShLIG'INING ZhAMOAT TARTIBINI SAK'LASh BUIIChA URINBOSARI   PPKhB KhTG KATTA INSPEKTORI      BATAL'ON KOMANDIRI    BULINMA KOMANDIRI  DOZNAVATEL'  ETAKChI MUTAKhASSIS  VIIBB ZhKhKh ZhTSB BOShLIG'I  KADIRLAR GURUHI   KIBER  KKKKL         KOMANDIR O`RINBOSARI  O'QITUVCHI   OPERATOR  OTLIQ XODIM  OTR/GUR/ KOM                  IKKINCHI TUMANLARARO PPX GURUHI INSPEKTORI  BIRINCHI OTRYAD INSPEKTORI                        YANGI NAMANGAN TUMANI IIB PPX INSPETORI   OLMAZOR  TUMANI IIO FMB JTSB BOSHLIG'I    ALOQA        BATALON KOMANDIRIR O'RINBOSARI   BOSH INSPEKTOR    HAYDOVCHI HODIM       MUTAXASSIS  IIB BOSHQARMA BOSHLIGI    BOSHQARMA BOSHLIG'I O'RINBOSARI  DISIGNER  GURUX KOM   OTRYAD MUTAHASISI  PATRUL                     URAB OLISh VA KUZDAN KEChIRIShNI TAShKILLAShTIRISh GURUKh'I   AKhBOROT TEKhNOLOGIIaLARI BUIIChA BOSh INSPKEKTORI  BUSTANLIK TIMAN  TOLEBI MFI  BUSTONLIK' TIIB 3-SON IIB PPKhG INSPEKTORI  PROD TEST  PROF INS  VILOYAT ADMIN        JTSB BOSHLIG`I    TUMANLARARO PATRUL-POST XIZMATI OTRYADI BIRINCHI TUMANLARARO PATRUL-POST XIZMATI GURUHI HAYDOVCHISI        NAMANGAN VILOYATI IIB JXX JTSB PPXB MAXSUS OTRYAD MUTAXASISI  SHAYXONTOHUR TUMANI IIO FMB 5-SONLI IIB HPB PROFILAKTIKA INSPEKTORI   P.I  P.K.I   P/I  TUMAN ADMIN  ZhKhKh BOSh INSPEKTOR  BOSh MUTAKhASSIZ  O`TTAA XASIS AGES   MUTAXASSIS KINOLIK  MUTAXASIS SAPYOR;     MUTAXASSIS O'QCHI  MUTAXASSIS-MERGAN  OFITSER  PSIXOLOGIK   PKI   SEKSIYA KOMANDIR  SIKTIRGANSKI  SURISHTIRUVCHI  SURUSHTIRUV BOSHLIG'I  YURIST  BULINMA BOShLIG'I  32904966800012  94-058-98-00   1-MINTAQA PPXO 2 GURUH KOMANDIRI      1-OTRYAD MPPX INSPEKTORI    1-MINTAK'A PPKh INSPEKTORI        1-MMM PPKhO 1-GURUKh KOMANDIRI  1-MMM PPKhO TIB O'RINBOSARI   PPX ISOTOXTO  INSPEKTORI                             NAMANGAN VILOYATI IIB JXX JTSB PPXB MAXSUS OTRYAD INSPEKTORII   PPKhB KATTA MUKhANDISI  1 MINTAXA PPX OTRYAD KOM ORINBOSARI  KOMANDIR SEKSIYA  1-MINTAK'A PPKh OTRIaD KOMANDARINING MMIB URINBOSARI  98162 HARBIY QISM  ALOQA BOSHLIG'I  BBO'  BATALYON SHTAB BOSHLIG`I  FELDSHER         GURUH KOMANDIR  GURUX KOMANDIRI YORDAMCHISI  GURUH MUTAXASSISI  INSPEKTOR PSIXOLOG  KATTA OFITSERI  KINOLOG  KONTRRAZVEDKA BO`LIM BOSHLIG`I  OTRIAT KOMANDIRI  MUTAXASSIS PULEMYOTCHI  ZhKB TTIG ETAKCh MUTAKhSSISI   QO'SHTEPA T 1-O'RINBOSAR   BESHARIQ T 1-O'RINBOSAR  BOSH PROKURATURASI HUQUQNI MUHOFAZA QILISH AKADEMIYASI  QUVASOY SH 1-O'RINBOSARI  DANG'ARA T 1-O'RINBOSARI  FARG'ONA SH 1-O'RINBOSARI       QUVA T 1-O'RINBOSAR  O'ZBEKISTON T 1-O'RINBOSARI     SO'X T 1-O'RINBOSARI  UCHKO'PRIK T 1-O'RINBOSARI  YOZYOVON T 1-O'RINBOSAR   JQB  KJ.JK.JK.  YEKAKCHI MUTAXASSISI  TKD ZhKKh BULIM BOShLIGI  MUTAXASSIS ALOQACHI  PORTLATUVCHI  PULEMYOTCHI  RADIOTELEFONCHI  TA'MINOT BO'YICHA YORDAMCHI  TEZKOR NAVBATCHI  GDSG  GURUH OFITSERI  KICHIK SERJANT    OK  MUTAXASSIS YO'NALTIRUVCHI  MUTAXASSIS HISOB RAQAM  MUTAXASISS KAVALERYACHI   MUTAXASSIS FELDSHER  MUTAXASSIS HAYDOVCHI (MOTOSIKLCHI))  MUTAXASSIS SEKSIYA KOMANDIRI  MUTAXASSIS OPIROTOR  MUTAXASSIS PORTLATUVCHI  MUTAXASSIS RAQAM XISOBCHI   2-MINTAK'A PPKh OTRIaD KOMANDIRI                  NAMANGAN SHAHAR PPXB INSPEKTORI  DAVLATOBOD TUMANI PPX BULINMA KOMANDIRI  ISMOTXTO GURUH KOMANDIRI   ISMOXTO MUXANDISI     ISMTOXTO MUXANDISI   ISOMTUHT SAFDOR HODIMI  ISOMTUHTA  ISOMTUHTA OTRYADI  INSPEKTOR SAFDOR XODIMI              DAVLATOBOD TUMANI PPX INSPEKTORI        DAVLATOBOD TUMANI UMID HTM BOSH INSPEKTORI  DEVELOPER  FARG'ONA VILOYATI IIB IMH PPX OTRYADI KOMANDIRINING TIB O'RINBOSARI   IIB JXX JTSB 1-O'RINBOSARI          IIB JXX JTSB BOSHLIG'I             JTSB BOSHLIG'I O'RINBOSARI       JTSB BOSHLIG'I  NAMANGAN SHAXAR IIB JXX JTSB PPX OTRYADI INSPEKTORI   NAMANGAN SHAXAR IIB JXX JTSB PPX OTRYADI INSPEKTORI      NAMANGAN SHAXAR LOLA XTM BOSH INSPEKTORI  NAMANGAN SHAXAR CHORSU MFY XTM INSPERTORI  NAMANGAN VILOYATI IIB JXX JTSB PPXB    NAMANGAN VILOYATI IIB JXX JTSB PPXB MAXSUS OTRYAD SUV BILAN ZARBA BERISH XAYDOVCHISI  NAMANGAN SHAHAR PPXB INSPEKTORI        NAMANGAN VILOYATI IIB JXX JTSB PPXB MAXSUS OTRYAD MUTAXASISI           NAMANGAN VILOYATI PPXB TUMALARARO OTRYADI INSPEKTORI  NAMANGAN VILOYATI PPXB NAVBATCHISI  NAMANGAN VILOYATI PPXB OTLIQ GURUHI  NAMANGAN VILOYATI PPXB TUMANLARARO  MMIO'  JTSB NQ KATTA INSPEKTOR NAVBATCHI   JXX ATB  KADRLAR GURUXI KATTA INSPEKTORI  KATTA SERJANT   LLL  MPPX INSPEKTORI TUNGI KLUB       3-OTRYAD MPPX INSPEKTORI      MIRZO ULUG`BEK TUMANI IIO FMB BOSHLIG`I  MUHANDIS  NAMANGAN SHAHAR GISHTKUPRIK 5-SON MFY PPX INSPEKTORI        NAMANGAN SHAHAR IIB PPX 4-SONLI OZOD MFY HTM INSPEKTORI    DAVLATOBOD TUMANI IIB JXX JTSB PPX OTRYAD KOMANDIRI  3-MINTAK'A PPKh 3-GURUKh' KOMANDIRI        1-MINTAK'A PPKh INSPEKTORI     1-OTRYAD MPPX INSPEKTORI   2-OTRIaD MPPKhO  3-OTRIaD SOFDOR-KhODIMI              PPX OTRYAD KOMANDIRI  3-GURUH SAVDOR HODIMI           3-PPKh OTRIaD KOMANDIRI   1-GURUX KOMANDIRI  1-OTRIaD GURUKh KOMANDIRI   PPX BATALONI BIRINCHI OTRYADI BO'LINMA KOMANDIRI  BATALION KOMANDIRINING MA'NAVIY VA MA'RIFIY ISHLAR BO'YICHA O'RINBOSARI     DEV  BRIGADA KOMANDIRI  32509893500073  4-MMM PPKhO KAMANDIRI  4-MINTAK'A PPKh KhAIDOVChI  9999999999999999  ATG MUHANDISI  ALOQA GURUHI KATTA MUHANDISI  AXBOROT TEHNALOGIYALARI GURUHI   KhIZMAT BOShLIG'I

In [77]:
pos_dict_df.to_excel("epatrul_structure.xlsx", index=False)