In [1]:
import psutil

# Check memory usage
def memory_usage():
    process = psutil.Process()
    mem_info = process.memory_info()
    return mem_info.rss / (1024 * 1024)  # Convert bytes to MB

print(f"Memory usage: {memory_usage()} MB")

Memory usage: 52.98046875 MB

In [2]:
import pandas as pd
import numpy as np
# Set pandas display options
pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.max_colwidth', None)  # Show full column width
pd.set_option('display.expand_frame_repr', False)  # Disable wrapping of rows

In [3]:
df = pd.read_csv('./fevral_2025_by_created_time.csv', sep=';')
df.head()

/var/folders/ww/67t1k6ss6bqfd8tw6ntmpfgm0000gn/T/ipykernel_14019/4076913990.py:1: DtypeWarning: Columns (24,49) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('./fevral_2025_by_created_time.csv', sep=';')

   protocolid                 createdtime                 updatedtime            violationtime  regionid  districtid   mtpid  organid protocolarticlepart inspectorworkcertificate  inspectorpinpp isrealinspectorpinpp inspectorbirthdate  latitude  longitude series         number                         inspectorfio  casestatus                      casestatusname      lastname firstname      secondname documentseries documentnumber           pinpp isrealpinpp   birthdate violatorgender violatorintoxicationname  violatorintoxicationid  violatoractualaddressregionid  violatoractualaddressdistrictid  decisionstatus decisionstatusname  decisiontypeid decisiontypename executiondate mainpunishmenttype mainpunishmentamount  resolutionorganid  admcaseorganid        admcaseorgan resolutionorgan resolutionconsiderinfo  punishmenttypeid  terminationreasonid  protocolarticlepartid  victimid victimpinpp  mainpunishmentamountsumm  mainpunishmentpaidamount mainpunishmentlastpaytime discountfordate70  discountamount70 discountfordate50  discountamount50  damageamount  damagetypeid damagetypename  compensationamount  compensationpaidamount
0    49231179  2025-02-20 03:43:44.043334  2025-02-20 03:43:51.202054  2025-03-04 08:50:44.044        11         258  2775.0       14             52 - 2Q           ТV- I № 002019  30303975800011                    t         1997-03-03       NaN        NaN   PTVL  2507301773207            ASATOV FARRUX URAL O‘G‘LI           3                  KO`RIB CHIQILMOQDA     BASHIROVA    NOZIMA      NU’MONOVNA             AE        1477072  41207864160023           t  1986-07-12           AYOL                      NaN                     NaN                             11                              258             NaN                NaN             NaN              NaN           NaN                NaN                  NaN                NaN              14  HPX (PROFILAKTIKA)             NaN                    NaN               NaN                  NaN                    968       NaN         NaN                       NaN                       NaN                       NaN               NaN               NaN               NaN               NaN           NaN           NaN            NaN                 NaN                     NaN
1    49231094  2025-02-20 03:43:44.043334  2025-02-20 03:43:51.202054   2025-03-04 08:46:19.65        11         258  2775.0       14             52 - 2Q           ТV- I № 002019  30303975800011                    t         1997-03-03       NaN        NaN   PTVL  2507301773122            ASATOV FARRUX URAL O‘G‘LI           3                  KO`RIB CHIQILMOQDA     RAXMONOVA   GULSHAN     FURQAT QIZI             AC        1205117  60102006020063           t  2000-02-01           AYOL                      NaN                     NaN                              7                              128             NaN                NaN             NaN              NaN           NaN                NaN                  NaN                NaN              14  HPX (PROFILAKTIKA)             NaN                    NaN               NaN                  NaN                    968       NaN         NaN                       NaN                       NaN                       NaN               NaN               NaN               NaN               NaN           NaN           NaN            NaN                 NaN                     NaN
2    49231016  2025-02-27 08:41:25.152334  2025-02-27 08:42:01.972133      2025-02-23 08:47:00        12         296  1323.0       14         161 - MODDA              FV-I 009711  31406954200080                    t         1995-06-14       NaN        NaN   PFAR  2507301773044  SOTVOLDIYEV MUZAFFAR UMIDBEK O‘G‘LI           3                  KO`RIB CHIQILMOQDA       NIZOMOV  BOTIRALI  ABDUMALIKOVICH             AD        3941205  32703887020019           t  1988-03-27          ERKAK                      NaN                     NaN                             12                              296             NaN                NaN             NaN              NaN           NaN                NaN                  NaN                NaN              14  HPX (PROFILAKTIKA)             NaN                    NaN               NaN                  NaN                   1453       NaN         NaN                       NaN                       NaN                       NaN               NaN               NaN               NaN               NaN           NaN           NaN            NaN                 NaN                     NaN
3    49228807  2025-02-11 19:27:44.746846  2025-02-11 19:27:52.666441  2025-03-04 04:02:26.856        12         285  1243.0       14     61  - PRIM-2 1Q              FV-I 006963  32210986900015                    t         1998-10-22       NaN        NaN   PFAR  2507301770835   ABDULLAYEV SHERZOD BAXTIYOR O‘G‘LI           3                  KO`RIB CHIQILMOQDA  TOSHPULATOVA   UG‘ILOY       MUSOYEVNA             AD        9495283  41411874140096           t  1987-11-14           AYOL                      NaN                     NaN                             12                              285             NaN                NaN             NaN              NaN           NaN                NaN                  NaN                NaN              14  HPX (PROFILAKTIKA)             NaN                    NaN               NaN                  NaN                    994       NaN         NaN                       NaN                       NaN                       NaN               NaN               NaN               NaN               NaN           NaN           NaN            NaN                 NaN                     NaN
4    49226121  2025-02-09 15:30:14.507008  2025-03-03 23:13:14.727685  2025-03-03 22:38:51.484         6         115  5854.0       14          41 - MODDA               АD-2181936  31211955910018                    t         1995-11-12       NaN        NaN   PNAM  2507301768149   XOLDAROV ALISHER ABDURASHID O‘G‘LI           9  SUDGA KO'RIB CHIQISH U-N YUBORILDI   HAYITMATOVA  NISHONBI   RAXMATJONOVNA             AD        7357357  42407842210024           t  1984-07-24           AYOL                      NaN                     NaN                              6                              115             NaN                NaN             NaN              NaN           NaN                NaN                  NaN                NaN              14  HPX (PROFILAKTIKA)             NaN                    NaN               NaN                  NaN                    906       NaN         NaN                       NaN                       NaN                       NaN               NaN               NaN               NaN               NaN           NaN           NaN            NaN                 NaN                     NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 874416 entries, 0 to 874415
Data columns (total 62 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   protocolid                       874416 non-null  int64
 1   createdtime                      874416 non-null  object
 2   updatedtime                      874416 non-null  object
 3   violationtime                    874416 non-null  object
 4   regionid                         874416 non-null  int64
 5   districtid                       874416 non-null  int64
 6   mtpid                            382522 non-null  float64
 7   organid                          874416 non-null  int64
 8   protocolarticlepart              874416 non-null  object
 9   inspectorworkcertificate         443376 non-null  object
 10  inspectorpinpp                   862725 non-null  object
 11  isrealinspectorpinpp             862725 non-null  object
 12  inspectorbirthdate               862725 non-null  object
 13  latitude                         492893 non-null  float64
 14  longitude                        492893 non-null  float64
 15  series                           874416 non-null  object
 16  number                           874416 non-null  int64
 17  inspectorfio                     874416 non-null  object
 18  casestatus                       874416 non-null  int64
 19  casestatusname                   874416 non-null  object
 20  lastname                         874416 non-null  object
 21  firstname                        874416 non-null  object
 22  secondname                       874037 non-null  object
 23  documentseries                   874414 non-null  object
 24  documentnumber                   874416 non-null  object
 25  pinpp                            874416 non-null  object
 26  isrealpinpp                      874416 non-null  object
 27  birthdate                        874416 non-null  object
 28  violatorgender                   874416 non-null  object
 29  violatorintoxicationname         17743 non-null   object
 30  violatorintoxicationid           17743 non-null   float64
 31  violatoractualaddressregionid    874416 non-null  int64
 32  violatoractualaddressdistrictid  874416 non-null  int64
 33  decisionstatus                   827529 non-null  float64
 34  decisionstatusname               827529 non-null  object
 35  decisiontypeid                   827529 non-null  float64
 36  decisiontypename                 827529 non-null  object
 37  executiondate                    484083 non-null  object
 38  mainpunishmenttype               802600 non-null  object
 39  mainpunishmentamount             802600 non-null  object
 40  resolutionorganid                827529 non-null  float64
 41  admcaseorganid                   874416 non-null  int64
 42  admcaseorgan                     874416 non-null  object
 43  resolutionorgan                  827529 non-null  object
 44  resolutionconsiderinfo           827527 non-null  object
 45  punishmenttypeid                 802600 non-null  float64
 46  terminationreasonid              24681 non-null   float64
 47  protocolarticlepartid            874416 non-null  int64
 48  victimid                         18103 non-null   float64
 49  victimpinpp                      18103 non-null   object
 50  mainpunishmentamountsumm         780673 non-null  float64
 51  mainpunishmentpaidamount         780673 non-null  float64
 52  mainpunishmentlastpaytime        458369 non-null  object
 53  discountfordate70                755639 non-null  object
 54  discountamount70                 755639 non-null  float64
 55  discountfordate50                755639 non-null  object
 56  discountamount50                 755639 non-null  float64
 57  damageamount                     19597 non-null   float64
 58  damagetypeid                     19597 non-null   float64
 59  damagetypename                   19597 non-null   object
 60  compensationamount               3900 non-null    float64
 61  compensationpaidamount           3900 non-null    float64
dtypes: float64(18), int64(10), object(34)
memory usage: 413.6+ MB

In [5]:
print(df.iloc[0])

protocolid                                           49231179
createdtime                        2025-02-20 03:43:44.043334
updatedtime                        2025-02-20 03:43:51.202054
violationtime                         2025-03-04 08:50:44.044
regionid                                                   11
districtid                                                258
mtpid                                                  2775.0
organid                                                    14
protocolarticlepart                                   52 - 2Q
inspectorworkcertificate                       ТV- I № 002019
inspectorpinpp                                 30303975800011
isrealinspectorpinpp                                        t
inspectorbirthdate                                 1997-03-03
latitude                                                  NaN
longitude                                                 NaN
series                                                   PTVL
number                                          2507301773207
inspectorfio                        ASATOV FARRUX URAL O‘G‘LI
casestatus                                                  3
casestatusname                             KO`RIB CHIQILMOQDA
lastname                                            BASHIROVA
firstname                                              NOZIMA
secondname                                         NU’MONOVNA
documentseries                                             AE
documentnumber                                        1477072
pinpp                                          41207864160023
isrealpinpp                                                 t
birthdate                                          1986-07-12
violatorgender                                           AYOL
violatorintoxicationname                                  NaN
violatorintoxicationid                                    NaN
violatoractualaddressregionid                              11
violatoractualaddressdistrictid                           258
decisionstatus                                            NaN
decisionstatusname                                        NaN
decisiontypeid                                            NaN
decisiontypename                                          NaN
executiondate                                             NaN
mainpunishmenttype                                        NaN
mainpunishmentamount                                      NaN
resolutionorganid                                         NaN
admcaseorganid                                             14
admcaseorgan                               HPX (PROFILAKTIKA)
resolutionorgan                                           NaN
resolutionconsiderinfo                                    NaN
punishmenttypeid                                          NaN
terminationreasonid                                       NaN
protocolarticlepartid                                     968
victimid                                                  NaN
victimpinpp                                               NaN
mainpunishmentamountsumm                                  NaN
mainpunishmentpaidamount                                  NaN
mainpunishmentlastpaytime                                 NaN
discountfordate70                                         NaN
discountamount70                                          NaN
discountfordate50                                         NaN
discountamount50                                          NaN
damageamount                                              NaN
damagetypeid                                              NaN
damagetypename                                            NaN
compensationamount                                        NaN
compensationpaidamount                                    NaN
Name: 0, dtype: object

In [6]:
df_renamed = df.copy()
df_renamed.rename(columns={'protocolid':'protocolId',
                           'createdtime':'createdTime',
                           'updatedtime':'updatedTime',
                           'violationtime':'violationTime',
                           'regionid':'regionId',
                           'districtid':'districtId',
                           'mtpid':'mtpId',
                           'pinpp':'pinpp',
                           'number':'number',
                           'series':'series',
                           'casestatus':'status',
                           'organid':'organId',
                           'lastname':'lastName',
                           'latitude':'latitude',
                           'victimid':'victimId',
                           'birthdate':'birthDate',
                           'firstname':'firstName',
                           'longitude':'longitude',
                           'secondname':'secondName',
                           'casestatusname':'statusName',
                           'victimpinpp':'victimPinpp',
                           'admcaseorgan':'admCaseOrgan',
                           'damageamount':'damageAmount',
                           'damagetypeid':'damageTypeId',
                           'inspectorfio':'inspectorFio',
                           'executiondate':'executionDate',
                           'admcaseorganid':'admCaseOrganId',
                           'damagetypename':'damageTypeName',
                           'decisiontypeid':'decisionTypeId',
                           'documentnumber':'documentNumber',
                           'documentseries':'documentSeries',
                           'inspectorpinpp':'inspectorPinpp',
                           'violatorgender':'violatorGender',
                           'resolutionorgan':'resolutionOrgan',
                           'decisiontypename':'decisionTypeName',
                           'discountamount50':'discountAmount50',
                           'discountamount70':'discountAmount70',
                           'punishmenttypeid':'punishmentTypeId',
                           'violatoractualaddressregionid':'violatorRegionId',
                           'discountfordate50':'discountForDate50',
                           'discountfordate70':'discountForDate70',
                           'resolutionorganid':'resolutionOrganId',
                           'compensationamount':'compensationAmount',
                           'inspectorbirthdate':'inspectorBirthdate',
                           'violatorintoxicationid':'intoxicationTypeId',
                           'mainpunishmenttype':'mainPunishmentType',
                           'violatoractualaddressdistrictid':'violatorDistrictId',
                           'protocolarticlepart':'protocolArticlePart',
                           'terminationreasonid':'terminationReasonId',
                           'violatorintoxicationname':'intoxicationTypeName',
                           'mainpunishmentamount':'mainPunishmentAmount',
                           'protocolarticlepartid':'protocolArticlePartId',
                           'compensationpaidamount':'compensationPaidAmount',
                           'resolutionconsiderinfo':'resolutionConsiderInfo',
                           'inspectorworkcertificate':'inspectorWorkCertificate',
                           'mainpunishmentamountsumm':'mainPunishmentAmountSumm',
                           'mainpunishmentpaidamount':'mainPunishmentPaidAmount',
                           'mainpunishmentlastpaytime':'mainPunishmentLastPayTime',
                           }, inplace=True)
df_renamed.head()

   protocolId                 createdTime                 updatedTime            violationTime  regionId  districtId   mtpId  organId protocolArticlePart inspectorWorkCertificate  inspectorPinpp isrealinspectorpinpp inspectorBirthdate  latitude  longitude series         number                         inspectorFio  status                          statusName      lastName firstName      secondName documentSeries documentNumber           pinpp isrealpinpp   birthDate violatorGender intoxicationTypeName  intoxicationTypeId  violatorRegionId  violatorDistrictId  decisionstatus decisionstatusname  decisionTypeId decisionTypeName executionDate mainPunishmentType mainPunishmentAmount  resolutionOrganId  admCaseOrganId        admCaseOrgan resolutionOrgan resolutionConsiderInfo  punishmentTypeId  terminationReasonId  protocolArticlePartId  victimId victimPinpp  mainPunishmentAmountSumm  mainPunishmentPaidAmount mainPunishmentLastPayTime discountForDate70  discountAmount70 discountForDate50  discountAmount50  damageAmount  damageTypeId damageTypeName  compensationAmount  compensationPaidAmount
0    49231179  2025-02-20 03:43:44.043334  2025-02-20 03:43:51.202054  2025-03-04 08:50:44.044        11         258  2775.0       14             52 - 2Q           ТV- I № 002019  30303975800011                    t         1997-03-03       NaN        NaN   PTVL  2507301773207            ASATOV FARRUX URAL O‘G‘LI       3                  KO`RIB CHIQILMOQDA     BASHIROVA    NOZIMA      NU’MONOVNA             AE        1477072  41207864160023           t  1986-07-12           AYOL                  NaN                 NaN                11                 258             NaN                NaN             NaN              NaN           NaN                NaN                  NaN                NaN              14  HPX (PROFILAKTIKA)             NaN                    NaN               NaN                  NaN                    968       NaN         NaN                       NaN                       NaN                       NaN               NaN               NaN               NaN               NaN           NaN           NaN            NaN                 NaN                     NaN
1    49231094  2025-02-20 03:43:44.043334  2025-02-20 03:43:51.202054   2025-03-04 08:46:19.65        11         258  2775.0       14             52 - 2Q           ТV- I № 002019  30303975800011                    t         1997-03-03       NaN        NaN   PTVL  2507301773122            ASATOV FARRUX URAL O‘G‘LI       3                  KO`RIB CHIQILMOQDA     RAXMONOVA   GULSHAN     FURQAT QIZI             AC        1205117  60102006020063           t  2000-02-01           AYOL                  NaN                 NaN                 7                 128             NaN                NaN             NaN              NaN           NaN                NaN                  NaN                NaN              14  HPX (PROFILAKTIKA)             NaN                    NaN               NaN                  NaN                    968       NaN         NaN                       NaN                       NaN                       NaN               NaN               NaN               NaN               NaN           NaN           NaN            NaN                 NaN                     NaN
2    49231016  2025-02-27 08:41:25.152334  2025-02-27 08:42:01.972133      2025-02-23 08:47:00        12         296  1323.0       14         161 - MODDA              FV-I 009711  31406954200080                    t         1995-06-14       NaN        NaN   PFAR  2507301773044  SOTVOLDIYEV MUZAFFAR UMIDBEK O‘G‘LI       3                  KO`RIB CHIQILMOQDA       NIZOMOV  BOTIRALI  ABDUMALIKOVICH             AD        3941205  32703887020019           t  1988-03-27          ERKAK                  NaN                 NaN                12                 296             NaN                NaN             NaN              NaN           NaN                NaN                  NaN                NaN              14  HPX (PROFILAKTIKA)             NaN                    NaN               NaN                  NaN                   1453       NaN         NaN                       NaN                       NaN                       NaN               NaN               NaN               NaN               NaN           NaN           NaN            NaN                 NaN                     NaN
3    49228807  2025-02-11 19:27:44.746846  2025-02-11 19:27:52.666441  2025-03-04 04:02:26.856        12         285  1243.0       14     61  - PRIM-2 1Q              FV-I 006963  32210986900015                    t         1998-10-22       NaN        NaN   PFAR  2507301770835   ABDULLAYEV SHERZOD BAXTIYOR O‘G‘LI       3                  KO`RIB CHIQILMOQDA  TOSHPULATOVA   UG‘ILOY       MUSOYEVNA             AD        9495283  41411874140096           t  1987-11-14           AYOL                  NaN                 NaN                12                 285             NaN                NaN             NaN              NaN           NaN                NaN                  NaN                NaN              14  HPX (PROFILAKTIKA)             NaN                    NaN               NaN                  NaN                    994       NaN         NaN                       NaN                       NaN                       NaN               NaN               NaN               NaN               NaN           NaN           NaN            NaN                 NaN                     NaN
4    49226121  2025-02-09 15:30:14.507008  2025-03-03 23:13:14.727685  2025-03-03 22:38:51.484         6         115  5854.0       14          41 - MODDA               АD-2181936  31211955910018                    t         1995-11-12       NaN        NaN   PNAM  2507301768149   XOLDAROV ALISHER ABDURASHID O‘G‘LI       9  SUDGA KO'RIB CHIQISH U-N YUBORILDI   HAYITMATOVA  NISHONBI   RAXMATJONOVNA             AD        7357357  42407842210024           t  1984-07-24           AYOL                  NaN                 NaN                 6                 115             NaN                NaN             NaN              NaN           NaN                NaN                  NaN                NaN              14  HPX (PROFILAKTIKA)             NaN                    NaN               NaN                  NaN                    906       NaN         NaN                       NaN                       NaN                       NaN               NaN               NaN               NaN               NaN           NaN           NaN            NaN                 NaN                     NaN

In [11]:
try:
	param = df_renamed.iloc[0]
	print(param['createdTime'])
	pd.to_datetime(param['createdTime'], format='%Y-%m-%d %H:%M:%S.%f').dt.strftime('%d-%m-%Y %H:%M:%S')
except Exception as e:
    print(f"An error occurred: {e}")

20-02-2025 03:43:44
An error occurred: time data "20-02-2025 03:43:44" at position 0 doesn't match format specified

In [8]:
df_renamed['createdTime'] = pd.to_datetime(df_renamed['createdTime'], format='%Y-%m-%d %H:%M:%S.%f').dt.strftime('%d-%m-%Y %H:%M:%S')
df_renamed['updatedTime'] = pd.to_datetime(df_renamed['updatedTime'], format='%Y-%m-%d %H:%M:%S.%f').dt.strftime('%d-%m-%Y %H:%M:%S')
df_renamed['violationTime'] = pd.to_datetime(df_renamed['violationTime'], format='%Y-%m-%d %H:%M:%S.%f').dt.strftime('%d-%m-%Y %H:%M:%S')
df_renamed['inspectorBirthdate'] = pd.to_datetime(df_renamed['inspectorBirthdate'], format='%Y-%m-%d').dt.strftime('%d-%m-%Y %H:%M:%S')
df_renamed['birthDate'] = pd.to_datetime(df_renamed['birthDate'], format='%Y-%m-%d').dt.strftime('%d-%m-%Y %H:%M:%S')
df_renamed['number'] = df_renamed['number'].astype(str)

In [9]:
print(df_renamed.iloc[0]['createdTime'], '|||', df.iloc[0]['createdtime'])
print(df_renamed.iloc[0]['updatedTime'], '|||', df.iloc[0]['updatedtime'])
print(df_renamed.iloc[0]['violationTime'], '|||', df.iloc[0]['violationtime'])
print(df_renamed.iloc[0]['inspectorBirthdate'], '|||', df.iloc[0]['inspectorbirthdate'])
print(df_renamed.iloc[0]['birthDate'], '|||', df.iloc[0]['birthdate'])
print(type(df_renamed.iloc[0]['number']), '|||', type(df.iloc[0]['number']))
print(df_renamed.iloc[0]['mtpId'], '|||', df.iloc[0]['mtpid'])

20-02-2025 03:43:44 ||| 2025-02-20 03:43:44.043334
20-02-2025 03:43:51 ||| 2025-02-20 03:43:51.202054
04-03-2025 08:50:44 ||| 2025-03-04 08:50:44.044
03-03-1997 00:00:00 ||| 1997-03-03
12-07-1986 00:00:00 ||| 1986-07-12
<class 'str'> ||| <class 'numpy.int64'>
2775.0 ||| 2775.0

0   protocolid                       552565 non-null  int64  
 1   createdtime                      552565 non-null  object
 2   updatedtime                      552565 non-null  object 
 3   violationtime                    552565 non-null  object 
 4   regionid                         552565 non-null  int64  
 5   districtid                       552565 non-null  int64  
 6   mtpid                            308499 non-null  float64
 7   organid                          552565 non-null  int64  
 8   protocolarticlepart              552565 non-null  object 
 9   inspectorworkcertificate         541500 non-null  object 
 10  inspectorpinpp                   541500 non-null  object 
 11  isrealinspectorpinpp             541500 non-null  object ----
 12  inspectorbirthdate               541500 non-null  object 
 13  latitude                         154418 non-null  float64
 14  longitude                        154418 non-null  float64
 15  series                           552565 non-null  object 
 16  number                           552565 non-null  int64  
 17  inspectorfio                     552565 non-null  object 
 18  casestatus                       552565 non-null  int64  
 19  casestatusname                   552565 non-null  object 
 20  lastname                         552565 non-null  object 
 21  firstname                        552565 non-null  object 
 22  secondname                       552126 non-null  object 
 23  documentseries                   552560 non-null  object 
 24  documentnumber                   552565 non-null  object 
 25  pinpp                            552565 non-null  object 
 26  isrealpinpp                      552565 non-null  object ----
 27  birthdate                        552565 non-null  object 
 28  violatorgender                   552565 non-null  object 
 29  violatorintoxicationname         17935 non-null   object 
 30  violatorintoxicationid           17935 non-null   float64
 31  violatoractualaddressregionid    552552 non-null  float64
 32  violatoractualaddressdistrictid  552552 non-null  float64
 33  decisionstatus                   542392 non-null  float64 ----
 34  decisionstatusname               542392 non-null  object ----
 35  decisiontypeid                   542392 non-null  float64
 36  decisiontypename                 542392 non-null  object 
 37  executiondate                    448342 non-null  object 
 38  mainpunishmenttype               501096 non-null  object 
 39  mainpunishmentamount             501096 non-null  object 
 40  resolutionorganid                542392 non-null  float64
 41  admcaseorganid                   552565 non-null  int64  
 42  admcaseorgan                     552565 non-null  object 
 43  resolutionorgan                  542392 non-null  object 
 44  resolutionconsiderinfo           542392 non-null  object 
 45  punishmenttypeid                 501096 non-null  float64
 46  terminationreasonid              40443 non-null   float64
 47  protocolarticlepartid            552565 non-null  int64  
 48  victimid                         29400 non-null   float64
 49  victimpinpp                      29400 non-null   object 
 50  mainpunishmentamountsumm         479417 non-null  float64
 51  mainpunishmentpaidamount         479417 non-null  float64
 52  mainpunishmentlastpaytime        303504 non-null  object 
 53  discountfordate70                440192 non-null  object 
 54  discountamount70                 444905 non-null  float64
 55  discountfordate50                427010 non-null  object 
 56  discountamount50                 427010 non-null  float64
 57  damageamount                     21775 non-null   float64
 58  damagetypeid                     21775 non-null   float64
 59  damagetypename                   21775 non-null   object 
 60  compensationamount               3772 non-null    float64
 61  compensationpaidamount           3772 non-null    float64

In [10]:
df_renamed.to_csv('processed_fevral_2025_created_time.csv')